app/views/shared/_matomo.html.haml

closes https://sentry.io/organizations/betagouv-f7/issues/2380592450/?environment=production&project=5747178

check if event.data.timing is null or undefined

---

config/locales/views.fr.yml

Met à jour le titre de la page d'accueil

---

app/views/shared/_tarteaucitron.html.haml

add integrity for tarte au citron

---

app/controllers/feedbacks_controller.rb
app/controllers/landings_controller.rb
app/controllers/shared_controller.rb
app/views/landings/new_solicitation.html.haml
app/views/solicitations/_solicitation.haml
config/brakeman.ignore
spec/controllers/shared_controller_spec.rb

sanitize inputs

---

app/views/about/mentions_d_information.fr.html.erb
app/views/shared/_tarteaucitron.html.erb
config/initializers/content_security_policy.rb

Met a jour le tag pour Google Ads

---

config/initializers/content_security_policy.rb

closes https://sentry.io/organizations/betagouv-f7/issues/2430399805/?project=5747178&query=is%3Aunresolved

ajoute api-adresse aux csp

---

config/initializers/content_security_policy.rb

add csp img-src

---

app/views/needs/add_match.js.haml

Fix erreur js lors de l'ajout d'un nouveau conseiller

---

app/views/landings/_gtag_conversion.html.erb
app/views/landings/_new_solicitation_thank_you.html.haml
app/views/needs/add_match.js.haml

add gtag conversion

---

app/assets/stylesheets/pages/index.sass
app/views/landings/_index_landing_cards.html.haml

Page d'accueil avec cards responsive sur 2 colonnes

---

app/helpers/breadcrumbs_helper.rb
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_index_landing_card.html.haml
app/views/landings/_index_landing_cards.html.haml
app/views/landings/new_solicitation.html.haml
app/views/pages/_breadcrumbs.html.haml

Amelioration iframe Martinique avec ajout institution dans les url Landing

---

Gemfile
Gemfile.lock
app/admin/territory.rb
config/locales/models.fr.yml
doc/01-setup.md
doc/02-development.md
doc/03-deployment.md
doc/04-architecture.md
doc/05-deployer-une-region.md
lib/tasks/deploy_region.rake

- close #1789 (c'est la révolution !)

Script déploiement région

---

app/front/javascripts/pages/siret_autocomplete.js
app/models/territory.rb
config/locales/views.fr.yml
db/seeds.rb
doc/04-architecture.md
doc/05-deployer-une-region.md

- corrige le problème d'identification du code région Martinique en js
- affine la détection des régions déployées

Amélioration process déploiement

---

app/views/landings/_gtag_conversion.html.erb
app/views/shared/_tarteaucitron.html.erb

creates tac variable for gtag

---

app/mailers/expert_mailer.rb
spec/mailers/expert_mailer_spec.rb

N'envoie des relances que pour les besoins de + de 4 jours

---

app/helpers/iframe_custom_css_helper.rb

MaJ style iframe Martinique

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/annuaire/advisors_controller.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/user.rb
app/services/expert_reminder_service.rb
config/locales/models.fr.yml
spec/factories/experts.rb
spec/factories/experts_subjects.rb
spec/factories/matches.rb
spec/factories/users.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
spec/models/user_spec.rb
spec/policies/expert_policy_spec.rb
spec/services/csv_import/user_importer_spec.rb

masque par défaut les utilisateurs supprimés

---

app/views/companies/_company.html.haml
config/locales/fr.yml
config/locales/views.fr.yml

Ajout d'info sur entreprise diffusable commercialement

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/annuaire/advisors_controller.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/user.rb
app/services/expert_reminder_service.rb
config/locales/models.fr.yml
spec/factories/experts.rb
spec/factories/experts_subjects.rb
spec/factories/matches.rb
spec/factories/users.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
spec/models/user_spec.rb
spec/policies/expert_policy_spec.rb
spec/services/csv_import/user_importer_spec.rb

Reverts betagouv/place-des-entreprises#1832

Revert "masque par défaut les utilisateurs supprimés"

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/annuaire/advisors_controller.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/user.rb
app/services/expert_reminder_service.rb
config/locales/models.fr.yml
spec/factories/experts.rb
spec/factories/experts_subjects.rb
spec/factories/matches.rb
spec/factories/users.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
spec/models/user_spec.rb
spec/policies/expert_policy_spec.rb
spec/services/csv_import/user_importer_spec.rb

Reverts betagouv/place-des-entreprises#1834

Revert du "Revert "masque par défaut les utilisateurs supprimés""

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/annuaire/advisors_controller.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/user.rb
app/services/expert_reminder_service.rb
config/locales/models.fr.yml
spec/factories/experts.rb
spec/factories/experts_subjects.rb
spec/factories/matches.rb
spec/factories/users.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
spec/models/user_spec.rb
spec/policies/expert_policy_spec.rb
spec/services/csv_import/user_importer_spec.rb

Reverts betagouv/place-des-entreprises#1837

Revert "Revert du "Revert "masque par défaut les utilisateurs supprimés"""

---

lib/tasks/transfer_bizdev.rake

close #1829 
En attente d'un accord sur les règles à suivre :)

Procédure départ bizdev

---

app/models/expert.rb
app/models/user.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb
spec/services/csv_import/user_importer_spec.rb

Import - rend optionnel le numéro de téléphone

---

app/models/concerns/person_concern.rb
spec/services/csv_import/user_importer_spec.rb

Import - Ajoute un 0 aux numéro de téléphone si Excel l'a supprimé

---

app/helpers/person_helper.rb
app/models/concerns/diagnosis_creation.rb
app/models/concerns/person_concern.rb
app/models/contact.rb
app/models/user.rb
app/services/csv_export/user_exporter.rb
app/services/csv_import/user_importer.rb
config/locales/models.fr.yml
spec/factories/experts.rb
spec/models/contact_spec.rb
spec/models/expert_spec.rb
spec/services/csv_export/user_exporter_spec.rb
spec/services/csv_import/user_importer_spec.rb

Import - supprimer le rôle de l'équipe à l'import

---

app/services/csv_import/base_importer.rb
spec/services/csv_import/base_importer_spec.rb

close #1852 
Evite les erreurs sur les lignes vides uniquement (car je n'ai pas trouvé d'erreur en cas de colonne vide :thinking: )

Import - pas d'erreur en cas de ligne blanche

---

app/admin/subject.rb
app/models/concerns/archivable.rb
config/locales/models.fr.yml

Première étape pour #1857 qui permet de voir par défaut les sujets non archivés
closes #1857

Ajoute des scopes pour les sujets archivés/non archivés en admin

---

app/views/shared/_tarteaucitron.html.erb
config/initializers/content_security_policy.rb

Add nonce to tarteaucitron script

---

app/views/annuaire/advisors/_table.html.haml

.... Je suis confuse. En fait, il n'y a que ça à faire pour close #1854 ?
J'ai la sensation de passer à côté de quelque chose :thinking:

Suppression de la description du sujet d'institution ds annuaire

---

app/models/antenne.rb
app/services/csv_import/antenne_importer.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
spec/services/csv_import/antenne_importer_spec.rb
spec/services/csv_import/user_importer_spec.rb

Import - plus de tolérance pour le nom des antennes

---

app/admin/expert.rb
app/models/expert.rb
config/locales/models.fr.yml

J'en ai profité pour supprimer le flag d'édition de ses compétences
closes #1859

traduit intervention criteria

---

app/admin/contact.rb
app/admin/expert.rb
spec/factories/contacts.rb
spec/factories/landing_topics.rb
spec/features/admin_controller_feature_spec.rb

Répare rôle manquant dans admin/contact + tests

---

app/controllers/annuaire/advisors_controller.rb
app/views/annuaire/advisors/_table.html.haml
app/views/annuaire/advisors/index.html.haml

Fix annuaire column order

---

app/controllers/annuaire/advisors_controller.rb
app/front/stylesheets/components/table.sass
app/views/annuaire/advisors/_table.html.haml
config/locales/views.fr.yml

Améliore la visualisation des anomalies de l'annuaire

---

spec/features/admin_controller_feature_spec.rb
spec/system/pages_system_spec.rb
spec/system_helper.rb

Add system tests for public pages

---

app/services/stats/quality/needs_done_no_help_stats.rb

Répare une stat qualité (done_no_help)

---

app/controllers/needs_controller.rb
config/locales/views.fr.yml
spec/system/needs_system_spec.rb
spec/system_helper.rb

Ajout de system tests Demandes reçues

---

config/initializers/active_admin.rb

change link to website in admin

---

app/services/csv_export/antenne_exporter.rb
app/services/csv_export/base_exporter.rb
app/services/csv_export/user_exporter.rb

trie les utilisateurs par antenne puis nom d'équipe dans l'export

---

app/models/concerns/person_concern.rb
spec/services/csv_import/user_importer_spec.rb

Import - retire les accents dans les emails

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
vendor/assets/stylesheets/active_admin.scss

Parce que le thème des années 2000 ça va bien deux minutes. J'ai fait ça vite fait mais ça rajoute un peu de couleurs. À voir si le reste de l'équipe préfère ça ou l'autre

add theme for active admin

---

app/models/clockwork.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/user.rb
app/services/unused_users_service.rb
spec/mailers/user_mailer_spec.rb
spec/services/unused_users_service_spec.rb

supprime les utilisateurs jamais connectés invités il y a plus de 7 mois

---

app/services/stats/matches/transmitted_less_than_72h_stats.rb

https://sentry.io/organizations/betagouv-f7/issues/2633962672/?environment=production&project=5747178&referrer=alert_email

corrige une erreur 500 sur la page stats de l'equipe

---

app/helpers/breadcrumbs_helper.rb
spec/system/pages_system_spec.rb

Répare breadcrumb stats

---

app/models/concerns/diagnosis_creation.rb
app/models/solicitation.rb
app/services/create_diagnosis/find_relevant_expert_subjects.rb
spec/factories/landing_subjects.rb
spec/factories/landing_themes.rb
spec/factories/landings.rb
spec/models/concerns/diagnosis_creation_spec.rb
spec/models/solicitation_spec.rb

Suppression du champs et mentions de 'preselected_institutions'

---

app/models/landing_subject.rb
db/migrate/20210822134423_create_landing_subjects.rb
db/migrate/20210914125531_change_landing_subjects_slugs.rb
db/schema.rb

Add uniqueness to landing subject slugs

---

app/models/solicitation.rb
app/services/csv_export/match_exporter.rb

return nil for solicitation.region if code_region.nil?

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
app/views/devise/passwords/edit.html.haml
app/views/users/registrations/password.html.haml
config/initializers/devise.rb
config/locales/devise.fr.yml
config/locales/models.fr.yml
config/routes.rb
spec/factories/users.rb
spec/features/application_controller_feature_spec.rb
spec/features/signin_spec.rb
spec/features/users/registrations_controller_spec.rb
spec/models/user_spec.rb
spec/system/users/invitations_controller_spec.rb

Augmenter la complexité du mot de passe

---

app/assets/stylesheets/pages/landing.sass
app/views/landings/landing_subjects/_new_solicitation_thank_you.html.haml
app/views/landings/landing_subjects/show.html.haml
config/locales/views.fr.yml

Message remerciement iframes

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/match.rb
app/admin/solicitation.rb
app/models/expert.rb
config/locales/models.fr.yml

Ajoute, modifie des filtres en admin

---

app/assets/stylesheets/application/solicitation.sass

Une PR qui va tout changer

---

app/services/csv_import/antenne_importer.rb
app/services/csv_import/base_importer.rb
spec/services/csv_import/antenne_importer_spec.rb

ne prends pas en compte les espaces dans les headers des csv

---

app/admin/user.rb

Fix missing phone_number

---

app/services/xlsx_export/user_exporter.rb

supprime la colonne institution de l'export excel

---

app/admin/solicitation.rb
config/locales/views.fr.yml
doc/05-deployer-une-region.md

close #1988
close #1989 
close #1991

Déploiement Bzh - compléments

---

app/controllers/pages_controller.rb
app/views/shared/_tarteaucitron.html.erb
config/locales/views.fr.yml

closes #1978 
J'ai essayé de mettre le texte dans une variable I18n mais ça n'apparaissait pas

update cookies text

---

app/front/stylesheets/components/components.sass

close #1765
Je ne sais pas si on clôture le ticket mais c'est plus utilisable. Il reste la liste `ol` avec les numéros qui s'affichent mais j'ai pas trouvé comment faire, et deux trois patouilles à droite à gauche mais rien d’handicapant.

IE imporvements

---

app/admin/solicitation.rb
app/models/solicitation.rb
app/services/csv_export/match_exporter.rb
app/services/csv_export/solicitation_exporter.rb
config/locales/models.fr.yml

closes #1969 
/!\ merger d'abord fusion-export

Amélioration fichier export solicitation

---

app/controllers/landings/landing_themes_controller.rb
config/initializers/content_security_policy.rb
package.json
spec/controllers/diagnoses/steps_controller_spec.rb
spec/models/diagnosis_spec.rb
spec/models/search_spec.rb
spec/models/subject_spec.rb
spec/services/csv_import/antenne_importer_spec.rb
spec/services/csv_import/base_importer_spec.rb
spec/services/csv_import/user_importer_spec.rb
yarn.lock

Plein de micro trucs de la session de debug sentry du jour

Csp update

---

app/controllers/annuaire/antennes_controller.rb
app/controllers/annuaire/base_controller.rb
app/controllers/annuaire/institutions_controller.rb
app/controllers/annuaire/users_controller.rb
app/front/stylesheets/application.sass
app/front/stylesheets/pages/annuaire.sass
app/helpers/institutions_helper.rb
app/models/antenne.rb
app/models/institution.rb
app/models/territory.rb
app/models/user.rb
app/policies/institution_policy.rb
app/views/annuaire/_search.html.haml
app/views/annuaire/antennes/index.html.haml
app/views/annuaire/institutions/_table.html.haml
app/views/annuaire/institutions/index.html.haml
app/views/annuaire/users/_table.html.haml
app/views/annuaire/users/index.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/annuaire/antennes_controller_spec.rb
spec/controllers/annuaire/institutions_controller_spec.rb
spec/controllers/annuaire/users_controller_spec.rb

Ajoute un filtre pour les région dans l'annuaire

---

app/views/shared/_tarteaucitron.html.erb
config/initializers/content_security_policy.rb

ajoute un service TAC pour Google ads

---

app/models/antenne.rb
app/models/concerns/person_concern.rb
app/services/csv_import.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
app/views/annuaire/antennes/_import_buttons.html.haml
app/views/annuaire/antennes/import.html.haml
app/views/annuaire/base/_import_errors.html.haml
app/views/annuaire/institutions/index.html.haml
app/views/annuaire/users/_import_buttons.html.haml
app/views/annuaire/users/import.html.haml
config/locales/views.fr.yml
spec/services/csv_import/user_importer_spec.rb

J'ai pas réussi à enlever les `\r` dans l'import. Ca fonctionne dans les tests parce que le CSV est sous forme de string mais dans les cas réels c'est un tempfile. Et pour enlever les `\r` il faut l'ouvrir sauf qu'on ne peut pas parce qu'on a une erreur à cause de ce `\r`j ustement.
closes #2056

optimisation de l'import

---

app/views/solicitations/_solicitation.haml
app/views/solicitations/remove.js.haml

Corrige la suppression des cartes sollicitations

---

app/views/companies/_facility_infos.html.haml

Ajoute la mention RM ou RCS sur la fiche d'un besoin

---

app/assets/stylesheets/mailers.sass
app/front/stylesheets/components/cards.sass
app/helpers/institutions_helper.rb
app/helpers/regions_helper.rb
app/views/solicitations/_solicitation.haml

solicitations cards style update

---

app/views/solicitations/_solicitation.haml

Correction d'une erreur introduite avec #2060

Fix condition doublon 

---

app/admin/expert.rb
config/locales/views.fr.yml

met à jour la page formulaire des experts en admin

---

app/assets/stylesheets/pages/landing.sass
app/helpers/breadcrumbs_helper.rb
app/views/landings/landing_subjects/_new_solicitation_thank_you.html.haml
app/views/landings/landing_subjects/show.html.haml
app/views/landings/landings/_pde_partnership_mention.html.haml
app/views/pages/_breadcrumbs.html.haml
config/locales/views.fr.yml

optimisations iframes

---

app/admin/territory.rb

closes #une_idee_que_jai_eu_dans_le_train_hier

Applique le même affichage des codes insee pour les territoire que les antennes

---

app/views/about/mentions_d_information.fr.html.erb
app/views/landings/landing_subjects/_new_solicitation_thank_you.html.haml
app/views/landings/landing_subjects/_tags_conversion.html.erb
config/initializers/content_security_policy.rb

Ajoute un event Fb

---

config/locales/views.fr.yml

Pour que ça rentre sur une seule ligne dans Google

Modifie le titre de l'accueil

---

app/mailers/user_mailer.rb

N'envoie pas d'email si le commentaire a été supprimé entre temps

---

app/admin/match.rb
app/admin/need.rb
config/locales/models.fr.yml

Cacher les MER en cours

---

app/admin/antenne.rb

Ce que je pensais cassé ne l'était pas, mais j'en ai profité pour améliorer les filtres sujets.

Filtre sujet par institution

---

app/models/institution.rb

Fix institution available_subjects

---

spec/features/admin_controller_feature_spec.rb

Fix subjects

---

app/front/javascripts/application/insee_code_field.js
app/views/feedbacks/create.js.haml
app/views/shared/_sentry.html.erb
config/initializers/sentry.rb

close #2112 
close #2111 
close #2110

Little fixes

---

app/front/javascripts/pages/siret_autocomplete.js
app/views/landings/landing_subjects/_new_solicitation_form.html.haml

n'affiche pas d'alerte pour les SIRET hors région pour FTE

---

app/services/csv_import.rb
app/services/csv_import/base_importer.rb
spec/fixtures/files/antennes-with-blank-rows.csv
spec/services/csv_import/antenne_importer_spec.rb

J'ai fait un test pour l'import d'antennes mais ça fonctionne aussi pour les utilisateurs
closes #2123

Ignore les lignes vides à l'import

---

config/locales/fr.yml

Répare le décalage de mois des stats

---

app/models/concerns/person_concern.rb
spec/fixtures/files/users-with-comma-in-emails.csv
spec/services/csv_import/user_importer_spec.rb

remplace les virgules et points virgules dans les emails

---

app/assets/stylesheets/pages/stats.sass
app/controllers/stats/team_controller.rb
app/models/match.rb
app/services/stats/matches/all.rb
app/services/stats/matches/positioning_rate.rb
app/views/stats/team/_tabs.html.haml
config/locales/views.fr.yml

Ajoute les stats sur le taux de positionnement

---

lib/tasks/fake_test_iframes.rake

Script de creation d'iframes de test

---

bin/rails
bin/rake
bin/setup
bin/spring
bin/yarn
config.ru
config/application.rb
config/boot.rb
config/environment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/application_controller_renderer.rb
config/initializers/assets.rb
config/initializers/backtrace_silencers.rb
config/initializers/filter_parameter_logging.rb
config/initializers/mime_types.rb
config/initializers/permissions_policy.rb
config/initializers/wrap_parameters.rb
config/puma.rb

Pendant la mise à jour vers Rails 6.1 je n'avais pas fait `rails app:update` il me semble du coup il manque des fichiers. J'avoue ne pas trop savoir pourquoi ça fonctionnait quand même.

Ajoutes des fichiers manquants de la mise à jour vers Rails 6.1

---

app/admin/helpers/links.rb
app/admin/solicitation.rb
config/locales/models.fr.yml
config/locales/views.fr.yml

Changements visibles sur `/admin/solicitations` 
closes #2170

ajoute un lien vers la fiche besoin sur l'index des sollicitations en admin

---

app/models/clockwork.rb
config/locales/models.fr.yml
lib/tasks/anonymize_old_diagnoses.rake
spec/tasks/anonymize_old_companies_spec.rb

Champs 🌾🚜 anonymisés
- Company
- name
- siren
- Facility
- siret
- Contact
- email
- full_name
- phone_number
- Solicitation
- email
- full_name
- phone_number
- siret
closes #2167

Anonymise les analyses créées il y a plus de 3 ans

---

app/admin/institution.rb
app/controllers/annuaire/antennes_controller.rb
app/helpers/institutions_helper.rb
app/services/stats/base_stats.rb
app/services/stats/matches/transmitted_less_than_72h_stats.rb
app/services/stats/public/solicitations_in_deployed_regions_stats.rb
app/services/stats/public/taking_care_time_stats.rb
app/views/annuaire/institutions/_table.html.haml
app/views/needs/_received_needs.haml
app/views/reminders/_need.haml

pages : 
- annuaire/institutions
- relances
- stats public et équipe
- annuaire/antennes
- admin/institutions
autres : 
- affichage des logos d'institutions
closes #2176

quelques optimisations pour le chargement de page

---

app/views/application/_head.html.haml
app/views/layouts/pages.html.haml
app/views/shared/_iframe_resizer.html.erb

close #2168 
Documentation pour les partenaires mise à jour : https://docs.google.com/document/d/12mhE5bf91lAXCoFhM6w2xlvxeAo0KmoLOdvVshaX2cE/edit#
Site de démonstration : https://betagouv.github.io/place-des-entreprises-test-iframes

Add resizer to iframes

---

app/admin/solicitation.rb

masque le lien vers la fiche besoin sur /admin/solicitations si l'analyse n'est pas terminé

---

app/front/javascripts/shared/controllers/siret_autocomplete_controller.js
app/services/api_consumption/models/base.rb
app/services/search_etablissement.rb
spec/services/api_consumption/models/facility_autocomplete_spec.rb

Attrape les erreurs apiEntreprise proprement et les log pour debug

---

app/admin/landing.rb
app/models/landing.rb
spec/models/landing_spec.rb

Ajout de liens pour mettre à jour iframe 360

---

app/services/csv_export/match_exporter.rb

Ajoute une colonne RCS et RM à l'export des MER

---

app/models/diagnosis.rb
app/views/diagnoses/steps/matches.html.haml
app/views/diagnoses/steps/needs.html.haml
app/views/diagnoses/steps/visit.html.haml
config/locales/models.fr.yml
spec/models/diagnosis_spec.rb

Empecher de valider un besoin sans MER

---

app/controllers/annuaire/users_controller.rb
app/policies/institution_policy.rb
app/views/annuaire/users/_table.html.haml
app/views/annuaire/users/index.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/annuaire/users_controller_spec.rb

Pouvoir envoyer des invitations depuis l'annuaire

---

app/controllers/diagnoses_controller.rb
app/models/concerns/diagnosis_creation.rb
app/models/use_cases/search_facility.rb
config/locales/models.fr.yml
spec/models/concerns/diagnosis_creation_spec.rb

Ajoute une erreur quand une commune n'est pas trouvée (SIRET étrangers)

---

app/services/api_consumption/models/facility_autocomplete.rb
app/services/api_entreprise/api_entreprise_error.rb
app/services/api_entreprise/entreprise/base.rb
spec/services/api_entreprise/entreprise/base_spec.rb

Prévention des erreurs liées aux APIS quand elles sont en vrac mais n'envoient pas de code erreur

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/user.rb
app/models/antenne.rb
app/models/concerns/soft_deletable.rb
app/models/expert.rb
app/models/institution.rb
app/models/user.rb
config/locales/models.fr.yml
spec/models/concerns/soft_deletable_spec.rb

Met à jour la suppression des utilisateurs, experts, antennes et institutions

---

app/controllers/utilities_controller.rb
app/front/javascripts/shared/controllers/siret_autocomplete_controller.js
app/services/search_etablissement.rb

Improve search etablissement

---

app/views/landings/landing_subjects/_new_solicitation_form.html.haml
config/locales/views.fr.yml

Changement du label siret pour dépot solicitation

---

app/controllers/annuaire/users_controller.rb
app/views/annuaire/users/_import_buttons.html.haml
app/views/annuaire/users/_table.html.haml
app/views/annuaire/users/index.html.haml

affiche les invitations pour les utilisateurs importés uniquement

---

app/models/feedback.rb
spec/models/feedback_spec.rb

Ne pas envoyer d'email des commentaires si l'expert n'est pas encore positionné

---

config/locales/views.fr.yml

Mise à jour champs siret

---

app/models/concerns/diagnosis_creation.rb
app/models/facility.rb
app/services/api_adresse/search_municipality.rb
app/services/api_geo/query.rb
spec/fixtures/files/api_adresse_search_municipality.json
spec/models/concerns/diagnosis_creation_spec.rb

MER automatique pour les solicitations sans siret

---

app/controllers/emails/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/services/process_solicitation_with_email.rb
app/views/solicitations/_solicitation_actions.html.haml
config/locales/views.fr.yml
spec/features/solicitations/send_generic_emails_spec.rb

amélioration des mails automatiques des solicitations

---

app/services/create_diagnosis/find_relevant_expert_subjects.rb
spec/services/create_diagnosis/find_relevant_expert_subjects_spec.rb

N'exclue pas les experts si le sujet du filtre est différent du sujet du besoin

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/application/_flashes.html.haml
app/views/mailers/solicitation_mailer/creation.html.haml
app/views/mailers/solicitation_mailer/independent_tva.html.haml
app/views/mailers/solicitation_mailer/intermediary.html.haml
app/views/mailers/solicitation_mailer/particular_retirement.html.haml
app/views/mailers/solicitation_mailer/recruitment_foreign_worker.html.haml
config/locales/views.fr.yml
spec/mailers/previews/solicitation_mailer_preview.rb

New emails

---

app/controllers/solicitations_controller.rb
app/models/solicitation.rb

ordonne les sollicitation par ordre de création et en affiche 50 par page au lieu de 100

---

app/assets/stylesheets/pages/landing-cards.sass
app/views/landings/landings/_multiple_steps.html.haml
app/views/shared/_iframe_resizer.html.erb

2 cols iframe

---

app/controllers/reports_controller.rb
app/views/reports/index.html.haml
config/locales/views.fr.yml
spec/models/need_spec.rb

affiche les exports de données disponibles après la création de l'antenne

---

app/controllers/emails/solicitations_controller.rb
app/views/solicitations/_solicitation_actions.html.haml

garde la recherche après avoir envoyé un email de sollciitation

---

app/admin/antenne.rb

enleve les anciens champs de formulaire de responsables d'antennes

---

app/controllers/diagnoses/steps_controller.rb
app/helpers/solicitation_helper.rb
app/views/solicitations/_solicitation_actions.html.haml
spec/controllers/diagnoses/steps_controller_spec.rb

reste sur la même page et redirige vers les sollicitations après une analyse

---

app/views/mailers/solicitation_mailer/creation.html.haml
app/views/mailers/solicitation_mailer/independent_tva.html.haml
app/views/mailers/solicitation_mailer/particular_retirement.html.haml
app/views/mailers/solicitation_mailer/recruitment_foreign_worker.html.haml
config/locales/views.fr.yml

update tva email and fix missing translation

---

.rubocop.yml
app/helpers/solicitation_helper.rb
app/views/solicitations/_solicitation.haml
config/locales/views.fr.yml
spec/helpers/solicitations_helper_spec.rb

affiche la région de la sollicitation quand il n'y a pas de région sélectionnée

---

app/views/landings/landing_subjects/_new_solicitation_form.html.haml
config/locales/views.fr.yml

ajoute une aide pour trouver le siret sur annuaire-entreprise

---

config/locales/views.fr.yml

met à jour l'email de tva - sie

---

app/models/concerns/diagnosis_creation.rb
app/models/subject.rb
spec/models/concerns/diagnosis_creation_spec.rb
spec/services/create_diagnosis/create_matches_spec.rb

Stopper l'analyse à l'étape besoins si la solicitation a pour sujet "autre demande"

---

app/controllers/solicitations_controller.rb

Suppression d'1 cache peu utile et posant problème

---

app/controllers/landings/landing_subjects_controller.rb
app/models/solicitation.rb
app/services/solicitation_modification/base.rb
app/services/solicitation_modification/create.rb
app/services/solicitation_modification/update_all_created_in_deployed_region.rb
db/migrate/20210527132241_add_region_deployed_at_fields.rb
lib/tasks/update_solicitations_code_region.rake
spec/models/solicitation_spec.rb
spec/services/solicitation_modification/create_spec.rb
spec/services/solicitation_modification/update_spec.rb

corrige le fait qu'une sollicitation est déclarée hors région ou non

---

app/front/stylesheets/base.sass
app/front/stylesheets/components/components.sass
app/front/stylesheets/typo.sass
app/front/stylesheets/utilities.sass
app/views/solicitations/_solicitation_actions.html.haml
config/locales/views.fr.yml

Met à jour le style des boutons d'action d'une sollicitation

---

app/controllers/emails/solicitations_controller.rb
app/services/cancel_solicitation_with_email.rb
config/locales/fr.yml
spec/features/solicitations/send_generic_emails_spec.rb
spec/services/cancel_solicitation_with_email_spec.rb

Correction oubli changement statut solicitation

---

app/models/solicitation.rb

Ajoute la possibilité d'abandonner plusieurs fois une sollicitation

---

app/controllers/landings/base_controller.rb
app/controllers/landings/landing_subjects_controller.rb
app/views/landings/landing_subjects/_new_solicitation_form.html.haml
spec/features/new_solicitation_feature_spec.rb

Preremplissage du siret dans les iframes

---

app/admin/landing.rb
app/helpers/images_helper.rb
app/views/landings/landings/_logos.html.haml
app/views/landings/landings/show.haml
db/migrate/20220316105619_remove_logos_to_landings.rb
db/schema.rb

répare l'affichage des logos sur contactez-nous

---

app/admin/landing_theme.rb

Move landing subject archived_at  field

---

app/admin/expert.rb
app/controllers/reminders/experts_controller.rb
app/models/expert.rb
app/models/feedback.rb
app/models/need.rb
app/views/reminders/experts/_expert.haml
app/views/reminders/experts/_expert_reminders_notes.haml
app/views/reminders/experts/quo.haml
app/views/reminders/experts/reminders_notes.js.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20220321155358_add_enum_category_to_feedbacks.rb
db/schema.rb
spec/factories/feedbacks.rb
spec/models/need_spec.rb

Amélioration relance 3 : Remplace les notes par commentaires pour la relance expert

---

app/front/javascripts/application/controllers/feedback_form_controller.js
app/front/stylesheets/pages/need_show.sass
app/policies/feedback_policy.rb
app/views/feedbacks/_form.html.haml
app/views/needs/show.haml
config/i18n-tasks.yml
config/locales/data/prefill_feedbacks.fr.yml
config/locales/views.fr.yml
spec/views/reminders/needs/index.html.haml_spec.rb

Amélioration relance 1 : Commentaires besoin pré-remplis

---

app/models/antenne.rb
spec/models/antenne_spec.rb

Detecte automatiquement les antennes regionales

---

app/services/time_duration_service.rb

https://sentry.io/organizations/place-des-entreprises-org/issues/3130748533/?project=5747178&query=is%3Aunresolved

répare find_quarters

---

app/models/solicitation.rb
spec/models/solicitation_spec.rb

close #2364 
Et enlève automatiquement les double points dans les emails (debug du jeudi matin)

Assouplissement machine à état solicitation

---

app/front/stylesheets/components/buttons.sass

Je l'ai mis que sur le vert, je crois qu'on en a besoin qu'ici pour l'instant
closes #2380

améliore le style des boutons vert verouillés

---

app/front/stylesheets/application.sass
app/front/stylesheets/components/components.sass
app/front/stylesheets/pages/reminders.sass
app/models/expert.rb
app/views/application/_person.haml
app/views/reminders/experts/_expert.haml
config/locales/views.fr.yml

Visible dans les relances par experts
closes #2372

Affiche les utilisateurs des équipes dans les relances

---

app/models/clockwork.rb

créer les rapports trimestriels par batch de 20 antennes

---

app/helpers/solicitation_helper.rb

Une sollicitation avait un `pk_kword` mais pas de `pk_campaign`, ce qui empêchait l'affichage de la page admin

Bug pk campaign

---

app/models/solicitation.rb

Pb de retour si etablissement non trouvé

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
spec/features/reports/report_feature_spec.rb

C'est pas optimum, j'aurai aimé ajouter un filtre dans la colonne de droite mais c'est assez compliqué avec activeadmin parce que ça dépend non pas d'un champ de User mais d'une table séparée.
closes #2409

ajoute un filtre pour les responsables pas encore invités

---

app/models/feedback.rb
spec/models/feedback_spec.rb

Met à jour les notifications par email pour les commentaires

---

app/controllers/reminders/experts_controller.rb
app/views/kaminari/_paginator.html.haml
app/views/reminders/_need.haml
app/views/reminders/experts/show.html.haml
config/routes.rb

Ajoute un lien du panier besoins vers les experts du panier critique

---

app/controllers/annuaire/antennes_controller.rb
app/controllers/annuaire/users_controller.rb
app/models/concerns/person_concern.rb
app/views/landings/landing_subjects/show.html.haml
config/initializers/content_security_policy.rb
config/locales/models.fr.yml
spec/features/users/experts_controller_spec.rb
spec/features/users/registrations_controller_spec.rb

- Change Voxusagers.gouv en jedonnemonavis.gouv (https://sentry.io/organizations/place-des-entreprises-org/issues/3212958628/?project=5747178&query=is%3Aunresolved)
- Enlève les objets nil dans l'import. Je n'ai pas réussi à reproduire le bug (https://sentry.io/organizations/place-des-entreprises-org/issues/2920561205/?project=5747178&query=is%3Aunresolved)
- Sanitize les utilisateurs et expert à chaque changement (https://sentry.io/organizations/place-des-entreprises-org/issues/2903708632/?project=5747178&query=smtp&statsPeriod=14d)

Débug du jeudi

---

app/views/landings/landing_subjects/show.html.haml
app/views/landings/landings/_multiple_steps.html.haml

Ajoute l'evenement Matomo sur le lien autre demande

---

app/admin/solicitation.rb
app/controllers/conseiller/solicitations_controller.rb
app/models/solicitation.rb
app/views/landings/landing_subjects/_matomo_company_contact_begin.html.erb
app/views/landings/landing_subjects/_new_solicitation_form.html.haml
app/views/solicitations/_matomo_company_contact_begin.html.erb
app/views/solicitations/form_contact.html.haml
config/locales/models.fr.yml

close https://sentry.io/organizations/place-des-entreprises-org/issues/3215633779/?alert_rule_id=5921866&alert_timestamp=1650614919650&alert_type=email&environment=production&project=5747178&referrer=alert_email

Fix redirection espace conseiller

---

app/views/landings/landing_subjects/_matomo_company_contact_failure.html.erb
app/views/landings/landing_subjects/_matomo_company_contact_success.html.erb
app/views/solicitations/_matomo_company_contact_success.html.erb
app/views/solicitations/form_complete.html.haml
app/views/solicitations/form_contact.html.haml

Les chiffres enregistrés via Matomo manquent tout de même de cohérence. Changements mineurs pour voir si ça change quelque chose.

Tentative amelioration ab tracking

---

app/front/javascripts/application/controllers/diagnosis_needs_step_controller.js
app/views/diagnoses/steps/needs.html.haml

Décoche automatiquement Autre besoin

---

app/controllers/stats/base_controller.rb
app/front/stylesheets/pages.sass
app/front/stylesheets/pages/stats.sass
app/services/stats/base_stats.rb
app/services/stats/filters_stats.rb
app/services/stats/public/companies_by_employees_stats.rb
app/services/stats/public/companies_by_naf_code_stats.rb
app/services/stats/public/exchange_with_expert_stats.rb
app/services/stats/public/solicitations_diagnoses_stats.rb
app/services/stats/public/solicitations_in_deployed_regions_stats.rb
app/services/stats/public/solicitations_stats.rb
app/services/stats/public/taking_care_time_stats.rb
app/services/stats/public/themes_stats.rb
app/services/stats/quality/needs_abandoned_stats.rb
app/services/stats/quality/needs_done_no_help_stats.rb
app/services/stats/quality/needs_done_not_reachable_stats.rb
app/services/stats/quality/needs_done_stats.rb
app/services/stats/quality/needs_not_for_me_stats.rb
app/views/stats/_stats_params.haml
config/locales/views.fr.yml

Ajoute des filtres pour les stats

---

app/views/solicitations/form_contact.html.haml

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3130748533/?project=5747178&query=is%3Aunresolved

corrige lien des mention legales dans le formulaire multipages

---

app/assets/javascripts/active_admin.js
app/assets/javascripts/admin/custom.js

Affiche une popup si utilisateur admin

---

app/controllers/reminders/needs_controller.rb

Relances par besoins : Trie par date de création

---

app/models/user.rb
spec/models/expert_spec.rb

Ne créer pas un nouvel expert quand on modifie l'email d'un utilisateur

---

.env.example
app/mailers/application_mailer.rb
app/mailers/custom_devise_mailer.rb

Test de modification pour améliorer la délivrabilité des emails
Possibilité de distinguer adresse d'envoi et reply_to

Add reply_to

---

app/services/create_diagnosis/find_relevant_expert_subjects.rb

close https://sentry.io/organizations/place-des-entreprises-org/issues/3248306044/events/48854d9f306a4074bb1acd80e029a8af/?project=5747178
close https://sentry.io/organizations/place-des-entreprises-org/issues/3229338461/events/fd4e61c62f674943b6924b1c4831652a/?project=5747178

Fix filter when no legal_form_code

---

app/helpers/breadcrumbs_helper.rb

https://sentry.io/organizations/place-des-entreprises-org/issues/3130748533/events/e63659493eee4aa0ba77f1a9c39ebae7/?project=5747178

Ajout des paramètres permis pour le lien des mentions d'information

---

app/helpers/companies_helper.rb
app/views/diagnoses/_company_details.haml
config/locales/models.fr.yml

Ajout info rcs page MER

---

app/front/stylesheets/utilities.sass
app/views/needs/_additional_experts.haml
config/locales/views.fr.yml

Ajout info ambulance

---

app/admin/match.rb
app/admin/solicitation.rb
app/models/match.rb
app/models/solicitation.rb
config/locales/models.fr.yml

Ajout du filtre Campagne en admin

---

app/policies/need_policy.rb
app/views/needs/show.html.haml
spec/policies/need_policy_spec.rb

Permet aux conseillers de voir les pages besoins de l'antenne

---

app/models/antenne.rb
app/models/commune.rb
app/models/need.rb
app/services/quarterly_report_service.rb
app/services/xlsx_export/antenne_stats_exporter.rb
app/services/xlsx_export/antenne_stats_worksheet_generator/base.rb
app/services/xlsx_export/antenne_stats_worksheet_generator/by_antenne.rb
app/services/xlsx_export/antenne_stats_worksheet_generator/by_region.rb
app/services/xlsx_export/antenne_stats_worksheet_generator/caption.rb
app/services/xlsx_export/match_exporter.rb
config/locales/data/codes_regions.fr.yml
config/locales/models.fr.yml

Amélioration des rapports antenne

---

Gemfile
app/front/stylesheets/tarteaucitron-dsfr.scss
app/views/about/mentions_d_information.fr.html.erb
app/views/layouts/side_menu.html.haml
app/views/pages/_navbar.haml

Ajoute OVH aux Mention informations, plus quelques trucs d'accessibilité

---

app/front/javascripts/application/controllers/diagnosis_needs_step_controller.js
app/views/diagnoses/steps/needs.html.haml
spec/factories/diagnoses.rb
spec/system/diagnosis_system_spec.rb
spec/views/needs/show.html.haml_spec.rb

auto-uncheck for all needs

---

app/views/devise/sessions/new.html.haml
config/locales/devise.fr.yml

Precise "Email perso" sur la page de connexion

---

.circleci/config.yml

Fichier de config édité automatiquement par circle ci pour accélérer un peu les tests (on passe sous les 7 minutes)

Update test to large resource class in config.yml

---

app/models/concerns/person_concern.rb
spec/models/concerns/person_concern_spec.rb

Amélioration de la normalisation des noms

---

app/admin/solicitation.rb
app/controllers/diagnoses_controller.rb
app/front/javascripts/application/insee_code_field.js
app/models/concerns/diagnosis_creation.rb
app/views/application/_insee_code_field.html.haml
app/views/diagnoses/new.haml
config/locales/views.fr.yml
spec/controllers/diagnoses_controller_spec.rb
spec/models/concerns/diagnosis_creation_spec.rb

Fix et facilite analyse pour demande sans siret

---

app/views/about/accessibilite.html.erb

Ajoute que la démarche est en cours

Met à jour la page accessibilité

---

app/controllers/concerns/inbox.rb
app/controllers/manager/needs_controller.rb
app/models/antenne.rb
app/models/concerns/territory_needs_status.rb
app/models/need.rb
app/policies/antenne_policy.rb
app/policies/application_policy.rb
app/policies/user_policy.rb
app/views/application/_navbar.html.haml
app/views/manager/needs/_header.html.haml
app/views/manager/needs/_menu.html.haml
app/views/manager/needs/_search.haml
app/views/manager/needs/index.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/models/concerns/involvement_concern_spec.rb
spec/models/concerns/territory_needs_status_spec.rb
spec/policies/user_policy_spec.rb

créer une page pour voir les besoins des antennes d'un responsable

---

app/admin/match.rb
app/views/mailers/admin_mailer/solicitation.haml
app/views/mailers/expert_mailer/_remind_received_needs.html.haml

close #2505 
close #2508 
(j'ai tout fait dans une PR pour que ce soit + rapide à merger)

Répare les liens entreprise dans les emails + lien dans l'admin des MER si plusieurs besoins

---

app/front/javascripts/application/insee_code_field.js

Fix bug js city autocomplete dataset

---

lib/tasks/transform_data_for_demo.rake

Script de génération du besoin démo

---

app/models/concerns/involvement_concern.rb
app/views/devise/mailer/invitation_instructions.text.erb
app/views/devise/mailer/reset_password_instructions.text.erb
app/views/mailers/_footer.text.erb
app/views/mailers/expert_mailer/_never_used_account_warning.text.erb
app/views/mailers/expert_mailer/_remind_received_needs.text.erb
app/views/mailers/expert_mailer/_support_contacts.text.erb
app/views/mailers/expert_mailer/notify_company_needs.text.erb
app/views/mailers/expert_mailer/remind_involvement.text.erb
app/views/mailers/user_mailer/match_feedback.text.erb
config/locales/devise.fr.yml
config/locales/views.fr.yml

Propose alternatives text pour emails importants

---

config/locales/data/prefill_feedbacks.fr.yml

Mise à jour des commentaires pré-remplis

---

app/views/about/accessibilite.html.erb

Mise à jour page accessibilité

---

app/controllers/feedbacks_controller.rb
app/controllers/shared_controller.rb
app/policies/feedback_policy.rb
app/views/shared/errors/404.js.haml
app/views/shared/errors/500.js.haml

Bloque les commentaires si connecté en tant que

---

app/views/about/comment_ca_marche.html.haml
app/views/pages/_alert_region.haml
app/views/pages/_navbar.haml
config/locales/views.fr.yml
doc/05-deployer-une-region.md

Retire le bandeau d'alerte région

---

app/admin/user.rb
app/mailers/expert_mailer.rb
app/models/user.rb
app/views/devise/mailer/reset_password_instructions.html.haml
app/views/devise/mailer/reset_password_instructions.text.erb
app/views/mailers/expert_mailer/_invitation_not_accepted_warning.html.haml
app/views/mailers/expert_mailer/_invitation_not_accepted_warning.text.erb
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/expert_mailer/notify_company_needs.text.erb
app/views/mailers/expert_mailer/remind_involvement.html.haml
app/views/mailers/expert_mailer/remind_involvement.text.erb
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/models/user_spec.rb

corrige les scopes des users, change 'never_used' en 'not_invited'

---

app/controllers/concerns/inbox.rb
app/controllers/manager/needs_controller.rb
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb

ordonne les besoins par date croissante dans la boite de réception 

---

app/mailers/custom_devise_mailer.rb
app/models/antenne.rb

Adresse contact comme expediteur des invitations

---

app/assets/javascripts/admin/custom.js

Ajout confirmation pour rendre un expert global

---

app/controllers/concerns/iframe_prefix.rb
app/controllers/landings/base_controller.rb
app/controllers/landings/landing_themes_controller.rb
app/controllers/landings/landings_controller.rb
app/controllers/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/services/solicitation_modification/format_params.rb
app/views/landings/landing_subjects/_card.html.haml
app/views/landings/landing_themes/_card.html.haml
app/views/solicitations/step_contact.html.haml
app/views/solicitations/step_description.html.haml
spec/features/new_solicitation_feature_spec.rb

permet de préchocher les questions pour les iframes

---

app/controllers/annuaire/search_controller.rb
app/helpers/institutions_helper.rb
app/views/annuaire/institutions/_table.html.haml
app/views/annuaire/search/_form.html.haml
app/views/annuaire/users/_import_buttons.html.haml

annuaire : telecharge les conseillers de la region si sélectionnée + améliorations

---

app/controllers/diagnoses/steps_controller.rb
app/front/stylesheets/application/steps.sass
app/models/concerns/diagnosis_creation.rb
app/models/need.rb
app/services/create_diagnosis/find_relevant_expert_subjects.rb
app/views/diagnoses/steps/matches.html.haml
app/views/diagnoses/steps/needs.html.haml
spec/services/create_diagnosis/find_relevant_expert_subjects_spec.rb

Fix - lie les filtres aux besoins

---

app/views/user_pages/tutoriels.haml
config/locales/views.fr.yml
spec/system/pages_system_spec.rb

Met à jour la video de tuto

---

app/admin/antenne.rb
app/models/antenne.rb
config/locales/models.fr.yml

Corrige le compte des MER d'une antenne

---

app/admin/company_satisfaction.rb
app/models/company_satisfaction.rb

add filter for regions

---

app/front/stylesheets/components/components.sass
app/views/companies/_facility_infos.html.haml
config/locales/fr.yml
config/locales/views.fr.yml

affiche RM et RCS en permanence 

---

app/front/packs/application.js
app/front/stylesheets/utilities.sass
app/views/reminders/_need.haml
app/views/reminders/experts/_expert.haml
app/views/reminders/needs/send_abandoned_email.js.haml

affiche en permanence les boutons d'envoi d'emails d'abandon et relance

---

config/locales/models.fr.yml
config/locales/views.fr.yml

met à jour les liens vers annuaire-entreprises.data.gouv.fr

---

app/admin/diagnosis.rb
app/admin/need.rb
app/controllers/needs_controller.rb
config/locales/views.fr.yml

https://sentry.io/organizations/place-des-entreprises-org/issues/3452888884/?project=5747178&query=is%3Aunresolved

affiche une erreur en cas d'affichage d'une page besoin avec analyse non terminé

---

app/services/unused_users_service.rb

https://sentry.io/organizations/place-des-entreprises-org/issues/3414490881/?project=5747178&query=is%3Aunresolved

verifie si un expert inutilisé a des MER avant de le supprimer

---

app/services/stats/matches/positioning_rate.rb

https://sentry.io/organizations/place-des-entreprises-org/issues/3416554867/?project=5747178&query=is%3Aunresolved

Corrige le filtre par institution et territoire sur /stats/equipe/mises-en-relation

---

app/views/companies/_facility_infos.html.haml
config/locales/views.fr.yml

Corrige l'affichage RM/RCS sur la page "plus d'informations"

---

app/views/solicitations/step_company.html.haml

Augmente la taille maximum du siret pour pouvoir avoir des espaces

---

app/views/conseiller/solicitations/remove.js.haml

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3441043533/events/22c5818a9ad645bea56f55bd3a77dfd8/?project=5747178

corrige l'affichage des messages d'information sur la pages des sollicitations

---

app/views/conseiller/solicitations/update_badges.js.haml
app/views/shared/_matomo.html.erb
app/views/shared/errors/404.js.haml
app/views/shared/errors/500.js.haml

- enlève un innerHTML et test si l'element existe avant
- met à jour le innerHTML des pages d'erreur
- change un parametre de Matomo qui était obsolète

correction de bug du jeudi

---

app/admin/company_satisfaction.rb
app/admin/match.rb
app/admin/solicitation.rb
app/controllers/partner_tools_controller.rb
app/controllers/stats/base_controller.rb
app/helpers/breadcrumbs_helper.rb
app/helpers/solicitation_helper.rb
app/models/match.rb
app/models/solicitation.rb
app/services/stats/base_stats.rb
app/services/stats/filters_stats.rb
app/views/conseiller/solicitations/_tracking.haml
app/views/mailers/company_mailer/confirmation_solicitation.html.haml
app/views/mailers/company_mailer/notify_not_reachable.html.haml
app/views/mailers/company_mailer/notify_taking_care.html.haml
app/views/mailers/company_mailer/retention.html.haml
app/views/mailers/company_mailer/satisfaction.html.haml
app/views/partner_tools/inserts.html.haml
app/views/stats/team/_stats_params.haml
config/locales/models.fr.yml
spec/features/new_solicitation_no_js_feature_spec.rb
spec/requests/landings_spec.rb

J'en ai profité pour mettre à jour les noms de nos paramètres de pk en mtm
closes #2605

permet d'accepter mtm_campaign and mtm_kwd

---

app/admin/duplicate_user.rb
app/admin/user.rb
app/assets/stylesheets/active_admin.sass
app/models/user.rb
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/models/user_spec.rb

Duplique un utilisateur

---

app/controllers/solicitations_controller.rb
app/services/search_facility.rb
app/views/solicitations/search_facility.html.haml
config/locales/views.fr.yml

close #2630, https://sentry.io/organizations/place-des-entreprises-org/issues/3521282941/?project=5747178&query=is%3Aunresolved

Debug jeudi

---

app/mailers/expert_mailer.rb
app/models/expert.rb
app/models/match.rb
app/views/mailers/expert_mailer/remind_involvement.html.haml
app/views/mailers/expert_mailer/remind_involvement.text.erb
config/locales/views.fr.yml
spec/mailers/previews/expert_mailer_preview.rb
spec/models/match_spec.rb

enlève les besoins deja pris en charges dans l'email hebdomadaire

---

app/front/stylesheets/components/navigation.sass
app/views/pages/_navbar.haml
package.json
yarn.lock

closes #2632 
J'ai essayé avec le code du DSFR sans rien changer et le logo ne s'affiche pas non plus
https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222789846/En-t+te+-+Header

Affiche le logo sur Firefox

---

app/admin/reassign_matches.rb
app/admin/user.rb
app/assets/stylesheets/active_admin.sass
app/models/user.rb
app/views/admin/reassign_matches/_reassign_matches.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/models/user_spec.rb

Réatribuer les mer à un autre utilisateur

---

app/mailers/expert_mailer.rb
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/expert_mailer/notify_company_needs.text.erb
app/views/mailers/expert_mailer/remind_involvement.html.haml
app/views/mailers/expert_mailer/remind_involvement.text.erb
spec/mailers/expert_mailer_spec.rb

Suppression invit automatique qd nouveau besoin

---

app/services/api_consumption/models/facility/api_insee.rb
spec/services/api_consumption/models/facility/api_insee_spec.rb

Correction identification région domtom

---

app/services/api_insee/base.rb
app/services/search_facility.rb
config/locales/fr.yml

Parer à l'inconsistance actuelle de l'API de l'INSEE

Api fallback

---

app/front/javascripts/application/controllers/bandeau_info_controller.js
app/views/application/_bandeau_info.html.haml
app/views/layouts/application.html.haml
config/locales/views.fr.yml

Affichage bandeau info

---

app/services/csv_export/match_exporter.rb
app/services/csv_export/solicitation_exporter.rb
app/services/effectif/code_effectif.rb
config/environments/test.rb
spec/factories/territories.rb
spec/services/csv_export/match_exporter_spec.rb

Deux éléments avaient échappé au commit de remaniement des effectifs.
A revoir rapidement (svp @LucienMLD ) car ça empêche notamment les exports csv. Si pas possible de le revoir de suite, dis-moi pour que je mette au moins en prod manuellement pour débloquer la situation.

Fix effectifs

---

app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/landings/landing_subjects_controller.rb
app/controllers/api/v1/landings/landing_themes_controller.rb
app/controllers/api/v1/landings/landings_controller.rb
app/models/institution.rb
app/models/landing_subject.rb
app/models/landing_theme.rb
app/serializers/api/v1/additional_subject_question_serializer.rb
app/serializers/api/v1/landing_serializer.rb
app/serializers/api/v1/landing_subject_serializer.rb
app/serializers/api/v1/landing_theme_serializer.rb
config/locales/fr.yml
config/routes.rb
spec/requests/api/v1/landing_subjects_spec.rb
spec/requests/api/v1/landing_themes_spec.rb
spec/requests/api/v1/landings_spec.rb
spec/support/api_spec_helper.rb
spec/swagger_helper.rb
swagger/v1/swagger.yaml

Api depot 2

---

config/locales/data/codes_departements.fr.yml
config/locales/data/codes_regions.fr.yml

Ajoute les communautés d'outre mer pour la traduction

---

app/assets/stylesheets/mailers.sass
app/controllers/solicitations_controller.rb
app/mailers/company_mailer.rb
app/models/clockwork.rb
app/services/solicitations_relaunch_service.rb
app/views/mailers/company_mailer/solicitation_relaunch.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/mailers/previews/company_mailer_preview.rb
spec/services/solicitations_relaunch_service_spec.rb

ajoute un email de relance pour les sollicitations non terminées

---

app/views/reminders/experts/show.html.haml

https://sentry.io/organizations/place-des-entreprises-org/issues/3631709330/?project=5747178&query=is%3Aunresolved

add missing variable

---

config/locales/models.fr.yml

change le label d'une question additionnelle sur l'investissement

---

app/services/admin_mailers_service.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3640287214/?project=5747178&query=undefined+method+%60%2B%27+for&statsPeriod=14d

corrige le lien vers les relance dans l'email des stats

---

app/front/javascripts/application/insee_code_field.js

API adresse : "q must contain at least 3 chars and start with a number or a letter"

Fix insee_code_field

---

Gemfile.lock
app/controllers/api/v1/solicitations_controller.rb
app/models/institution.rb
app/models/solicitation.rb
app/serializers/api/v1/landing_subject_serializer.rb
app/serializers/api/v1/solicitation_logo_serializer.rb
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/factories/institutions.rb
spec/requests/api/v1/landing_subjects_spec.rb
spec/requests/api/v1/landing_themes_spec.rb
spec/requests/api/v1/landings_spec.rb
spec/requests/api/v1/solicitations_spec.rb
spec/swagger_helper.rb
swagger/v1/swagger.yaml

Améliorations diverses de l'API

---

app/admin/solicitation.rb
app/models/solicitation.rb
app/services/csv_export/solicitation_exporter.rb
config/locales/models.fr.yml

close #2705
Filtre pour permettre de n'exporter que les sollicitations complètes ou incomplètes

Ajout filtre completion pour solicitation en admin

---

app/controllers/concerns/iframe_prefix.rb
app/controllers/landings/base_controller.rb
app/controllers/landings/landing_themes_controller.rb
app/controllers/landings/landings_controller.rb
app/controllers/solicitations_controller.rb

Empêche le double tracking à cause du cache 

---

config/initializers/rack_attack.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3691295891/?project=5747178&query=is%3Aunresolved&referrer=issue-stream

ban foobar ip

---

app/models/badge.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3702829636/?project=5747178&query=is%3Aunresolved&referrer=issue-stream

corrige la suppression des tags

---

app/services/stats/filters_stats.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3727593297/?project=5747178&query=is%3Aunresolved&referrer=issue-stream

fix wrong method name

---

app/controllers/application_controller.rb
app/controllers/concerns/inbox.rb
app/controllers/manager/needs_controller.rb
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb
app/controllers/reminders_actions_controller.rb
app/models/concerns/involvement_concern.rb
app/models/match.rb
app/models/need.rb
app/views/matches/_match.haml
app/views/reminders/_header.html.haml
app/views/reminders/experts/_expert.haml
config/locales/views.fr.yml
config/routes.rb
spec/features/application_controller_feature_spec.rb
spec/models/concerns/involvement_concern_spec.rb
spec/system/needs_system_spec.rb

Mise en coherence inbox

---

app/views/mailers/company_mailer/solicitation_relaunch_company.html.haml
app/views/mailers/company_mailer/solicitation_relaunch_description.html.haml
config/locales/views.fr.yml

Distinction relance étape entreprise/description

---

app/controllers/solicitations_controller.rb
app/front/stylesheets/pages/multistep-form.sass
app/models/solicitation.rb
app/views/about/_transcription_pde_testimonial.haml
app/views/about/comment_ca_marche.html.haml
app/views/badges/index.html.haml
app/views/conseiller/solicitations/_solicitation_actions.html.haml
app/views/sitemap/sitemap.html.haml
app/views/solicitations/_company_tile.html.haml
app/views/solicitations/_header.html.haml
app/views/solicitations/_next_button.html.haml
app/views/solicitations/_previous_button.html.haml
app/views/solicitations/_steps.html.haml
app/views/solicitations/form_complete.html.haml
app/views/solicitations/search_company.html.haml
app/views/solicitations/search_facility.html.haml
app/views/solicitations/step_company.html.haml
app/views/solicitations/step_company_search.html.haml
app/views/solicitations/step_contact.html.haml
app/views/solicitations/step_description.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml

Accessibilite solicitation form

---

app/front/javascripts/pages/percentage_column_chart.js
app/front/javascripts/pages/stats_charts.js
app/views/annuaire/base/_import_errors.html.haml
app/views/shared/_flashes.html.haml
app/views/shared/_skiplinks.html.haml
app/views/solicitations/form_complete.html.haml
app/views/solicitations/step_company_search.html.haml
config/locales/views.fr.yml
spec/a11y/application/devise_spec.rb
spec/a11y/application/needs_spec.rb
spec/a11y/application/pages_spec.rb
spec/a11y/pages/about_spec.rb
spec/a11y/pages/landings_spec.rb
spec/a11y/pages/solicitation_form_spec.rb
spec/a11y/pages/stats_spec.rb
spec/support/axe/matchers/be_accessible.rb

/!\ Dépendant de #2711 
close #2736

Finalisation accessibilite - retours Maroua

---

app/models/need.rb
spec/models/need_spec.rb

affiche que les besoins non pris en charge dans les relances

---

app/admin/solicitation.rb
app/models/solicitation.rb

Ajoute le filtre manquant pour les mots clés des sollicitation

---

app/models/feedback.rb
spec/models/feedback_spec.rb

Restreint l'envoie d'emails de notification de commentaires

---

app/front/stylesheets/components/tiles.sass

rend les colonnes des iframes responsives

---

app/controllers/solicitations_controller.rb
app/models/solicitation.rb
spec/controllers/solicitations_controller_spec.rb

Fix de la redirection relance solicitation

---

app/admin/user.rb
app/services/api_consumption/models/facility/api_entreprise.rb
app/views/companies/_facility.html.haml
config/locales/views.fr.yml

Micro ajouts IDCC fiche entreprise + filtre date création utilisateurs

---

app/services/csv_export/match_exporter.rb
app/services/csv_export/solicitation_exporter.rb
config/locales/models.fr.yml
spec/services/csv_export/match_exporter_spec.rb

Ajoute la catégorie juridique aux exports

---

app/models/feedback.rb
spec/factories/experts.rb
spec/models/feedback_spec.rb

fix un probleme de notifications lors d'un commentaire

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/mailers/solicitation_mailer/employee_labor_law.html.haml
config/locales/views.fr.yml
spec/features/solicitations/send_generic_emails_spec.rb
spec/mailers/previews/solicitation_mailer_preview.rb

ajoute l'email de sollicitations pour les employés

---

app/admin/commune.rb
app/models/commune.rb

Pour debug commune sans région

Amélioration affichage admin des communes

---

config/locales/views.fr.yml

Correction suite à la proposition de mon IDE

correction de typos dans les textes

---

app/admin/expert.rb

Demande amélioration des bizdev

Enleve les antennes supprimées des filtres expert

---

app/front/stylesheets/application/steps.sass
app/services/stats/public/companies_by_employees_stats.rb
app/services/stats/public/companies_by_naf_code_stats.rb
app/views/diagnoses/steps/needs.html.haml
config/initializers/rack_attack.rb

- Corrige le filtre des stats quand on choisit une région et une antenne
- Corrige le style sur la page de sélection du besoin quand on fait une MER
- Ajoute une IP pour Rackattack
closes #2793

corrections du jeudi

---

app/front/stylesheets/components/navigation.sass
app/helpers/application_helper.rb
app/views/about/accessibilite.html.erb
app/views/about/cgu.fr.html.erb
app/views/about/mentions_d_information.fr.html.erb
app/views/devise/sessions/new.html.haml
app/views/pages/_footer.haml
app/views/solicitations/step_company.html.haml
app/views/solicitations/step_company_search.html.haml
app/views/solicitations/step_contact.html.haml
app/views/solicitations/step_description.html.haml
app/views/user_pages/tutoriels.haml
config/locales/views.fr.yml

Retouche accessibilite

---

app/views/about/accessibilite.html.erb
config/locales/views.fr.yml
spec/system/pages_system_spec.rb

MaJ de la page accessibilité

---

app/helpers/status_helper.rb
app/views/application/_person_modal.html.haml
app/views/diagnoses/steps/matches.html.haml
app/views/needs/_additional_experts.haml
app/views/needs/_empty_placeholder.html.haml
app/views/needs/_match_actions.html.haml
app/views/needs/show.html.haml
app/views/reports/index.html.haml
app/views/shared/_flashes.html.haml
app/views/solicitations/step_company_search.html.haml

Amélioration rapide accessibilité

---

app/controllers/solicitations_controller.rb
app/front/stylesheets/pages/multistep-form.sass
app/models/solicitation.rb
app/views/solicitations/step_company_search.html.haml
app/views/solicitations/step_description.html.haml
app/views/solicitations/step_verification.html.haml
config/locales/fr.yml
config/locales/views.fr.yml
config/routes.rb
spec/a11y/pages/solicitation_form_spec.rb
spec/features/new_solicitation_js_feature_spec.rb

Etape de vérification

---

app/models/concerns/person_concern.rb
app/models/expert.rb
app/models/user.rb
spec/models/expert_spec.rb

MaJ user quand on update personal_skillset

---

app/admin/landing_theme.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3878065350/?project=5747178&query=is%3Aunresolved&referrer=issue-stream

prevent undefined method `html_safe' for nil:NilClass

---

app/admin/landing_theme.rb

closes https://sentry.io/organizations/place-des-entreprises-org/issues/3878162309/?project=5747178&query=is%3Aunresolved&referrer=issue-stream

undefined method `logos' for LandingSubject

---

app/admin/antenne.rb
app/models/match_filter.rb
app/models/subject.rb
app/services/create_diagnosis/find_relevant_expert_subjects.rb
db/migrate/20230113133832_change_match_filters_subject.rb
db/schema.rb
spec/services/create_diagnosis/find_relevant_expert_subjects_spec.rb

Fix match_filter problem

---

app/admin/antenne.rb
app/views/solicitations/step_description.html.haml
config/locales/views.fr.yml

minor changes description

---

app/front/stylesheets/components/cards.sass
app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

Affiche alerte si pas dans registre

---

app/controllers/stats/base_controller.rb
app/controllers/stats/team_controller.rb
app/helpers/stats_helper.rb
app/services/stats/base_stats.rb
app/services/stats/filters_stats.rb
app/views/stats/public/_stats_params.haml
app/views/stats/team/_stats_params.haml
app/views/stats/team/_tabs.html.haml
app/views/stats/team/index.html.haml
config/locales/views.fr.yml
spec/views/stats/team/index.html.haml_spec.rb

Ajoute le theme dans les filtres des stats et garde les filtres entre les onglets

---

app/models/match.rb
spec/models/match_spec.rb

Auto cloture des MER pole emploi

---

app/front/stylesheets/pages/multistep-form.sass
app/views/solicitations/_institutions_tiles_block.html.haml
app/views/solicitations/form_complete.html.haml
app/views/solicitations/matomo_events/_matomo_partner_contact.html.erb
config/locales/views.fr.yml

Description detaillee des partenaires page merci

---

app/controllers/solicitations_controller.rb

Fix redirect error

---

app/models/match.rb
spec/models/match_spec.rb

Fix pole emploi autoclosure

---

app/views/needs/show.html.haml
config/locales/models.fr.yml

Changement question recrutement cadre + affichage questions sur fiches besoin

---

app/views/application/_navbar.html.haml

closes #2856 
discussion sur le sujet https://github.com/hotwired/turbo/issues/288
le problème était soi-disant résolu mais ça ne fonctionne pas https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.6
J'ai testé plein de solutions pour garder un lien mais je n'ai pas trouvé

redirige vers l'accueil après deconnexion

---

app/controllers/concerns/inbox.rb

change la clé de cache pour le compte des boites de reception PC

---

app/views/feedbacks/create.js.haml
app/views/needs/_match_actions.html.haml
config/locales/views.fr.yml

Quand un conseiller refuse et laisse un commentaire, on raccourcit le texte qui demande de déposer un commentaire
closes #2904

Affiche un message plus court quand un conseiller refuser et laisse un commentaire

---

config/rorvswild.yml

Fix ror vs wild

---

app/views/mailers/solicitation_mailer/no_expert.html.haml
config/locales/views.fr.yml

MaJ mail pas d'expert avec professions liberales

---

app/controllers/annuaire/users_controller.rb
app/helpers/institutions_helper.rb
app/services/csv_export/user_exporter.rb
app/services/csv_import/user_importer.rb
app/services/xlsx_export/user_exporter.rb
app/views/annuaire/institutions/_table.html.haml
config/locales/models.fr.yml
spec/services/csv_export/user_exporter_spec.rb

Amélioration export annuaire

---

app/admin/email_retentions.rb
app/assets/stylesheets/mailers.sass
app/mailers/company_mailer.rb
app/models/clockwork.rb
app/models/email_retention.rb
app/models/match.rb
app/models/need.rb
app/services/retention_service.rb
app/views/mailers/_header.html.haml
app/views/mailers/company_mailer/intelligent_retention.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20230320150526_create_email_retention.rb
db/schema.rb
spec/factories/email_retention.rb
spec/mailers/company_mailer_spec.rb
spec/mailers/previews/company_mailer_preview.rb
spec/models/need_spec.rb
spec/services/retention_service_spec.rb

Ajout de mail rétention automatique à notre séquence

---

app/views/user_pages/tutoriels.haml
config/locales/views.fr.yml

Ajout tutoriel notification

---

app/admin/user.rb
app/models/user.rb
app/views/application/_person.haml
app/views/reminders/experts/_expert.haml
app/views/stats/team/_stats_params.haml
config/locales/models.fr.yml

close #2975 (je me le tente sans supprimer le cache)
close #2945

Debug 20230413

---

app/views/feedbacks/create.js.haml

Modifie le sens d'ajout des commentaires

---

app/models/solicitation.rb
spec/models/solicitation_spec.rb

Chercher une sollicitation par siret / siren

---

app/controllers/conseiller/solicitations_controller.rb

évite les doublons d'historique sur les fiches de sollicitations

---

Procfile
app/models/api_key.rb
lib/tasks/staging_transform_data.rake
lib/tasks/transform_data_for_demo.rake

Automatisation de script post-déploiement sur staging : 
- formatage des données pour les démo
- simplification des clés d'API pour les tests partenaires

Update staging post deploy hooks

---

app/controllers/concerns/inbox.rb
app/controllers/needs_controller.rb
app/front/stylesheets/components/components.sass
app/helpers/page_infos_helper.rb
app/helpers/solicitation_helper.rb
app/models/expert.rb
app/models/need.rb
app/models/theme.rb
app/models/user.rb
app/views/needs/_search.haml
app/views/needs/index.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/models/need_spec.rb

Ajout de filtres dans la boite de réception des conseillers

---

app/front/stylesheets/application/need_show.sass
app/models/landing.rb
app/views/needs/show.html.haml
config/locales/views.fr.yml

Ajout lien Entreprendre sur fiche besoin

---

app/admin/company_satisfaction.rb
app/admin/match.rb
app/models/company_satisfaction.rb
config/locales/models.fr.yml

Améliorations filtres admin (MER et Satisfaction)

---

app/controllers/concerns/inbox.rb
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb
app/models/need.rb
app/views/reminders/experts/quo.haml
spec/features/reminders/experts_feature_spec.rb
spec/features/reminders/needs_feature_spec.rb

Fix and tests reminders bugs

---

.circleci/config.yml
Gemfile
Gemfile.lock
Procfile
app/models/territory.rb
config/database.example.yml
db/migrate/20230502123048_enable_postgis.rb
db/migrate/20230502123049_fix_geocodes.rb
db/schema.rb
spec/factories/territories.rb
spec/models/antenne_spec.rb
spec/models/concerns/territory_needs_status_spec.rb
spec/models/solicitation_spec.rb

Enable postgis and make a small fix to the schema
refs #625

Add geography to the db (1/n)

---

app/controllers/reminders/experts_controller.rb
app/views/layouts/application.html.haml

Flash if send_re_engagement_email pb

---

app/models/antenne.rb
app/models/institution.rb
app/services/stats/filters_stats.rb

Compte les experts supprimés pour les stats

---

app/controllers/shared_controller.rb
app/models/user.rb
app/services/api_rne/base.rb
app/services/api_rne/token/base.rb
app/views/shared/errors/404.html.haml
config/locales/fr.yml

- fix (?) pb API RNE avec jeton (peut-être cache trop long ?) (close #3055)
- empêche de passer par Mot de passe oublié sans invitation (cf #3054)
- fix trad erreur 500

Debug 20130612

---

app/controllers/api/v1/solicitations_controller.rb
app/models/solicitation.rb
config/locales/models.fr.yml
spec/models/solicitation_spec.rb
spec/requests/api/v1/solicitations_spec.rb

A ne merger qu'une fois que le partenaire aura réparé l'envoi de données. 
close #3017

Ajout de validations sur les questions additionnelles des solicitations

---

app/models/facility.rb
spec/models/use_cases/search_facility_spec.rb

Problème de formatage des codes naf avec passage à une nouvelle API : 9001Z -> 90.01Z
close #3086

Fix naf code

---

db/migrate/20230705150741_add_sent_at_to_matches.rb
lib/tasks/init_match_sent_at.rake

fix #3083 
Qui se basait dans ces scripts de mise à jour sur le scope `sent`, modifié entre temps

Fix sent scope use

---

app/views/about/mentions_d_information.fr.html.erb
config/environments/production.rb
doc/04-architecture.md

MaJ smtp-relay sendinblue -> brevo

---

app/controllers/annuaire/institutions_controller.rb
app/helpers/annuaire_helper.rb
app/helpers/institutions_helper.rb
app/views/annuaire/institutions/_table.html.haml
app/views/annuaire/institutions/index.html.haml
spec/controllers/annuaire/institutions_controller_spec.rb
spec/factories/institutions.rb
spec/system/annuaire_system_spec.rb

Perfs sur ma machine :
- sans filtre : moins d'une demi seconde (au lieu de 1-1,5)
- avec filtre sur la région : entre 2 et 2,5 secondes (au lieu de 6-6,5)
Est-ce suffisant ?

fetch antennes count and users count with one sql query

---

app/controllers/concerns/inbox.rb
app/controllers/manager/needs_controller.rb
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb
app/helpers/search_helper.rb
app/helpers/solicitation_helper.rb
app/models/antenne.rb
app/models/theme.rb
app/views/manager/needs/_search.haml
app/views/manager/needs/index.html.haml
app/views/needs/_search.haml
app/views/needs/index.html.haml
app/views/reminders/experts/quo.haml
config/locales/views.fr.yml

Ajoute les filtres pour les responsables d'antennes

---

app/admin/expert.rb
app/models/expert.rb
config/locales/models.fr.yml

Add clean scopes for experts

---

app/controllers/stats/team_controller.rb
app/front/javascripts/pages/controllers/stats_controller.js
app/services/stats/base_stats.rb
app/services/stats/filters_stats.rb
app/views/stats/team/_stats_params.haml
app/views/stats/team/index.html.haml
config/locales/models.fr.yml
spec/views/stats/team/index.html.haml_spec.rb

Add stats iframe select

---

app/views/solicitations/step_contact.html.haml

Ajustements page atterrissage

---

app/models/referencement_coverage.rb
app/services/update_antenne_coverage.rb
config/locales/models.fr.yml
spec/services/update_antenne_coverage_spec.rb

annuaire : ajout d'un anomalie quand il n'y a pas d'utilisateur

---

app/views/about/comment_ca_marche.html.haml
config/locales/views.fr.yml

supprime la phrase pour rejoindre le partenariat

---

spec/models/antenne_spec.rb

c'est des tests que je voulais faire passer dans la PR du jeudi mais j'ai oublié de commit

add tests for territorial antennes

---

app/services/stats/base_stats.rb

corrige les stats quand on ne sélectionne pas le 1er du mois

---

app/views/about/mentions_d_information.fr.html.erb

Mention de traitements nouveaux

Mise à jour des traitements dans les mentions légales

---

.circleci/config.yml
.env.example
app/mailers/application_mailer.rb
app/mailers/custom_devise_mailer.rb
app/views/mailers/company_mailer/solicitation_relaunch_description.html.haml
config/initializers/devise.rb
spec/mailers/previews/devise_mailer_preview.rb

@LucienMLD en bossant sur les mails, me suis rendue compte qu'il y avait des incohérences (contact@**at.**place-des-entreprises.beta.gouv.fr dans le footer des emails, par exemple).
Cette PR pour faire un bon coup de ménage. Il faudra vérifier les variables des app prod et staging au moment du déploiement.

Fix Application emails

---

app/controllers/annuaire/users_controller.rb
app/controllers/companies_controller.rb
app/front/stylesheets/components/components.sass
app/policies/need_done_policy.rb
app/policies/need_in_progress_policy.rb
app/views/conseiller/solicitations/_solicitation_actions.html.haml

Debug 20230914

---

config/locales/data/prefill_feedbacks.fr.yml
config/locales/views.fr.yml

Met à jour le text des commentaires pré écrits

---

app/services/stats/matches/done_no_help_rate_stats.rb
app/services/stats/matches/done_not_reachable_rate_stats.rb
app/services/stats/matches/done_rate_stats.rb
app/services/stats/matches/not_for_me_rate_stats.rb
app/services/stats/matches/not_positioning_rate.rb
app/services/stats/matches/positioning_rate.rb
app/services/stats/matches/taking_care_rate_stats.rb

Ca n'enlève pas les N+1 mais ça gagne quelques millisecondes

rollback refacto to win milliseconds

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/mailers/solicitation_mailer/kbis_extract.html.haml
config/locales/mailers.fr.yml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/solicitation_mailer_preview.rb
swagger/v1/swagger.yaml

Add mail kbis

---

app/models/antenne.rb

debug fichiers stats

---

app/front/stylesheets/application/need_show.sass
app/policies/match_policy.rb
app/views/matches/_match.haml
spec/policies/match_policy_spec.rb

Permet aux responsable de modifier le statut des mises en relations

---

app/views/mailers/user_mailer/quarterly_report.html.haml
config/locales/mailers.fr.yml

Mail temporaire stats dynamiques

---

config/locales/models.fr.yml
spec/services/csv_export/user_exporter_spec.rb

Mention code insee dans fichier referencement

---

app/controllers/manager/stats_controller.rb

Ajoute des graphs pour les responsables

---

app/policies/match_policy.rb

close https://trello.com/c/MekVqrQH/346-modification-des-statuts-des-besoins-en-tant-que-responsable

Enable match update by manager

---

app/models/clockwork.rb
app/models/expert.rb
app/services/reminders_service.rb
spec/controllers/reminders/experts_controller_spec.rb
spec/controllers/reminders/reminders_registers_controller_spec.rb
spec/features/reminders/experts_feature_spec.rb
spec/services/reminders_service_spec.rb
spec/support/reminders_spec_helper.rb

Panier poussin : MER reçue plutôt que cloturée

---

Gemfile.lock
app/controllers/manager/needs_controller.rb
app/models/antenne.rb
app/views/about/accessibilite.html.erb
app/views/reports/index.html.haml
yarn.lock

closes https://place-des-entreprises-org.sentry.io/issues/4567135435/?project=5747178&query=is%3Aunresolved&referrer=issue-stream&stream_index=3

debug du jeudi

---

Gemfile
Gemfile.lock
config/environments/production.rb

add redis for caching

---

app/front/stylesheets/components/table.sass
app/views/annuaire/users/_table.html.haml
spec/system/annuaire_system_spec.rb

MaJ annuaire : 3 colonnes fixées + trait épais

---

app/views/mailers/company_mailer/notify_taking_care.html.haml
config/locales/mailers.fr.yml

Affichage institution dans mail de prise en charge

---

app/front/stylesheets/components/table.sass

Fix affichage annuaire

---

app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

Flag Cycle abandon

---

app/controllers/concerns/iframe_prefix.rb
app/jobs/application_job.rb
app/services/stats/needs/themes.rb
spec/controllers/landings/landings_controller_spec.rb
spec/controllers/solicitations_controller_spec.rb

https://place-des-entreprises-org.sentry.io/issues/4628680507/events/c435c804c848419e9582c51ac084b071/?project=5747178

correction redirections des vieux sujet, couleurs des stats

---

app/services/csv_export/solicitation_exporter.rb

Ajout des infos page d'origine dans les exports

---

app/views/solicitations/_header.html.haml
app/views/stats/_load_stats.html.haml
app/views/stats/_main_stats_chart.haml
app/views/stats/_ministats.haml
lib/tasks/staging_transform_data.rake

Debug: chiffres stats non tronqués

---

app/models/institution_subject.rb
app/services/stats/needs/transmitted.rb
app/views/conseiller/solicitations/_solicitation.haml
app/views/needs/show.html.haml
spec/features/admin_controller_feature_spec.rb

Debug : Empeche les dépassements de ligne + jointures

---

app/jobs/admin/send_failed_jobs_job.rb
app/mailers/admin_mailer.rb
app/views/mailers/admin_mailer/failed_jobs.html.haml
config/locales/mailers.fr.yml
spec/mailers/previews/admin_mailer_preview.rb

J'ai pas l'impression qu'on puisse avoir la liste, avoir le nombre pour nous alerter me parait suffisant pour pas passer des heures là-dessus
closes #3293

fix email for failed jobs

---

app/jobs/admin/send_failed_jobs_job.rb
app/mailers/admin_mailer.rb
app/models/clockwork.rb
app/views/feedbacks/_feedback.haml
app/views/mailers/admin_mailer/failed_jobs.html.haml
config/initializers/rack_attack.rb
config/initializers/sidekiq.rb
config/locales/mailers.fr.yml
doc/05-gotchas.md
spec/mailers/previews/admin_mailer_preview.rb

Debug : rapports envoyés après 3jours + Sidekiq Failures + lignes dépassent commentaires

---

app/views/mailers/solicitation_mailer/intermediary.html.haml
config/locales/mailers.fr.yml

Met à jour l'email "intermédiaire" et "pas d'expert"

---

app/admin/feedback.rb
app/controllers/conseiller/csv_exports_controller.rb
app/models/expert.rb
app/models/feedback.rb
app/services/csv_export/feedback_exporter.rb
config/locales/models.fr.yml
spec/factories/company_satisfactions.rb
spec/services/csv_export/feedback_exporter_spec.rb

Fichier des commentaires

---

app/controllers/stats/public_controller.rb
app/controllers/stats/team_controller.rb
app/services/stats/companies/by_employees.rb
app/services/stats/needs/abandoned.rb
app/services/stats/needs/done_no_help.rb
app/services/stats/needs/done_not_reachable.rb
app/services/stats/needs/exchange_with_expert.rb
app/services/stats/needs/exchange_with_expert_column.rb
app/services/stats/needs/not_for_me.rb
app/services/stats/needs/quo.rb
app/services/stats/needs/taking_care.rb
app/services/stats/needs/themes.rb
app/services/stats/needs/transmitted.rb
config/locales/views.fr.yml

Mise à jour des stats avec besoins abandonnés détaillés

---

config/initializers/sidekiq.rb

Cf https://github.com/mhfs/sidekiq-failures/issues/146

Sidekiq failures config outside

---

app/controllers/conseiller/diagnoses/steps_controller.rb
app/controllers/emails/solicitations_controller.rb
app/front/stylesheets/utilities.sass
app/helpers/solicitation_helper.rb
app/mailers/solicitation_mailer.rb
app/services/send_solicitation_generic_email.rb
app/views/conseiller/diagnoses/steps/_next_step.haml
app/views/conseiller/diagnoses/steps/contact.html.haml
app/views/conseiller/diagnoses/steps/matches.html.haml
app/views/conseiller/diagnoses/steps/needs.html.haml
app/views/conseiller/solicitations/_solicitation.haml
app/views/mailers/solicitation_mailer/bad_quality.html.haml
app/views/pages/_cta_button.haml
config/locales/mailers.fr.yml
config/locales/views.fr.yml
spec/controllers/conseiller/diagnoses/steps_controller_spec.rb
spec/mailers/solicitation_mailer_spec.rb
spec/services/send_solicitation_generic_email_spec.rb

Permet de changer le sujet d'un besoin depuis une sollicitation

---

app/services/api_consumption/models/facility/base.rb
app/views/companies/_facility.html.haml
app/views/needs/show.html.haml

Evite une 500 sur la page de vue d'une entreprise s'il n'y a pas de code Insee et sur la page d'un besoin s'il n'y a pas de sollicitation

debug du jeudi 01

---

app/models/diagnosis.rb
app/models/solicitation.rb
app/services/stats/base_stats.rb
app/services/stats/matches/base.rb
app/services/stats/matches/done.rb
app/services/stats/matches/done_no_help.rb
app/services/stats/matches/done_not_reachable.rb
app/services/stats/matches/not_for_me.rb
app/services/stats/matches/not_positioning.rb
app/services/stats/matches/positioning.rb
app/services/stats/matches/taking_care.rb
app/services/stats/needs/abandoned.rb
app/services/stats/needs/base.rb
app/services/stats/needs/done.rb
app/services/stats/needs/done_no_help.rb
app/services/stats/needs/done_not_reachable.rb
app/services/stats/needs/exchange_with_expert.rb
app/services/stats/needs/not_for_me.rb
app/services/stats/needs/quo.rb
app/services/stats/needs/taking_care.rb
app/services/stats/needs/themes.rb
app/services/stats/needs/transmitted.rb
app/services/xlsx_export/antenne_stats_exporter.rb
doc/05-gotchas.md

- prendre en compte les besoins des experts supprimés
- ne prendre que les besoins issues de sollicitations
- prendre les MER selon la date de création de la sollicitations correspondantes
close #3330 
close #3345 
Besoins sans solicitation :
```ruby
needs=Need.joins(:diagnosis).where(diagnosis: { solicitation_id: nil }, created_at: '2021-09-01'.to_time.beginning_of_day..).order(:created_at)
hash = {}
needs.joins(:visitee).where.not(visitee: { email: ['test@test.fr', 'adeline.latron@beta.gouv.fr']}).find_each do |need|
base = { need_id: need.id, need_created_at: need.created_at }
contact_email = need&.visitee&.email
if contact_email.nil?
hash[need.id] = base.merge({ solicitations: 'no_contact' })
else
solicitations = Solicitation.where(email: contact_email)
if solicitations.any? …
```

Amélioration de la cohérence des Stats 

---

app/controllers/manager/stats_controller.rb
app/helpers/stats_helper.rb
app/models/antenne.rb
app/views/manager/stats/_stats_params.haml
app/views/reports/index.html.haml
app/views/stats/team/_stats_params.haml
doc/05-gotchas.md
spec/factories/antennes.rb
spec/factories/users.rb
spec/features/reports/report_feature_spec.rb
spec/helpers/stats_helper_spec.rb

Pour l'instant, j'ai trié par ordre de niveau territorial et alphabétique. 
closes #3338

Trie les antennes dans le select des stats

---

app/views/stats/team/index.html.haml
config/locales/views.fr.yml

Ajoute une alerte dans l'onglet "stats public" pour les admins quand il y a  une institution de sélectionné
closes #3355

adds alerte for admin public stats

---

app/controllers/stats/team_controller.rb
app/services/stats/needs/abandoned.rb
app/services/stats/needs/abandoned_total_count.rb
app/services/stats/needs/done_no_help.rb
app/services/stats/needs/done_not_reachable.rb
app/services/stats/needs/not_for_me.rb
config/locales/views.fr.yml
spec/views/stats/team/index.html.haml_spec.rb

Stats par besoins derniers ajustement

---

app/controllers/manager/stats_controller.rb
app/views/manager/stats/index.html.haml
config/locales/views.fr.yml

Ajoute une alerte sur la page des stats d'un responsable si son antenne n'a pas d'experts avec des sujets
closes https://place-des-entreprises-org.sentry.io/issues/4993061119/?project=5747178&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

Ajoute une alerte sur la page des stats d'un responsable si son antenne n'a pas d'experts avec des sujets

---

app/views/solicitations/step_contact.html.haml

ajoute une longueur minimum pour le champ téléphone

---

app/views/companies/_company.html.haml
app/views/needs/show.html.haml
config/locales/views.fr.yml

Suppression de l'affichage des registres pour les conseillers

---

app/views/landings/landings/_multiple_steps.html.haml

Modification du tracking sur page contactez-nous

---

app/views/shared/_matomo.html.erb

retire le Matomo de data.gouv

---

.circleci/config.yml
Gemfile.lock
spec/rails_helper.rb

Avec l'aide de https://bentranz.medium.com/codeclimate-setup-for-ruby-on-rails-project-b8ccf1fe390

Ajoute la config codeclimate

---

app/controllers/concerns/iframe_prefix.rb
app/controllers/solicitations_controller.rb
spec/controllers/solicitations_controller_spec.rb
spec/mailers/expert_mailer_spec.rb
spec/models/api_key_spec.rb
spec/policies/need_policy_spec.rb

Redirect entreprendre solicitations

---

app/controllers/needs_controller.rb
app/front/stylesheets/application/need_show.sass
app/policies/need_policy.rb
app/views/needs/_additional_experts.haml
app/views/needs/show.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/needs_controller_spec.rb
spec/policies/need_policy_spec.rb

Met à jour le formulaire de choix d'un expert en mode ambulance

---

README.md

adds badges

---

app/front/stylesheets/application/need_show.sass
app/front/stylesheets/components/tags.sass
app/services/api_consumption/models/company/api_entreprise.rb
app/views/manager/stats/index.html.haml
app/views/matches/_match.haml
app/views/needs/show.html.haml

- https://trello.com/c/Q9aTCkfX/394-affichage-d%C3%A9cal%C3%A9
- https://place-des-entreprises-org.sentry.io/issues/5101330231/?project=5747178&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=3

Debug - Amelioration MER page besoin + corrections mineures

---

app/views/mailers/solicitation_mailer/kbis_extract.html.haml
config/locales/mailers.fr.yml

Add non diffusible info

---

app/controllers/conseiller/diagnoses_controller.rb
app/models/concerns/diagnosis_creation.rb
spec/controllers/conseiller/diagnoses_controller_spec.rb
spec/models/concerns/diagnosis_creation_spec.rb

close https://place-des-entreprises-org.sentry.io/issues/5198149840/?project=5747178&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=8

MaJ creation diagnosis pour les mauvaises qualités

---

app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

add intermediary alert for solicitations

---

app/admin/user.rb
app/models/user.rb
app/models/user_right.rb
app/views/mailers/expert_mailer/_support_contacts.html.haml
app/views/mailers/expert_mailer/_support_contacts.text.erb
app/views/mailers/user_mailer/quarterly_report.html.haml
config/locales/mailers.fr.yml
config/locales/models.fr.yml
db/migrate/20240426121938_create_national_referent.rb
db/schema.rb
spec/factories/users.rb
spec/views/mailers/expert_mailer/_support_contacts.html.haml_spec.rb

Affiche les coordonnées des référents nationaux pour les responsables d'antennes nationales

---

app/jobs/company_emails/send_intelligent_retention_emails_job.rb
app/views/application/_navbar.html.haml
app/views/conseiller/sitemap/sitemap.html.haml
app/views/landings/landings/home.haml
app/views/pages/_navbar.haml

- fallback tarteaucitron
- pas d'envoi de retention intelligente pour les vieux besoins

Debug : pas d'envoi de retention intelligente pour les vieux besoins / fallback tarteaucitron

---

app/admin/company.rb
app/admin/facility.rb
app/helpers/companies_helper.rb
app/policies/expert_policy.rb

Natures activité en admin / responsables voient MER de comptes supprimées

---

app/views/pages/_tarteaucitron.html.erb

closes #3427 
https://developers.google.com/tag-platform/security/guides/consent?consentmode=basic&hl=fr#tag-manager_2

Update Google consent mode

---

app/models/concerns/with_effectif.rb
app/services/csv_export/match_exporter.rb
app/services/csv_export/solicitation_exporter.rb
app/services/stats/companies/by_employees.rb
app/services/xlsx_export/match_exporter.rb
config/locales/data/codes_effectif.fr.yml

Fusionne les 0 salariés, non employeurs et absence données

---

app/policies/expert_policy.rb
spec/policies/expert_policy_spec.rb

Tout les conseillers peuvent voir les MER des conseillers supprimés

---

app/views/devise/sessions/new.html.haml

Encart connexion France Travail

---

app/controllers/api/v1/landings/base_controller.rb
app/controllers/api/v1/landings/landings_controller.rb
app/views/mailers/company_mailer/confirmation_solicitation.mjml
config/locales/mailers.fr.yml
spec/requests/api/v1/landings_spec.rb
spec/swagger_helper.rb

Debug 20240507

---

app/helpers/application_helper.rb
app/helpers/seo_helper.rb
app/views/landings/landings/home.haml
app/views/layouts/pages.html.haml
app/views/pages/_faq.html.haml

Ajout rich snippets accueil + rétablissement page comment ça marche

---

app/jobs/antenne_coverage/update_job.rb

Bug annuaire codes insee manquants

---

app/views/about/mentions_d_information.fr.html.erb
app/views/about/mentions_legales.fr.html.erb

MaJ mentions d'info (cookies baleen)

---

app/views/devise/sessions/new.html.haml

Suppression de l'encart FranceTravail

---

app/models/match_filter.rb
spec/models/match_filter_spec.rb

Clean code_naf with point in match_filter

---

app/models/institution.rb
spec/models/institution_spec.rb

met à jour le référencement des antenne à l'ajout d'un sujet à une institution

---

app/admin/company_satisfaction.rb
app/models/company_satisfaction.rb
app/policies/shared_satisfaction_policy.rb
app/views/application/_navbar.html.haml
config/locales/models.fr.yml
spec/policies/shared_satisfaction_policy_spec.rb

@LucienMLD petite amélioration assez pressée pour Adeline.
Je voulais aussi mettre dans la PR le filtre "satisfaction avec commentaire" mais me suis cassée les dents dessus. Je te laisse voir si tu arrives à le faire vite fait, sinon ce sera à expédier comme ça

Cache satisfaction si manager ou admin

---

.codeclimate.yml
app/services/quarterly_reports/generate_reports.rb
app/services/time_duration_service.rb
app/services/xlsx_export/antenne_stats_exporter.rb
app/views/reports/index.html.haml
spec/services/quarterly_reports/generate_reports_spec.rb

garder les fichiers stats de l'année dernière complète plus l'année en cours

---

config/initializers/content_security_policy.rb

nettoyage des csp

---

app/controllers/concerns/load_filter_options.rb
app/front/javascripts/shared/controllers/stats_controller.js
app/services/stats/base_stats.rb
app/services/stats/filters/base.rb
app/services/stats/filters/companies.rb
app/services/stats/filters/matches.rb
app/services/stats/filters/needs.rb
app/services/stats/filters/solicitations.rb
app/views/mailers/company_mailer/confirmation_solicitation.mjml
app/views/stats/team/_stats_params.haml
app/views/stats/team/_tabs.html.haml
app/views/stats/team/index.html.haml
config/locales/models.fr.yml
package.json
spec/mailers/previews/company_mailer_preview.rb
spec/services/stats/filters/companies_spec.rb
spec/services/stats/filters/matches_spec.rb
spec/services/stats/filters/needs_spec.rb
spec/services/stats/filters/solicitations_spec.rb
spec/views/stats/team/index.html.haml_spec.rb
yarn.lock

Ajout filtre API dans les stats équipe

---

app/assets/stylesheets/application/custom_components.sass
app/views/conseiller/shared_satisfactions/_need.haml
spec/a11y/application/shared_satisfactions_spec.rb

Change la couleur de la notification besoins + tests accessibilité

---

app/views/about/_transcription_pde_presentation.haml
app/views/about/cgu.fr.html.erb
app/views/pages/_how_it_works_long.html.haml

met à jour la vidéo de présentation

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/mailers/solicitation_mailer/retirement_liberal_professions.mjml
config/locales/mailers.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/solicitation_mailer_preview.rb

Ajoute le mail Retraite PL - CIPAV CARPIMKO

---

.codeclimate.yml
app/services/xlsx_export/antenne_stats_worksheet_generator/base.rb
app/services/xlsx_export/antenne_stats_worksheet_generator/by_subject.rb
config/locales/models.fr.yml

closes #3483 
- séparation des thématiques de l'institution et des thématiques occasionnelles
- ajout d'une phrase pour expliquer le potentiel décalage entre nombre de besoins et MER

Amélioration du fichier stats partenaire

---

app/views/conseiller/shared_satisfactions/_callout.html.haml
config/locales/views.fr.yml
spec/features/reminders/experts_feature_spec.rb

Ajout Avertissement consentement pour les satisfactions

---

app/views/mailers/solicitation_mailer/moderation.mjml
config/locales/mailers.fr.yml

Actualisation du mail Modération

---

app/assets/stylesheets/components/cards.sass
app/helpers/solicitation_helper.rb
app/views/conseiller/solicitations/_solicitation.haml
spec/helpers/solicitation_helper_spec.rb

Affiche les informations d'une sollicitation sous forme de liste html

---

app/policies/need_policy.rb
spec/policies/need_policy_spec.rb

Fix cas particulier responsable pour autorisation d'accès a un besoin

---

app/models/subject_answer.rb
app/models/subject_answer_grouping.rb
app/services/create_diagnosis/find_relevant_expert_subjects.rb
spec/services/create_diagnosis/find_relevant_expert_subjects_spec.rb

Fix pb de filtre d'Initiative

---

app/admin/institution.rb
app/admin/solicitation.rb
app/admin/subject.rb
app/controllers/api/v1/solicitations_controller.rb
app/controllers/conseiller/solicitations_controller.rb
app/helpers/needs_helper.rb
app/serializers/api/v1/simple_subject_answer_serializer.rb
app/serializers/api/v1/subject_question_serializer.rb
app/views/conseiller/diagnoses/steps/needs.html.haml
app/views/conseiller/solicitations/_solicitation.haml
app/views/needs/show.html.haml
app/views/solicitations/step_description.html.haml
config/locales/models.fr.yml
swagger/v1/swagger.yaml

Ajout des questions dans les sollicitations en admin

---

app/models/feedback.rb
spec/models/feedback_spec.rb

commentaires des admins, n'envoie pas d'email au expert ayant clôturé par injoignable

---

app/services/sitemap_generator.rb
app/views/sitemap/sitemap.xml.builder

Correction des dates du sitemap

---

app/controllers/users/invitations_controller.rb
app/views/devise/invitations/edit.html.haml
app/views/devise/passwords/edit.html.haml
app/views/users/registrations/password.html.haml
config/locales/devise.fr.yml
spec/system/users/invitations_controller_spec.rb

Amélioration du process d'invitation

---

app/admin/expert.rb
app/admin/reassign_matches.rb
app/admin/user.rb
app/models/expert.rb
app/models/user.rb
app/views/admin/reassign_matches/_reassign_matches.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/models/expert_spec.rb
spec/models/user_spec.rb

réattribut les mer aux experts plutôt qu'aux utilisateurs

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/mailers/solicitation_mailer/formalites_asso_agri_sci.mjml
app/views/mailers/solicitation_mailer/mediateurs.mjml
config/locales/mailers.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/solicitation_mailer_preview.rb

Ajout mail Formalites asso agri sci et Mediateurs

---

app/admin/user.rb
app/controllers/annuaire/users_controller.rb
app/controllers/experts_controller.rb
app/helpers/annuaire_helper.rb
app/models/expert.rb
app/models/user.rb
app/services/csv_export/user_exporter.rb
app/services/csv_import/user_importer.rb
app/services/xlsx_export/user_exporter.rb
app/views/annuaire/antennes/_table.html.haml
app/views/annuaire/base/_import_errors.html.haml
app/views/annuaire/users/_table.html.haml
app/views/annuaire/users/index.html.haml
app/views/conseiller/sitemap/sitemap.html.haml
app/views/users/_menu.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/controllers/annuaire/users_controller_spec.rb
spec/features/annuaire/users_spec.rb
spec/models/user_spec.rb
spec/services/csv_export/user_exporter_spec.rb
spec/services/csv_import/user_importer_spec.rb
spec/system/annuaire_system_spec.rb

simplifie l'annuaire en partant des experts

---

app/assets/stylesheets/components/cards.sass
app/controllers/conseiller/suivi_qualite_controller.rb
app/helpers/reminders_helper.rb
app/models/reminders_action.rb
app/views/conseiller/suivi_qualite/_refused_feedback_need.haml
config/brakeman.ignore
config/locales/views.fr.yml

Amelioration carte commentaire refusées

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml

permet de créer un expert à la création d'un utilisateur ou depuis sa page admin

---

app/services/api_france_competence/base.rb
app/services/api_france_competence/siret/base.rb
spec/api_helper.rb
spec/controllers/companies_controller_spec.rb
spec/models/use_cases/search_facility_spec.rb
spec/services/api_consumption/facility_spec.rb
spec/services/api_france_competence/siret/base_spec.rb

Fix accès API France Compétence

---

app/controllers/stats/public_controller.rb
app/services/stats/needs/done_with_help_column.rb
app/views/stats/public/index.haml
config/locales/views.fr.yml
spec/views/stats/public/index.html.haml_spec.rb
spec/views/stats/team/index.html.haml_spec.rb

Met à jour la mesure d’impact

---

app/admin/expert.rb
app/admin/user.rb
app/assets/stylesheets/components/table.sass
app/controllers/annuaire/users_controller.rb
app/controllers/experts_controller.rb
app/controllers/manager/stats_controller.rb
app/controllers/users/registrations_controller.rb
app/models/user.rb
app/policies/antenne_policy.rb
app/views/conseiller/sitemap/sitemap.html.haml
app/views/experts/edit.html.haml
app/views/experts/subjects.html.haml
app/views/manager/stats/_stats_params.haml
app/views/manager/stats/index.html.haml
app/views/users/_menu.html.haml
app/views/users/registrations/antenne.html.haml
app/views/users/registrations/password.html.haml
config/initializers/active_admin.rb
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
spec/a11y/application/devise_spec.rb
spec/a11y/application/pages_spec.rb
spec/policies/antenne_policy_spec.rb

Suite amelioration experts

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
spec/features/signin_spec.rb
spec/system/users/passwords_controller_spec.rb

Fix problème de connection à cause du token d'invitation

---

app/controllers/needs_controller.rb
app/views/needs/_star_btn.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/needs_controller_spec.rb

closes [#3615](https://github.com/betagouv/conseillers-entreprises/issues/3615)

Permet de ne plus suivre un besoin si on a cliqué sans faire exprès

---

app/models/expert_subject.rb
app/models/facility.rb
spec/models/expert_subject_spec.rb

MaJ filtre RNE : ajout APRM + toutes les chambres si pas de nature d'activité

---

app/models/user.rb

corrige la création d'expert d'un utilisateur quand case pas coché

---

app/helpers/reminders_helper.rb

Actualise la page des besoins suivies quand on clique sur traiter

---

app/controllers/annuaire/users_controller.rb
app/services/api_entreprise/base.rb
app/services/api_insee/base.rb
app/services/xlsx_export/annuaire_user_exporter.rb
app/services/xlsx_export/base_exporter.rb

le premier commit est un commit de début avec la tentative de résoudre le missing template pour l'erreur 500 en json

Améliore l'export xls de l'annuaire pour faire apparaitre tout les experts

---

app/models/landing.rb
app/models/landing_theme.rb
app/models/theme.rb
app/services/stats/needs/themes.rb
config/locales/models.fr.yml
db/migrate/20240923150853_add_cooperation_to_themes.rb

Regroupement des thématiques coopération

---

app/admin/landing.rb
config/locales/models.fr.yml

Ajout lien fin des iframes en admin

---

app/models/expert.rb
app/services/xlsx_export/annuaire_user_exporter.rb
spec/models/expert_spec.rb

N'affiche pas les experts personnels dans les exports xlsx

---

app/models/solicitation.rb
app/services/xlsx_export/base_exporter.rb
app/services/xlsx_export/match_exporter.rb
spec/models/solicitation_spec.rb

Ajoute une colonne "Intitulé de la source" pour l'export des responsables

---

app/admin/theme.rb

Dis donc, j'avais oublié d'ajouter les champs permettant d'éditer le boolean coopération des thèmes

Ajout des champs d'edition de cooperation, themes

---

app/controllers/concerns/iframe_prefix.rb
app/models/solicitation.rb
app/views/solicitations/step_contact.html.haml
spec/features/new_solicitation_no_js_feature_spec.rb

Pré-remplissage du formulaire contact

---

app/controllers/annuaire/users_controller.rb
spec/controllers/annuaire/users_controller_spec.rb

- closes [#3672](https://github.com/betagouv/conseillers-entreprises/issues/3672)

Permet de voir les utilisateurs sans expert dans l'annuaire

---

app/controllers/annuaire/users_controller.rb
app/helpers/annuaire_helper.rb
app/views/annuaire/users/_table.html.haml
config/locales/views.fr.yml

corrige l'annuaire, les utilisateurs apparaissent plusieurs fois

---

app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
spec/models/solicitation_spec.rb

Plusieurs abandons nécessaires pour marquer une solicitation

---

app/assets/stylesheets/components/cards.sass
app/assets/stylesheets/shared/typo.sass
app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
config/locales/data/categories_juridiques.fr.yml
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

Ajoute une alerte "Pas SAS" pour les sollicitations et met à jour les badges

---

app/admin/landing.rb
app/helpers/needs_helper.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
app/views/needs/show.html.haml
config/locales/models.fr.yml
spec/helpers/solicitation_helper_spec.rb

close #3699 
/!\ Mettre les champs `display_partner_url` des landings internes à `true`

Affiche le lien vers les fiches entreprendre

---

app/controllers/conseiller/diagnoses_controller.rb
app/models/solicitation.rb
app/services/api_consumption/models/facility/api_entreprise.rb
app/services/stats/needs/abandoned_total_count.rb
lib/tasks/rattrapage_api_rne.rake
spec/controllers/conseiller/diagnoses_controller_spec.rb

Fix : 
- [NoMethodError Conseiller::DiagnosesController#create - undefined method `persisted?' for an instance of Hash](
https://conseillers-entreprises-org.sentry.io/issues/6089551471/?environment=production&project=5747178&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0)
- [ActionView::Template::Error 
Conseiller::SolicitationsController#processed - undefined method `subject' for nil](https://conseillers-entreprises-org.sentry.io/issues/6089387390/?environment=production&project=5747178&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=4)
- [ActionView::Template::Error 
CompaniesController#show - undefined method `[]' for nil …

Debug 241125

---

app/models/solicitation.rb
app/views/solicitations/step_description.html.haml
config/locales/views.fr.yml

closes [#3711](https://github.com/betagouv/conseillers-entreprises/issues/3711)

Ajoute une case a cocher pour envoyer la sollicitation sur deux sujets

---

app/admin/landing.rb
app/admin/landing_theme.rb
app/admin/logo.rb
app/models/institution.rb
app/models/landing.rb
app/models/landing_subject.rb
app/models/logo.rb
app/views/landings/landings/home.haml
app/views/landings/landings/show.haml
config/locales/models.fr.yml
db/migrate/20241119103228_clean_logos.rb
db/schema.rb

En lien avec la PR Cooperation (#3701), car les 2 migrations dans la foulée cassent tout

MaJ du fonctionnement des logos (logo polymorphique)

---

app/controllers/conseiller/suivi_qualite_controller.rb
app/models/match.rb
app/models/need.rb
app/views/conseiller/suivi_qualite/_filters.html.haml

Ajout d'un filtre par institution dans Suivi qualité

---

app/models/user.rb
spec/models/concerns/soft_deletable_spec.rb

Supprime les droits des utilisateurs que l'on supprime

---

app/mailers/solicitation_mailer.rb
app/views/mailers/solicitation_mailer/bad_quality.mjml
config/locales/mailers.fr.yml
spec/mailers/previews/expert_mailer_preview.rb

en lien avec #3700 
close #3734

Cooperation ajustements

---

app/models/need.rb

Fix https://conseillers-entreprises-org.sentry.io/issues/6147749890/?project=5747178&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=19

Fix stats acquisition

---

app/views/shared/_transcription_pde_tutoriel.html.haml
app/views/user_pages/tutoriels.haml

Met à jour les liens vers la vidéo de tuto

---

app/mailers/solicitation_mailer.rb
app/models/solicitation.rb
app/views/mailers/solicitation_mailer/administrations_collectivites.mjml
app/views/mailers/solicitation_mailer/creation.mjml
config/locales/mailers.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/solicitation_mailer_preview.rb

Mail automatique administration

---

app/models/concerns/naf_code.rb
app/services/api_consumption/models/facility/api_entreprise.rb
spec/models/concerns/naf_code_spec.rb

Corrige un soucis avec un code_nafa non pas `nil` mais `""`

Fix blank nafa code

---

app/admin/solicitation.rb
app/models/concerns/mandatory_answers.rb
app/models/need.rb
app/models/solicitation.rb
spec/controllers/conseiller/diagnoses/steps_controller_spec.rb
spec/factories/needs.rb
spec/services/diagnosis_creation/find_relevant_expert_subjects_spec.rb

Fix problème questions besoins

---

app/controllers/conseiller/solicitations_controller.rb
app/services/stats/needs/abandoned_total_count.rb
config/locales/views.fr.yml

fix redirection après changement de sujet et graph des abandonnés

---

app/models/match.rb
spec/models/match_spec.rb

Fix auto-cloture des MER france-travail

---

app/services/csv_export/feedback_exporter.rb
spec/services/csv_export/feedback_exporter_spec.rb

Ajout auteur commentaire dans export csv

---

app/controllers/conseiller/cooperations_controller.rb
app/models/feedback.rb

- fix le select des sujets dans Coopération
- close #3781

Debug 250130

---

app/services/build_antennes_collection.rb

Corrige le select des antennes pour les responsables

---

app/admin/user.rb
app/models/user.rb
app/policies/match_policy.rb
app/policies/shared_satisfaction_policy.rb
config/locales/models.fr.yml
spec/factories/users.rb
spec/policies/shared_satisfaction_policy_spec.rb

close #3790 
close #3791 
close #3793

Evol mer manager

---

app/helpers/admin_expert_card_footer_helper.rb

closes https://conseillers-entreprises-org.sentry.io/issues/6293213806/?project=5747178&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20%21title%3A%2AApi%2A&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=3

jeudi debug

---

app/models/solicitation.rb
app/views/conseiller/solicitations/_solicitation.haml
config/locales/views.fr.yml

Ajoute une alerte sur les sollicitation de l'xp urssaf

---

app/admin/user.rb

Affiche le bouton invitation demo pour les responsables

---

app/admin/theme.rb
app/controllers/application_controller.rb
app/models/landing_theme.rb
app/models/user.rb
app/policies/match_policy.rb
app/policies/report_policy.rb
app/services/xlsx_export/annuaire_user_exporter.rb
spec/models/user_spec.rb
spec/policies/match_policy_spec.rb

close #3815 
close https://trello.com/c/wSsOOs7O/514-fichier-de-ref-depuis-lannuaire
close https://conseillers-entreprises-org.sentry.io/issues/6314022007/?environment=production&project=5747178&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=8

Debug 250220

---

app/views/mailers/solicitation_mailer/creation.mjml
config/locales/mailers.fr.yml
config/locales/views.fr.yml

Ajout "Après échange téléphonique" pour clôture Pas d'aide disponible

---

.rubocop.yml
app/services/check_password_complexity.rb
config/initializers/devise.rb
config/locales/devise.fr.yml
config/locales/fr.yml
doc/04-architecture.md
public/.well-known/security.txt
spec/factories/users.rb
spec/features/application_controller_feature_spec.rb
spec/features/signin_spec.rb
spec/features/users/registrations_controller_spec.rb
spec/models/user_spec.rb
spec/system/users/invitations_controller_spec.rb
spec/system/users/passwords_controller_spec.rb

Amélioration documentation et renforcement politique de mot de passe

---

config/locales/data/prefill_feedbacks.fr.yml

MaJ commentaires pré-remplis

---

app/views/conseiller/shared_satisfactions/_need.haml

Fix Vu des partages de satisfaction

---

config/locales/views.fr.yml

Ajouter l'info SIRET dans la recherche en BAL

---

app/models/solicitation.rb
config/locales/views.fr.yml

Case 'je certifie être dirigeant' sur sujet 'Financer investissement'

---

app/controllers/conseiller/experts_controller.rb
app/serializers/autocomplete/expert_serializer.rb
app/serializers/autocomplete/expert_subject_serializer.rb

Fix select des experts en admin

---

app/assets/stylesheets/shared/utilities.sass
app/front/javascripts/application/controllers/password_visibility_controller.js
app/views/devise/invitations/edit.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/sessions/new.html.haml
app/views/shared/_password_tips.html.haml
app/views/shared/_visibility_password_button.html.haml
app/views/users/registrations/password.html.haml
config/locales/devise.fr.yml
config/locales/views.fr.yml

Afficher / cacher le mot de passe

---

app/mailers/application_mailer.rb

Ajout un header X-Encryption aux emails

---

app/mailers/custom_devise_mailer.rb
app/models/antenne.rb
app/models/concerns/with_support_user.rb
app/models/cooperation.rb
app/models/user.rb
app/views/devise/mailer/invitation_instructions.mjml
config/locales/devise.fr.yml
config/locales/fr.yml
config/locales/models.fr.yml
spec/mailers/previews/devise_mailer_preview.rb

Mail invite cooperation

---

app/controllers/api/v1/solicitations_controller.rb
app/models/solicitation.rb
app/serializers/api/v1/solicitation_serializer.rb
config/locales/models.fr.yml
spec/models/solicitation_spec.rb
spec/requests/api/v1/solicitations_spec.rb
spec/swagger_helper.rb
swagger/v1/swagger.yaml

Passage à la dernière version d'OpenAPI (https://github.com/OAI/OpenAPI-Specification/releases) et nettoyage de l'API

Upgrade openapi

---

app/services/api_consumption/models/facility/api_entreprise.rb
app/services/diagnosis_creation/find_relevant_expert_subjects.rb
app/views/about/mentions_legales.fr.html.erb

close https://trello.com/c/rYpPzQ80/539-opco-akto-mayotte
close #3879 
close #3878

Micro evols

---

app/models/expert_subject.rb
app/models/facility.rb
spec/models/expert_subject_spec.rb

Redirect Mayotte solicitations to Akto Mayotte

---

app/admin/company_satisfaction.rb
app/models/company_satisfaction.rb

Filtre antenne pour les satisfactions

---

app/serializers/api/v1/solicitation_logo_serializer.rb
app/serializers/api/v1/solicitation_serializer.rb
spec/requests/api/v1/solicitations_spec.rb
swagger/v1/swagger.yaml

Ajoute l'id de la solicitation en résultat d'API

---

app/admin/antenne.rb
config/locales/models.fr.yml

Affiche nombre d'antennes enfant

---

app/admin/institution.rb
config/locales/models.fr.yml

Renomme les questions dans l'admin des institutions

---

app/controllers/conseiller/cooperations_controller.rb
app/controllers/manager/stats_controller.rb
app/controllers/stats/public_controller.rb
app/controllers/stats/team_controller.rb
app/services/stats/solicitations/five_days_delay.rb
app/services/stats/solicitations/taking_care_time.rb
app/services/stats/solicitations/three_days_delay.rb
config/locales/views.fr.yml

Stats temps de prise en charge pour partenaires et coopérations

---

app/controllers/manager/stats_controller.rb
app/controllers/stats/team_controller.rb

Ajout stats par sujet

---

app/admin/user.rb
app/models/user.rb
app/views/application/_navbar.html.haml
config/locales/mailers.fr.yml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/features/application_controller_feature_spec.rb
spec/system/users/passwords_controller_spec.rb

close #3936
close #3938 
close #3939

MaJ vidéo tuto, mail Carsat, onglet absents

---

app/admin/company_satisfaction.rb
app/admin/expert.rb
app/admin/match.rb
app/admin/user.rb

pour la recherche suivante on passe de plus de 66000 ms à 1500
http://localhost:3000/admin/company_satisfactions?q%5Bcreated_at_gteq%5D=2025-01-01&q%5Bcreated_at_lteq%5D=2025-06-30&q%5Bcontacted_by_expert_eq%5D=true&q%5Buseful_exchange_eq%5D=true&q%5Bshared_eq%5D=shared&commit=Filtrer&order=created_at_desc

Retire les includes non nécessaires sur la page satisfactions

---

app/controllers/solicitations_controller.rb
app/views/solicitations/form_complete.html.haml
app/views/solicitations/step_description.html.haml
config/data/subject_answers.yml
config/locales/models.fr.yml
config/locales/views.fr.yml

Ameliorations suite tests utilisateurs TIH

---

app/admin/user.rb
app/helpers/experts_helper.rb
config/locales/fr.yml
config/locales/models.fr.yml

closes [#3974](https://github.com/betagouv/conseillers-entreprises/issues/3974)

n'affiche pas le badge d'absence si la date de début est dans le futur

---

Gemfile
Gemfile.lock
app/services/api_consumption/aggregators/company.rb
app/services/api_consumption/aggregators/facility.rb

redo #4010, mais en ajoutant la gem, cette fois-ci.

Parallelize api calls in aggregators (deuxième essai)

---

app/admin/feedback.rb
app/models/feedback.rb
config/locales/models.fr.yml

Ajoute un filtre région pour les commentaires en admin
