betagouv/conseillers-entreprises

app/models/user.rb
app/views/errors/404.html.haml
app/views/errors/500.html.haml
app/views/layouts/_footer_home.html.haml
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
config/locales/common.fr.yml
config/locales/common_vuejs.fr.yml
config/locales/devise.fr.yml
config/locales/devise_additions.fr.yml
config/locales/views/companies.fr.yml
config/locales/views/diagnoses.fr.yml
config/locales/views/experts.fr.yml
config/locales/views/home.fr.yml
config/locales/views/layouts.fr.yml
config/locales/views/mailers/admin_mailer.fr.yml
config/locales/views/mailers/expert_mailer.fr.yml
config/locales/views/mailers/territory_user_mailer.fr.yml
config/locales/views/mailers/user_mailer.fr.yml
config/locales/views/territory_users.fr.yml
spec/features/admin_controller_feature_spec.rb
spec/features/application_controller_feature_spec.rb
spec/fixtures/territory_user_statistic_csv_fixture.csv
spec/models/user_spec.rb
spec/services/territory_user_service/csv_generator_spec.rb
spec/views/companies/show.html.haml_spec.rb
spec/views/home/index.html.haml_spec.rb
spec/views/mailers/admin_mailer/weekly_statistics.html.haml_spec.rb
spec/views/mailers/expert_mailer/notify_company_needs.html.haml_spec.rb

Small tweaks to the static/about contents:
* Replace old SGMAP references
* Fix typography
* Fix how the territory admins are displayed. (Mostly to avoid displaying @MathieuGens both in the territory admins and project team.)

Update contact info

---

app/services/sirene_api/sirene_search.rb

Properly URL-encode the query

---

app/views/devise/confirmations/new.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/registrations/new.html.haml
config/locales/devise_additions.fr.yml

The suggestions for firstname, lastname, etc. are more confusing than helpful.

Remove signup suggestions

---

app/services/api_entreprise/entreprise_response.rb
app/services/api_entreprise/etablissement_response.rb

Prevent an error when api-entreprise is down

---

app/admin/dashboard.rb
app/controllers/stats_controller.rb
app/views/stats/_stats_table.html.haml
app/views/stats/index.html.haml
app/views/stats/stats.csv.erb
config/i18n-tasks.yml
config/locales/active_admin.fr.yml
config/locales/views/stats.fr.yml
config/routes.rb

First attempt at `/stats` page. Still unreferenced from the main pages, but with a csv export :)

stats pages

---

app/controllers/companies_controller.rb
app/models/search.rb
app/views/companies/search.html.haml

That one was lost when migrating to the Sirene API 🤷‍♂️

Save recent searches

---

app/admin/diagnosis.rb
app/controllers/api/diagnosed_needs_controller.rb
app/controllers/diagnoses_controller.rb
app/controllers/experts_controller.rb
app/controllers/relays_controller.rb
app/controllers/stats_controller.rb
app/models/diagnosis.rb
app/models/use_cases/get_diagnoses.rb
app/models/user.rb
app/services/admin_mailers_service.rb
app/services/relay_service/mailer_service.rb
db/migrate/20180607102408_add_archived_at_to_diagnosis.rb
db/schema.rb
spec/controllers/diagnoses_controller_spec.rb
spec/controllers/experts_controller_spec.rb
spec/controllers/relays_controller_spec.rb
spec/features/admin_controller_feature_spec.rb
spec/models/diagnosis_spec.rb

Do not fake `destroy` with paranoid, mark as archived instead.

Refactor diagnosis.archive

---

app/views/companies/show.html.haml

Fix missing parameter in Company “Diagnoses” section

---

Procfile
README.md

Auto migrate DB after scalingo deploy

---

Gemfile
Gemfile.lock
db/migrate/20180619114027_remove_deleted_at_from_diagnosis.rb
db/schema.rb

Remove act_as_paranoid

---

app/controllers/diagnoses_controller.rb
app/views/diagnoses/index.html.haml
config/routes.rb

Redirect to the current step in the backend code, not in the UI.

Add diagnoses#show

---

app/admin/territory.rb

Add the advisor name in the summary table in admin/territory

---

app/admin/expert.rb

ActiveAdmin: fix changing territories/assistances of an Expert

---

app/views/devise/registrations/new.html.haml
config/locales/devise_additions.fr.yml

This time, use a specific, chosen wording and not automatic Faker suggestions.
(This becomes more interesting now that #120 is merged)

Add placeholder values to the registration form fields

---

app/admin/contact.rb
app/admin/expert.rb
app/admin/user.rb
app/models/concerns/person_concern.rb
config/locales/active_admin.fr.yml
spec/models/concerns/person_concern_spec.rb

Add `normalize_values` helpers for all Person models

---

app/admin/company.rb
app/admin/expert.rb
app/admin/match.rb
app/admin/relay.rb
app/admin/territory.rb
app/views/admin/_matches.html.arb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml

Relay and Expert, in addition to Territory and Company. Also tweak all these pages.

Add matches table to most admin pages

---

app/admin/match.rb
app/services/admin_mailers_service.rb
app/services/relay_service/information_hash.rb
app/services/relay_service/mailer_service.rb
app/views/admin/_matches.html.arb
app/views/mailers/admin_mailer/weekly_statistics.html.haml
app/views/mailers/relay_mailer/weekly_statistics.html.haml
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
config/locales/views/mailers/admin_mailer.fr.yml
config/locales/views/mailers/relay_mailer.fr.yml
spec/features/admin_controller_feature_spec.rb
spec/mailers/admin_mailer_spec.rb
spec/mailers/relay_mailer_spec.rb
spec/services/admin_mailers_service_spec.rb
spec/services/relay_service/mailer_service_spec.rb
spec/views/mailers/admin_mailer/weekly_statistics.html.haml_spec.rb
spec/views/mailers/relay_mailer/weekly_statistics.html.haml_spec.rb

and “Référent contact” to “Mise en relation”

Rename “contacted_expert” to match

---

app/views/admin/_matches.html.arb
config/locales/active_admin.fr.yml

Fix (again) displaying matches with deleted experts

---

app/admin/user.rb
app/views/layouts/_navbar.html.haml
config/locales/common.fr.yml
config/locales/views/layouts.fr.yml
spec/features/signin_spec.rb

Cleanup and use a dropdown menu for admin / profile / logout.

Make some room in the navbar

---

app/assets/stylesheets/user_impersonate.sass
app/javascript/packs/common/nextStepButton.vue.erb
app/views/diagnoses/step4.html.haml
app/views/user_impersonate/_header.html.haml
config/locales/views/companies.fr.yml

* Change the “teal” buttons to use green like the rest of the app.
* Make sure the “impersonate” footer stays on top

Small UI tweaks

---

app/helpers/companies_helper.rb
spec/helpers/companies_helper_spec.rb

See https://doc.entreprise.api.gouv.fr/#codes-erreur

Workaround a crash if api-entreprise returns an error

---

Gemfile.lock

Fix Gemfile.lock after #162

---

Gemfile
Gemfile.lock
app/mailers/expert_mailer.rb
app/models/use_cases/save_and_notify_diagnosis.rb

So that advisors get out-of-office autoreplies 😁

 Put the advisor email address in the reply_to field

---

app/controllers/application_controller.rb
app/models/match.rb
app/views/experts/_match.html.haml
app/views/needs/_team.html.haml
app/views/users/show.html.haml
config/locales/common.fr.yml
spec/features/admin_controller_feature_spec.rb
spec/features/application_controller_feature_spec.rb

Slightly unrelated, but done in passing.
(in before a large PR)

Preliminary tweaks for experts dashboard

---

app/models/expert.rb
app/models/user.rb
app/views/needs/_team.html.haml
spec/models/user_spec.rb

We’ll want to tweak the UI in some ways if the User and the Expert are the same “person”.

Add user.is_oneself? for 1-1 expert/user relation

---

app/models/relay.rb
spec/models/relay_spec.rb

And properly nullify the reference in the related matches

Allow deleting relays

---

app/views/layouts/_navbar.html.haml
app/views/needs/_assigned_diagnoses.html.haml
app/views/needs/index.html.haml
config/locales/views/layouts.fr.yml
config/locales/views/needs.fr.yml
config/routes.rb
spec/routing/routing_spec.rb

Activate Dashboard for Experts and Relays

---

app/views/diagnoses/step5.html.haml

Fix old reference to “expert/match” partial view

---

app/assets/stylesheets/semantic-ui_extensions.sass

-> https://github.com/sass/sass/issues/1599
The way we use it doesn’t seem to make any difference. 🤷‍♀️

Fix a sass deprecation warning

---

app/admin/category.rb
app/admin/question.rb

Fixup #185: allow modifying the sort order from the admin panel

---

app/models/clockwork.rb

Fix weekly Relay email not being sent

---

config/locales/views/diagnoses.fr.yml

(Except in the first line of git messages)

Sentences end with a single period

---

db/migrate/20180913145542_remove_first_name_last_name.rb
db/schema.rb

This is following PR #120 from two months ago.

Remove the `first_name` and `last_name` columns

---

Gemfile
Gemfile.lock
bin/rspec
bin/spring

This doesn’t solve the html tests being slow, but it’s a start.

Add gem spring-commands-rspec

---

app/models/visit.rb
app/services/expert_mailers_service.rb
app/views/diagnoses/step5.html.haml
app/views/needs/_assigned_diagnoses.html.haml
app/views/needs/show.html.haml

Remove a remnant of `creation_date_localized` and add a helper method above `Visit.happened_on`.

Add Visit.display_date

---

app/admin/match.rb
config/locales/active_record.fr.yml

See https://sentry.data.gouv.fr/betagouvfr/reso/issues/630999/

Fix admin/matches filtering by question

---

app/views/companies/search.html.haml
app/views/diagnoses/index.html.haml

Fix the Search button rounded corners

---

app/admin/diagnosed_need.rb
app/models/diagnosed_need.rb
spec/models/diagnosed_need_spec.rb

C’est un petit pas, mais ça permet déjà d’afficher les besoins en souffrance dans la liste dans l’admin.

Add DiagnosedNeed.status_synthesis

---

app/admin/diagnosed_need.rb
app/models/match.rb
db/migrate/20180921080647_add_matches_count_to_diagnosed_needs.rb
db/schema.rb

* a cache_counter column in db
* a matches_count column in admin/diagnosed_needs

Add a match_count column to diagnosed_need

---

app/controllers/companies_controller.rb
app/services/api_entreprise/etablissement_response.rb

https://sentry.data.gouv.fr/betagouvfr/reso/issues/631498/

Display ApiEntreprise errors instead of a 500

---

spec/mailers/previews/app_mailer_preview.rb
spec/mailers/previews/user_mailer_preview.rb
vendor/assets/stylesheets/mailers.sass

* Basic css styling
* local previews

Mailers Improvements

---

app/mailers/expert_mailer.rb
app/models/concerns/person_concern.rb
app/models/diagnosed_need.rb
spec/models/concerns/person_concern_spec.rb
spec/models/diagnosed_need_spec.rb

* Add Person::email_with_display_name, as we’re going to use it a lot in mailers
* Add DiagnosedNeed::relays_and_experts

Person improvements

---

app/admin/feedback.rb
app/models/feedback.rb
app/models/match.rb
config/locales/active_record.fr.yml
db/migrate/20180925131649_create_feedbacks.rb
db/schema.rb
spec/factories/feedbacks.rb
spec/models/feedback_spec.rb

Add Match Feedback model, access check, ActiveAdmin and base i18n
https://trello.com/b/TdTq4e5P/produit

Add Feedback model

---

app/controllers/feedbacks_controller.rb
app/mailers/user_mailer.rb
app/views/mailers/user_mailer/match_feedback.html.haml
config/locales/views/mailers/user_mailer.fr.yml
spec/mailers/previews/user_mailer_preview.rb
vendor/assets/stylesheets/mailers.sass

https://trello.com/c/UdFYw7oI/245

Send “Feedback” emails to advisors / other experts

---

app/mailers/user_mailer.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/match.rb
spec/models/diagnosed_need_spec.rb

* Add `:through` relationships between Matches/DiagnosedNeeds/Diagnoses
* Allow sorting DiagnosedNeeds by Question sorting order
* Tweak the `relays_and_experts` methods to actually return `Persons`

DiagnosedNeed model improvements

---

app/views/companies/show.html.haml

which _may_ be nil for old data.
https://sentry.data.gouv.fr/betagouvfr/reso/issues/632854/

Use display_date in the company page instead of happened_on

---

app/mailers/expert_mailer.rb
app/services/expert_reminder_service.rb
app/views/mailers/expert_mailer/_reminders_match.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
config/locales/views/mailers/expert_mailer.fr.yml
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
vendor/assets/stylesheets/mailers.sass

Some style adjustments in expert_reminder_service, as well as design refinements in the reminders email.

Refactor expert_reminder_service

---

app/models/diagnosed_need.rb
app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/views/diagnoses/step5.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/needs/show.html.haml
spec/models/diagnosed_need_spec.rb

Always sort diagnosed_needs by category/question interview order

---

app/controllers/stats_controller.rb
app/models/company.rb
app/models/diagnosed_need.rb
app/models/user.rb
app/views/stats/_stats_table.html.haml
app/views/stats/stats.csv.erb

Rework stats to exclude activity from Admin users

---

app/admin/institution.rb
db/migrate/20181022135725_remove_email_and_phone_number_from_institution.rb
db/schema.rb

Préliminaire à https://trello.com/c/z9Ty2rNK/270-nettoyage-institutions

Suppression des email et phone_number des Institutions

---

app/models/antenne.rb
app/models/commune.rb
app/models/institution.rb
app/models/user.rb
db/migrate/20181022140618_create_antennes.rb
db/schema.rb
spec/factories/antennes.rb
spec/models/antenne_spec.rb

Preliminary work for https://trello.com/c/z9Ty2rNK/270-nettoyage-institutions
As with #246, this only adds tables and columns, the behaviour is unchanged.

Add Antenne

---

app/models/facility.rb
app/models/territory_city.rb
db/migrate/20181030094510_make_communes_nonnull.rb
db/schema.rb
spec/models/facility_spec.rb

Following #251, readd nonnull constraints in a separate migration.

Make communes nonnull

---

app/views/admin/_matches.html.arb
config/locales/active_record.fr.yml

* Split the facility name and the commune name in two columns
* Use shorter headers for “Artisanat” and “Commerce”

Small UI improvements in admin

---

app/admin/expert.rb
app/admin/user.rb
app/models/expert.rb
app/models/user.rb
app/views/diagnoses/step4.html.haml
app/views/diagnoses/step5.html.haml
app/views/home/contact.html.haml
app/views/needs/show.html.haml
app/views/users/show.html.haml

`.size` supposedly does the ⭐️ right thing ⭐️  between a `COUNT` request of counting the already-loaded collection.

Use `.size` rather than `.length` or `.count` for ActiveRecord

---

app/controllers/diagnoses_controller.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/user.rb
app/views/diagnoses/step4.html.haml
spec/models/user_spec.rb

Display their role and institution in addition to their name.

Improve relays display in notify

---

app/controllers/application_controller.rb
spec/controllers/matches_controller_spec.rb
spec/controllers/needs_controller_spec.rb
spec/features/application_controller_feature_spec.rb

Readd missing tests for matches_controller and needs_controller

Application controller tests

---

app/services/expert_reminder_service.rb
spec/services/expert_reminder_service_spec.rb

Apparently I 👌 the ruby syntax.
https://trello.com/c/w03V3X0X/282-correction-de-lenvoi-des-mails-de-relance

Fix reminder emails not being properly sent

---

app/admin/antenne.rb
app/admin/user.rb
app/models/antenne.rb
app/models/user.rb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml

To ease the manual edition in https://trello.com/c/z9Ty2rNK/270-nettoyage-institutions and https://trello.com/c/uzBpixmv/264-nettoyage-territoire

Improve admin/users to edit and display Antennes

---

db/migrate/20181108165719_make_antenne_nonnull.rb
db/schema.rb

Now that the production data follows our model =)

Add additional SQL nonnull constraints

---

app/admin/assistance.rb
app/admin/expert.rb
app/admin/territory.rb
app/models/commune.rb
app/models/expert.rb
app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/views/needs/_team.html.haml
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
db/migrate/20181108171440_create_join_table_experts_communes.rb
db/schema.rb
spec/models/commune_spec.rb
spec/models/expert_spec.rb
spec/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts_spec.rb

* When picking Experts to contact, first look at the Antennes on the requested Commune;
* Some Experts have their own intervention zones. (that used to be specified through their territories)

Use Antennes and Experts interventions zones

---

app/admin/antenne.rb
app/admin/commune.rb
app/admin/company.rb
app/admin/diagnosed_need.rb
app/admin/diagnosis.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/relay.rb
app/admin/territory.rb
app/models/territory.rb
app/views/admin/_antennes.html.arb
app/views/admin/_experts.html.arb
app/views/admin/_matches.html.arb
app/views/admin/_users.html.arb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml

following #264 and related issues

Display team (advisors and experts) and antennes in admin/territory

---

app/admin/territory.rb
app/models/territory.rb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
db/migrate/20181114100707_add_bassin_emploi_to_territory.rb
db/schema.rb

Will be used for stats and nicer descriptions of intervention zones.

Add Territory.bassin_emploi

---

app/helpers/admin_helper.rb

Fix admin link leading to antennes instead of territories

---

db/migrate/20181115161951_drop_expert_territories.rb
db/schema.rb

Following #276, we don’t use at all anymore.

Actually drop expert_territories

---

app/admin/user.rb
app/models/user.rb
config/locales/active_admin.fr.yml
spec/models/user_spec.rb

Tries to match:
* existing Antenne of a similar name
* Antennes with experts’ with the same email domain

Add User.autolink_to_antenne

---

app/controllers/feedbacks_controller.rb
app/models/feedback.rb
spec/models/feedback_spec.rb

following https://trello.com/c/UdFYw7oI/245

Disallow empty feedbacks

---

app/admin/territory.rb
app/models/assistance_expert.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/match.rb
app/models/relay.rb

https://trello.com/c/uuE56yiE/291-admin-territoires-trier-les-mises-en-relation-par-date-décroissante.

Admin: order matches by date rather than by status

---

app/models/concerns/many_communes.rb
app/models/concerns/person_concern.rb

Don’t just put everything under `included do`

Codestyle in concerns

---

app/admin/antenne.rb
app/admin/diagnosis.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/territory.rb
app/controllers/diagnoses_controller.rb
app/models/antenne.rb
app/models/assistance.rb
app/models/category.rb
app/models/commune.rb
app/models/company.rb
app/models/concerns/many_communes.rb
app/models/contact.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/facility.rb
app/models/feedback.rb
app/models/institution.rb
app/models/match.rb
app/models/question.rb
app/models/search.rb
app/models/territory.rb
app/models/user.rb
app/models/visit.rb
config/locales/active_record.fr.yml
spec/features/application_controller_feature_spec.rb

Comment out, add `:through` associations and specify inverse associations.

Model improvements

---

app/admin/diagnosed_need.rb
app/admin/expert.rb
app/admin/territory.rb
app/admin/user.rb
app/views/mailers/admin_mailer/weekly_statistics.html.haml
config/i18n-tasks.yml
config/locales/active_admin.fr.yml

Simplify a bunch of things following #294

Fix admin i18n

---

CONTRIBUTING.md
README.md

Remove some deprecated comments from README

---

app/admin/antenne.rb
app/models/concerns/many_communes.rb
spec/models/concerns/many_communes_spec.rb

instead of a single-line text input

Admin: use a text_area for many_communes insee_codes

---

app/views/home/contact.html.haml

see https://sentry.data.gouv.fr/betagouvfr/reso/issues/643989/

Fix user.relay_territories association name

---

app/assets/javascripts/application.js
app/models/diagnosed_need.rb
app/models/match.rb
app/models/user.rb
app/models/visit.rb
config/application.rb
spec/models/antenne_spec.rb
spec/models/diagnosed_need_spec.rb

This _should_ be done; let’s see what breaks.

Use rails_ujs and load rails 5.2 defaults

---

app/models/antenne.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/institution.rb

Preliminary work for https://trello.com/c/Qg5QFeK7/275-pages-stats-engagement-detection

Fix missing model associations

---

app/models/company.rb
app/services/categorie_juridique.rb
config/i18n-tasks.yml
config/locales/categories_juridiques.fr.yml
spec/services/categorie_juridique_spec.rb

more preliminary work for https://trello.com/c/Qg5QFeK7/275-pages-stats-engagement-detection
(but will have more uses)

Add descriptions for “Categories juridiques” of companies

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/stats_controller.rb
app/models/company.rb
app/models/territory.rb
app/services/stats/base_stats.rb
app/services/stats/companies_stats.rb
app/services/stats/diagnosed_needs_stats.rb
app/services/stats/stats.rb
app/views/stats/_stats_chart.html.haml
app/views/stats/charts.html.haml
config/locales/views/stats.fr.yml
config/routes.rb

accessible at /stats/charts, not linked to yet.

Add first version of the charts stats

---

app/services/stats/base_stats.rb
app/services/stats/companies_stats.rb
app/services/stats/diagnosed_needs_stats.rb
app/views/stats/_stats_chart.html.haml

Fix incorrect stats for companies, display the total for each month in the tooltip, and sort categories.

Charts improvements

---

app/views/devise/mailer/_emails_footer.haml

fixes https://sentry.data.gouv.fr/betagouvfr/reso/issues/650252/

Fix team page url in email footer

---

app/admin/antenne.rb
app/admin/institution.rb
app/helpers/institutions_helper.rb
app/models/antenne.rb
app/models/institution.rb
db/migrate/20190117132717_add_show_icon_flag.rb
db/schema.rb

to control which icons should be displayed on the home page.
This is mostly a workaround for some caching issue somewhere between Sprockets and Scalingo.

Add a show_icon flag to Institutions and Antennes

---

app/admin/diagnosed_need.rb
app/admin/diagnosis.rb
app/admin/match.rb
app/models/diagnosis.rb
config/locales/active_record.fr.yml

* improve filters from admin/territories. 
* improve columns in admin/territories

Small improvements in admin

---

app/models/facility.rb
app/views/diagnoses/step5.html.haml
app/views/needs/_assigned_diagnoses.html.haml
app/views/needs/_diagnosis_summary.haml
app/views/needs/show.html.haml
config/locales/views/diagnoses.fr.yml
config/locales/views/needs.fr.yml

Also dry it in a partial for both diagnoses/step5 and needs/show.

Add the SIRET in the diagnosis summary header

---

app/admin/diagnosed_need.rb
app/models/diagnosed_need.rb
db/migrate/20190129132339_add_archived_at_to_diagnosed_need.rb
db/schema.rb

This only adds the flag in database; it’s not properly used yet.

Allow archiving diagnosed needs

---

app/models/antenne.rb
app/models/user.rb
db/migrate/20190129132340_rename_antenne_users_count.rb
db/schema.rb

I forgot to rename it when renaming the association.

Fix Antenne::users counter cache column name

---

spec/mailers/previews/admin_mailer_preview.rb

Forgot the mail test template in #347

Fixup of_user scope removal

---

app/models/company.rb
app/models/concerns/created_within.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/institution.rb
app/models/match.rb
app/models/user.rb
app/views/diagnoses/index.html.haml
spec/models/diagnosed_need_spec.rb

Syntax consistency, cleanup, deduplication…

Small scopes refactor

---

app/admin/diagnosed_need.rb
app/admin/diagnosis.rb
app/controllers/diagnoses_controller.rb
app/helpers/admin_archivable.rb
app/models/concerns/archivable.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/user.rb
app/services/admin_mailers_service.rb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
config/locales/views/mailers/user_mailer.fr.yml
config/locales/views/needs.fr.yml
config/locales/views/stats.fr.yml
spec/controllers/diagnoses_controller_spec.rb
spec/fixtures/relay_statistic_csv_fixture.csv
spec/mailers/previews/admin_mailer_preview.rb
spec/models/concerns/archivable_spec.rb
spec/models/diagnosis_spec.rb

* Actually support the `archived_at` in DiagnosedNeed and do not report archived items as abandoned.
* Add UI in the admin to set/unset the archived flag
* DRY the Archivable behaviour with Diagnosis and DiagnosedNeed

Archivable DiagnosedNeeds

---

app/helpers/feedback_helper.rb

https://sentry.data.gouv.fr/betagouvfr/reso/issues/668467/

Prevent a crash when trying to display feedback from deleted experts

---

.haml-lint.yml
app/controllers/entreprise_controller.rb
app/views/entreprise/index.haml
app/views/layouts/empty.html.haml
config/routes.rb

Just embed the strikingly pages for now.

Add embedded iframe landing pages

---

app/admin/solicitation.rb
app/controllers/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/views/mailers/admin_mailer/solicitation.haml
app/views/solicitations/_tracking.haml
config/locales/active_record.fr.yml
config/locales/views/solicitations.fr.yml
spec/mailers/previews/admin_mailer_preview.rb

* Better columns and filter in the admin page
* Links and descriptions in the email
* Links to relevant google ad console

Improve solicitations UI in email and in admin

---

README.md
lib/tasks/import_dump.rake

dump, import and anonymize production data

Add an “import_dump” rake task

---

config/locales/views/solicitations.fr.yml

Adjust text and description in main form

---

app/assets/stylesheets/solicitations/index.sass
app/views/landing/landing.haml

* Make it not look like complete garbage on IE
* Add a marianne logo in the navbar

Tweaks for the landing pages

---

app/views/devise/mailer/_emails_footer.haml

https://sentry.data.gouv.fr/betagouvfr/reso/issues/670742/

Fix a_propos url in team

---

app/views/devise/mailer/_emails_footer.haml

https://sentry.data.gouv.fr/betagouvfr/reso/issues/670763/

Fix team link in email footer

---

app/controllers/landing_controller.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/views/solicitations/_tracking.haml
config/locales/active_record.fr.yml

We don’t actually use pk_source, pk_content and pk_medium.

Fix how we use pk_ matomo parameters

---

app/views/solicitations/index.haml

Fix missing element ID in solicitation form

---

app/views/layouts/_head.html.haml
app/views/layouts/empty.html.haml
app/views/layouts/solicitations.html.haml
app/views/stats/show.haml

This fixes Highcharts not being properly loaded in /stats when coming from /
https://sentry.data.gouv.fr/betagouvfr/reso/issues/674094/

Fix turbolinks params in js include tags

---

app/admin/diagnosed_need.rb
app/admin/diagnosis.rb
app/controllers/diagnoses_controller.rb
app/models/concerns/archivable.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/user.rb
app/services/admin_mailers_service.rb
config/locales/active_admin.fr.yml
spec/controllers/diagnoses_controller_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/models/concerns/archivable_spec.rb

* Replace `:archived` and `:not_archived` with `:archived(bool)`
* Use a filter instead of scopes in admin

Refactor archivable

---

app/admin/diagnosed_need.rb
app/admin/diagnosis.rb
app/admin/layout_hacks.rb
app/mailers/expert_mailer.rb
app/models/diagnosed_need.rb
app/models/match.rb
app/services/admin_mailers_service.rb
app/services/expert_reminder_service.rb
app/views/mailers/admin_mailer/weekly_statistics.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
config/i18n-tasks.yml
config/locales/active_admin.fr.yml
config/locales/views/mailers/admin_mailer.fr.yml
config/locales/views/mailers/expert_mailer.fr.yml
spec/mailers/admin_mailer_spec.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/models/match_spec.rb
spec/services/admin_mailers_service_spec.rb
spec/services/expert_reminder_service_spec.rb
spec/views/mailers/admin_mailer/weekly_statistics.html.haml_spec.rb

* Simplify scopes in diagnosed_need, refactor using by_status
* Use it in activeadmin
* Use it in mailers
* Hack activeadmin scopes to support html tooltips

Diagnosed needs scopes

---

app/admin/question.rb
app/models/category.rb
app/models/diagnosed_need.rb
app/models/question.rb
app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/needs/show.haml
db/migrate/20190325142929_add_archived_at_to_question.rb
db/schema.rb
lib/tasks/readd_archived_questions_from_orphans.rake
spec/models/diagnosed_need_spec.rb

* Add `archived_at` to allow archived questions and avoid orphaned diagnosed_needs
* Add a script to recreate archived questions from orphaned diagnosed_needs
This is preliminary work for the “relays” and “admin team” refactor.

Cleanup Questions

---

app/models/diagnosed_need.rb
app/models/question.rb
app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/services/relay_service/csv_generator.rb
app/services/user_daily_change_update_mailer_service.rb
app/views/diagnoses/step2.html.haml
app/views/diagnoses/step4.html.haml
app/views/mailers/expert_mailer/_reminders_match.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/user_mailer/match_feedback.html.haml
app/views/needs/_diagnoses_list.haml
app/views/needs/_need_header.haml
config/locales/active_record.fr.yml
db/migrate/20190326162230_remove_question_label_from_diagnosed_need.rb
db/migrate/20190326163032_prevent_null_categories.rb
db/schema.rb
spec/factories/diagnosed_needs.rb
spec/services/relay_service/csv_generator_spec.rb
spec/services/user_daily_change_update_mailer_service_spec.rb
spec/views/mailers/expert_mailer/notify_company_needs.html.haml_spec.rb

Use the fact that diagnosis.question is never null throughout the app.

Remove Diagnosis.question_label and DRY

---

app/views/devise/confirmations/new.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml

See https://github.com/plataformatec/devise/blob/master/app/helpers/devise_helper.rb

Stop using devise_error_messages!

---

app/views/diagnoses/step2.html.haml

Namely, the Support theme would be empty.

Do not display empty Themes when selecting Subjects

---

app/admin/match.rb
app/models/match.rb
app/models/user.rb
lib/tasks/convert_relays_matches_to_support_matches.rake
spec/models/user_spec.rb

Convert existing relay matches to support matches

---

app/admin/diagnosis.rb
app/admin/need.rb
app/admin/subject.rb
app/helpers/admin_archivable.rb
app/views/diagnoses/_in_progress_diagnoses_list.haml
app/views/needs/_diagnoses_list.haml
config/locales/active_admin.fr.yml
config/locales/common.fr.yml

Make the button fully clickable 🤷‍♂️

Fix Archive Diagnosis button

---

app/admin/company.rb
app/admin/dashboard.rb
app/admin/delayed_job.rb
app/admin/diagnosis.rb
app/admin/expert.rb
app/admin/landing.rb
app/admin/skill.rb
app/admin/solicitation.rb
app/admin/subject.rb
app/admin/territory.rb
app/admin/theme.rb
app/admin/user.rb
config/initializers/active_admin.rb
spec/features/admin_controller_feature_spec.rb
spec/features/application_controller_feature_spec.rb

Reorder admin menu items

---

app/assets/stylesheets/solicitations/index.sass
app/views/solicitations/index.haml

* Maybe just remove the pictures

Add a “testimonials” section on /

---

app/assets/stylesheets/solicitations/index.sass
app/views/solicitations/index.haml

Use fancy quotes for testimonies

---

Gemfile
Gemfile.lock
app/assets/stylesheets/diagnoses.sass
app/controllers/diagnoses_controller.rb
app/views/diagnoses/_in_progress_diagnoses_list.haml
app/views/diagnoses/archives.haml
app/views/diagnoses/index.haml
app/views/needs/_diagnoses_list.haml
config/locales/views/diagnoses.fr.yml
config/routes.rb
spec/controllers/diagnoses_controller_spec.rb
spec/factories/diagnoses.rb

- Ajoute une page pour voir les analyses archivées
- Change l'icône "Archiver" pour quelque chose de moins destructif
---

Ajoute une page pour voir les Analyses archivées

---

app/views/diagnoses/index.haml

Diagnoses: remove superfluous CSS class

---

app/models/match.rb
config/locales/models.fr.yml
spec/models/match_spec.rb
spec/models/need_spec.rb
spec/models/use_cases/update_expert_viewed_page_at_spec.rb

Some duplicate matches where inserted when creating the Place des Entreprises team. (#438)

Prevent dual matches for the same need to the same expert

---

Gemfile
Gemfile.lock
config/application.rb

Avant : <img width="112" alt="Capture d’écran 2019-05-09 à 11 31 05" src="https://user-images.githubusercontent.com/139391/57443275-f893e100-724d-11e9-9101-477f78e39e2c.png">,  après : <img width="105" alt="image" src="https://user-images.githubusercontent.com/139391/57443262-f16cd300-724d-11e9-961a-b686d004eb94.png">

Use rails-i18n (for proper fr pluralization rules)

---

app/controllers/diagnoses_controller.rb
app/views/diagnoses/_in_progress_diagnoses_list.haml
app/views/needs/_archive_action.haml
app/views/needs/_diagnoses_list.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/diagnoses_controller_spec.rb

And make sur the “Archive” button title changes when the diagnosis is archived.

Allow un-archiving diagnoses

---

app/controllers/stats_controller.rb
app/services/stats/solicitations_stats.rb
app/views/stats/show.haml
config/locales/views.fr.yml

Add solicitations stats

---

app/helpers/status_helper.rb

Use form buttons rather than links for the match action buttons

---

app/mailers/user_mailer.rb
app/models/diagnosis.rb
app/models/need.rb
spec/models/need_spec.rb

Once upon a time, there used to be relays in there too. But not anymore.

Remove Need#contacted_persons

---

app/controllers/needs_controller.rb
app/models/diagnosis.rb
app/models/match.rb
app/models/need.rb
app/models/user.rb
app/views/diagnoses/_diagnoses.haml
app/views/diagnoses/_diagnosis.haml
app/views/needs/_received_needs.haml
app/views/needs/archives.haml
app/views/needs/index.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/needs_controller_spec.rb
spec/factories/matches.rb

Améliorations de la “boite de réception” des demandes reçues:
* catégories “en attente de réponse”, “pris en charge (par d’autre)”
* mise à part des demandes archivées (clôturées, refusées)

Add needs/archive

---

app/admin/landing.rb
app/models/landing.rb
app/views/landings/index.haml
app/views/landings/show.haml
config/locales/models.fr.yml

* Add custom meta attributes support for landing pages
* Tweak stats alignment

Landing pages tweaks

---

app/views/landings/show.haml

Fix solicitation form feedback message not appearing after submission

---

.circleci/config.yml
app/views/landings/show.haml
app/views/solicitations/_form.haml
app/views/solicitations/_thank_you.haml
spec/controllers/landings_controller_spec.rb
spec/factories/landings.rb
spec/features/new_solicitation_feature_spec.rb
spec/rails_helper.rb

Add solicitation form feature tests

---

app/controllers/landings_controller.rb
app/controllers/stats_controller.rb
app/services/stats/stats.rb
app/views/stats/show.haml

And pass the params in a slightly less broken way.

Tweak the stats territory and institution form

---

app/assets/stylesheets/solicitations/index.sass
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_landing.haml
app/views/landings/_steps.haml
app/views/landings/index.haml
app/views/landings/show.haml
config/locales/views.fr.yml

* Add back the descriptions in the landing “vignettes”
* Cleanup the css a bit
* Clarify labels

More landing page tweaks

---

app/controllers/landings_controller.rb
app/models/landing_topic.rb
app/services/stats/stats.rb
app/views/landings/_hero.haml
app/views/landings/_institutions.haml
app/views/landings/_landing_details.haml
app/views/landings/_landings.haml
app/views/landings/_testimonials.haml
app/views/landings/index.haml
app/views/landings/show.haml
app/views/solicitations/_form.haml
app/views/stats/_ministats.haml
app/views/stats/_stats_chart.haml
app/views/stats/_stats_charts.haml
app/views/stats/_stats_params.haml
app/views/stats/show.haml
config/locales/views.fr.yml

Cleanup landing pages and stats
* add caching wherever possible
* dry and simplify partials
* make sure landing pages without topics render correctly

Partials and cache

---

app/views/landings/_landing_details.haml
app/views/landings/show.haml
app/views/solicitations/_form.haml
config/locales/views.fr.yml
spec/features/landing_page_feature_spec.rb

Fix landing pages redirection and meta

---

config/locales/views.fr.yml
spec/features/new_solicitation_feature_spec.rb

besoin en demande
sous 72 heures

Modifications de textes

---

app/views/landings/_landing_details.haml

Cleanup (remove useless comment)

---

app/services/expert_reminder_service.rb
spec/services/expert_reminder_service_spec.rb

We want to display reminders in the web UI, not simply send emails once a week: let’s make this algorithm reusable.

Refactor reminders service

---

app/assets/stylesheets/solicitations/index.sass

Display the environment ribbon in all the pages

---

app/controllers/needs_controller.rb
app/models/concerns/involvement_concern.rb
app/models/expert.rb
app/models/user.rb
spec/controllers/needs_controller_spec.rb
spec/models/concerns/involvement_concern_spec.rb

Preliminary work for the “reminders” page.

Move the needs_controller “inbox” queries to an Involvement concern

---

app/controllers/stats_controller.rb
app/views/diagnoses/_diagnosis.haml
app/views/layouts/solicitations/_navbar.haml
app/views/mailers/expert_mailer/_remind_received_needs.html.haml
app/views/needs/show.haml
app/views/stats/_stats_chart.haml
app/views/stats/_stats_params.haml
app/views/stats/_stats_table.haml
config/locales/fr.yml

Various fixes and improvements:
* codestyle for `render` calls
* date formats
* split “connexion” menu
* fix stats after #501

Cleanup and tweaks

---

app/admin/need.rb
app/models/need.rb
app/services/admin_mailers_service.rb
app/views/diagnoses/_diagnosis.haml
app/views/mailers/admin_mailer/weekly_statistics.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/services/admin_mailers_service_spec.rb
spec/views/mailers/admin_mailer/weekly_statistics.html.haml_spec.rb

Add a “last activity” label for abandoned needs

---

app/assets/javascripts/application.js
app/assets/stylesheets/diagnoses.sass
app/controllers/needs_controller.rb
app/controllers/reminders_controller.rb
app/models/territory.rb
app/views/diagnoses/_archive_action.haml
app/views/diagnoses/_diagnoses.haml
app/views/diagnoses/_diagnosis.haml
app/views/layouts/_navbar.html.haml
app/views/needs/_received_needs.haml
app/views/needs/show.haml
app/views/person/_person.haml
app/views/reminders/_expert.haml
app/views/reminders/index.haml
app/views/reminders/show.haml
config/locales/views.fr.yml
config/routes.rb

List the experts with late matches.
* filter by territory
* display received/accepted needs and abandoned needs
* Also: add  an experimental `regions` scope for Territories.

Add a /relances tab

---

app/models/diagnosis.rb
app/views/needs/show.haml

instead of the date the visit happened on.

Display the diagnosis completion date as the discussion start date

---

app/admin/match.rb
app/models/match.rb
spec/models/match_spec.rb

Also, copy the new expert info when updated.

Allow changing experts in /admin/matches/

---

app/admin/match.rb

We need to be able to change it as much as the expert themselves.

Allow changing Match.skill in the UI

---

app/admin/match.rb
app/admin/need.rb
app/admin/skill.rb
app/admin/subject.rb
app/admin/theme.rb
app/helpers/admin_helper.rb
app/models/expert.rb
app/models/expert_skill.rb
app/models/match.rb
app/models/need.rb
app/models/skill.rb
app/models/subject.rb
app/models/theme.rb

Declare the `through` associations and add filters and links in admin.

Allow filtering matches and needs by skill/subject/theme

---

spec/models/diagnosis_spec.rb

We now properly validate visitee is present in step > 4.

Remove a #TODO comment after #522

---

app/models/antenne.rb
app/models/contact.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/expert_skill.rb
app/models/facility.rb
app/models/feedback.rb
app/models/landing_topic.rb
app/models/match.rb
app/models/need.rb
app/models/search.rb
app/models/user.rb
db/migrate/20190809123350_add_foreign_keys.rb
db/migrate/20190809123750_use_bigints.rb
db/migrate/20190809124307_make_references_nonnulls.rb
db/schema.rb
spec/factories/diagnoses.rb
spec/models/facility_spec.rb

- make sure references are always foreign keys
- use `null: false` when relevant
- change a stray integer column to bigint

Improve model references in DB schema

---

app/views/companies/_search_form.haml
app/views/diagnoses/step4.html.haml
app/views/needs/_feedback_form.haml
app/views/reminders/index.haml
app/views/stats/_stats_params.haml
app/views/user_impersonate/_header.html.haml

Use “form_with” :)
Yay rails 5.1 😁

Slightly cleanup and modernize

---

.haml-lint.yml
app/assets/stylesheets/layout.sass
app/assets/stylesheets/semantic-ui_extensions.sass
app/views/layouts/_flashes.html.haml
app/views/layouts/_navbar.html.haml
app/views/users/_team.html.haml
app/views/users/_user.json.jbuilder
app/views/users/show.html.haml
app/views/users/show.json.jbuilder

Remove useless rules and partials, and adjust space at the top of the layout.

Partials and sass cleanup

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
app/views/layouts/solicitations/_navbar.haml
app/views/users/show.html.haml
config/routes.rb
spec/features/users/registrations_controller_spec.rb

This is refactor and partial revert of #550

Properly disable new account creation, but leave account edition on

---

config/locales/models.fr.yml
vendor/assets/stylesheets/active_admin.scss

Small fixes done in passing for #555

Tweak admin UI

---

app/views/mailers/shared/_footer.haml

Fix url email footer logo

---

app/admin/user.rb
app/models/user.rb
config/locales/devise.fr.yml
config/locales/models.fr.yml
db/migrate/20191017142119_add_deactivated_at_to_devise.rb
db/schema.rb
spec/features/signin_spec.rb

We’re reworking the whole user management process (see #559)

User cleanup: support for deactivation

---

app/admin/user.rb
app/controllers/users/invitations_controller.rb
app/mailers/admin_mailer.rb
app/mailers/user_mailer.rb
app/models/expert.rb
app/models/user.rb
app/views/mailers/admin_mailer/new_user_approved_notification.html.haml
app/views/mailers/user_mailer/account_approved.html.haml
config/locales/devise.fr.yml
config/locales/models.fr.yml
config/locales/views.fr.yml
db/migrate/20191018143155_remove_is_approved_from_user.rb
db/schema.rb
lib/tasks/import_dump.rake
spec/admin/users_controller_admin_spec.rb
spec/factories/users.rb
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/user_mailer_preview.rb
spec/mailers/user_mailer_spec.rb
spec/models/user_spec.rb

User cleanup: Remove user#is_approved

---

lib/tasks/import_dump.rake

* Check the postgres user from database.yml in rake import_dump
* Make sure the local fake admin account is active :)

Check the postgres user from database.yml in rake import_dump

---

app/admin/user.rb

Fix csv download in /admin/users

---

app/admin/feedback.rb
app/models/feedback.rb
config/locales/models.fr.yml
db/migrate/20191025150441_remove_feedback_match.rb
db/schema.rb

Feedback have a need and an optional user since #545, I never updated the admin panel. 🙈

Fix crash in /admin/feedback

---

lib/tasks/import_dump.rake

Territories, themes, institutions names… can be kept visible.

Do not anonymize all data when importing the db

---

app/admin/solicitation.rb

Properly export all attributes in solicitations CSV

---

app/views/about/top_5.haml
config/locales/views.fr.yml

Ajustements sur la page `/top_5` 💁

Top 5 tweaks

---

.github/workflows/rebase.yml

https://github.com/marketplace/actions/automatic-rebase

Add “automatic rebase” github action

---

.gitignore
README.md
app/models/feedback.rb
app/models/solicitation.rb
app/models/user.rb
db/schema.rb
lib/tasks/auto_annotate_models.rake
lib/tasks/import_dump.rake
lib/tasks/lint.rake
lib/tasks/optimize-image-sizes.rake

Cleanup and tooling

---

config/locales/views.fr.yml

update text on homepage

---

app/models/expert.rb
app/models/user.rb
config/initializers/devise.rb
config/locales/models.fr.yml
db/migrate/20191114104842_remove_user_confirmable.rb
db/schema.rb
spec/factories/users.rb

Followup from #569
Also, cleanup work before #638

Remove Devise::Confirmable columns from Users

---

app/views/devise/mailer/invitation_instructions.html.haml
app/views/devise/mailer/reset_password_instructions.html.haml
config/locales/devise.fr.yml
config/locales/fr.yml
spec/mailers/previews/devise_mailer_preview.rb

Tweaks to Devise invitation and reset_password emails

---

lib/tasks/create_experts_matching_users.rake

Make sure to load :environment in the create_matching_users rake task

---

.github/workflows/rebase.yml

It should no longer complain anymore when it doesn’t run.

Readd the /rebase github action

---

app/admin/expert.rb
app/models/expert.rb
config/locales/models.fr.yml
lib/tasks/create_experts_matching_users.rake
spec/factories/experts.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb
spec/services/admin_mailers_service_spec.rb

:warning: Only merge once #651 is merged and the task is run in production
refs #638

Validate that experts always have users

---

app/admin/company.rb
app/admin/facility.rb
app/models/company.rb
app/models/concerns/effectif.rb
app/models/facility.rb
app/models/use_cases/search_facility.rb
config/locales/codes_effectif.fr.yml
config/locales/models.fr.yml
db/migrate/20191121101634_add_code_effectif.rb
db/schema.rb
spec/models/concerns/effectif_spec.rb
spec/models/use_cases/search_facility_spec.rb

* Parse it from the API-entreprises response
* Display it and filter it in /admin pages
* Include nice full-text description
* Also improve the “categorie juridique” description while we’re at it.
first step for #580.

Add “code effectif” to Company and Facility

---

app/models/expert.rb
app/models/expert_subject.rb
app/models/institution.rb
app/models/institution_subject.rb
app/models/match.rb
app/models/skill.rb
app/models/subject.rb
config/initializers/inflections.rb
db/migrate/20191106134931_create_institutions_subjects.rb
db/migrate/20191106135049_create_experts_subjects.rb
db/migrate/20191114145320_add_subject_to_matches.rb
db/schema.rb
lib/tasks/migrate_skills_to_institutions.rake
spec/factories/expert_subjects.rb
spec/factories/institutions_subjects.rb
spec/factories/matches.rb
spec/factories/subjects.rb
spec/lib/tasks/migrate_skills_to_institutions_task_spec.rb
spec/models/expert_subject_spec.rb
spec/models/institution_subject_spec.rb

Add models 

---

app/models/antenne.rb
spec/models/antenne_spec.rb

Fixup after #566, I had this commit waiting for a while :shrug:

Add missing test for Antenne#by_antenne_and_institution_names

---

db/seeds.rb
lib/tasks/import_dump.rake

create local admin user

---

app/admin/expert.rb
app/admin/institution.rb
app/admin/match.rb
app/admin/need.rb
app/controllers/diagnoses_controller.rb
app/controllers/needs_controller.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/expert_subject.rb
app/models/institution.rb
app/models/institution_subject.rb
app/models/match.rb
app/models/need.rb
app/models/subject.rb
app/models/user.rb
app/views/diagnoses/_expert_skill_checkboxes.html.haml
app/views/diagnoses/step4.html.haml
app/views/needs/_additional_experts.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/controllers/diagnoses_controller_spec.rb
spec/models/diagnosis_spec.rb
spec/models/expert_spec.rb
spec/models/match_spec.rb

Change matching algorithm to use the institution/experts/subjects

---

app/admin/expert.rb
app/assets/stylesheets/experts.sass
app/controllers/experts_controller.rb
app/models/expert.rb
app/views/experts/edit.haml
app/views/users/_team.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb

create page for experts to edit his subjects

---

app/assets/javascripts/needs.js
app/views/devise/invitations/new.html.haml

[invitations] Allow full text search for antenne names

---

lib/tasks/fetch_companies_effectifs.rake

Add a script to batch-fetch missing “code_effectif“

---

app/views/layouts/solicitations/_footer.haml
config/locales/about/cgu.fr.yml
config/locales/views.fr.yml
spec/fixtures/relay_statistic_csv_fixture.csv
spec/models/user_spec.rb

Renomme DINSIC en DINUM

---

app/assets/javascripts/solicitations.js
app/assets/javascripts/stats_charts.js
app/assets/stylesheets/solicitations/index.sass
app/services/stats/companies_stats.rb
app/services/stats/source_stats.rb
app/services/stats/stats.rb
app/views/stats/_stats_chart.haml
app/views/stats/_stats_charts.haml
config/locales/codes_effectif.fr.yml
config/locales/views.fr.yml

* Ajout d’un graph comparant les sollicitation directes aux visites de conseillers (#632)
* Groupement des entreprises aidées par taille (#580)

Stats improvements

---

app/admin/subject.rb

fixes crash on page /admin/subjects/:id

---

app/models/match.rb
db/migrate/20191212094740_remove_skill_tables.rb
db/schema.rb

remove tables skills and expert_skills

---

app/admin/user.rb
app/models/contact.rb
app/models/diagnosis.rb
app/models/user.rb
app/validators/contact_validator.rb
config/locales/models.fr.yml
config/routes.rb
spec/models/diagnosis_spec.rb
spec/models/user_spec.rb

(somewhat related) cleanup done in passing for #638. I’m mostly getting these commits out of the way for the actual PR :)

Miscellaneous cleanup

---

.rubocop.yml
app/assets/stylesheets/experts.sass
app/models/expert_subject.rb
app/views/diagnoses/step4.html.haml
app/views/experts/edit.haml
config/locales/views.fr.yml
db/migrate/20191209162732_add_role_to_experts_subjects.rb
db/schema.rb
spec/views/diagnoses/step4.html.haml_spec.rb

Permettre aux référents d’indiquer s’ils sont “spécialistes” d’un sujet ou “suppléants”

---

app/controllers/concerns/flash_to_review_subjects.rb
app/controllers/diagnoses_controller.rb
app/controllers/experts_controller.rb
app/controllers/needs_controller.rb
app/controllers/users_controller.rb
app/models/expert.rb
app/views/layouts/_flashes.html.haml
config/locales/views.fr.yml
db/migrate/20191212153012_add_subjects_reviewed_at_to_expert.rb
db/schema.rb
spec/models/expert_spec.rb

:warning: Merge #704 before
refs #638

Display an alert to incite users users to edit their subjects

---

app/models/expert_subject.rb
db/schema.rb

We lost some changes while tweaking a migration

Synchronize schema.rb and model annotation

---

app/controllers/feedbacks_controller.rb
app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/feedback.rb
app/models/user.rb
app/views/mailers/user_mailer/confirm_notifications_sent.html.haml
app/views/mailers/user_mailer/match_feedback.html.haml
app/views/users/_team.html.haml
config/locales/views.fr.yml
spec/mailers/previews/user_mailer_preview.rb
spec/models/user_spec.rb

⚠️ merge #713 first
* Also: change the button text to “Répondre”
refs #638

Do not cc everyone in UserMailer#match_feedback

---

app/views/needs/_visit_summary.haml
config/locales/views.fr.yml

display created_at date instead of visit date

---

app/admin/match.rb

Add commune (insee_code) in /admin/matches index and csv

---

app/controllers/experts_controller.rb
app/models/institution_subject.rb
app/views/experts/edit.haml

We should be using interview ordering everywhere.

Fix subjects ordering in /experts/:id/edit

---

app/admin/expert.rb
app/admin/feedback.rb
app/admin/user.rb
config/locales/models.fr.yml

Also add admin_links from experts and users to their feedbacks and fix related i18n.
fixes #729

Allow searching feedbacks by _advisor_ author (user, not expert)

---

app/assets/stylesheets/layout.sass
app/assets/stylesheets/semantic-ui_extensions.sass
app/assets/stylesheets/solicitations/index.sass
app/views/layouts/_navbar.html.haml

fixes #731 (both in app and on landing page)

Make navbar responsive

---

app/helpers/status_helper.rb
app/views/diagnoses/_archive_action.haml
app/views/diagnoses/_diagnosis.haml
app/views/matches/_match.haml
app/views/needs/_additional_experts.haml
app/views/needs/_feedback_form.haml

buttons should be solid, labels should be outlined. fixes #589
---
Je suis dubitatif, mais au moins c’est cohérent sur les différentes pages.

Invert labels and buttons styles

---

app/controllers/matches_controller.rb
app/controllers/solicitations_controller.rb
app/mailers/company_mailer.rb
app/views/mailers/company_mailer/confirmation_solicitation.html.haml
app/views/mailers/company_mailer/taking_care_by_expert.html.haml
app/views/mailers/company_mailer/taking_care_by_support.html.haml
config/locales/views.fr.yml
spec/factories/needs.rb
spec/factories/solicitations.rb
spec/mailers/company_mailer_spec.rb
spec/mailers/previews/company_mailer_preview.rb

Mails aux chefs d’entreprises

---

app/views/mailers/expert_mailer/_remind_received_needs.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
config/locales/views.fr.yml

Mail E - Relance hebdomadaire du référent

---

app/views/layouts/_flashes.html.haml

change flash notice color to green

---

spec/mailers/user_mailer_spec.rb

Properly use shared examples for emails. :)

update test UserMailer#update_match_notify

---

app/controllers/concerns/flash_to_review_subjects.rb

following #715, related to #735. We’ll see after #747.

Re-Disable the flash to review subjects for now

---

app/models/need.rb
app/views/reminders/_expert_contents.haml
config/locales/views.fr.yml

cf https://github.com/betagouv/place-des-entreprises/issues/599#issuecomment-568499217
This change adds a new label rather than changing the meaning of existing scopes.

Fix an inconsistency in /relances

---

app/models/diagnosis.rb
spec/models/diagnosis_spec.rb

Do not crash when sending reset emails

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
spec/models/user_spec.rb

Show the users needing to be invited rather than the users not invited.

Improve the scopes in /admin/users

---

app/views/companies/search.haml

fixes PLACE-DES-ENTREPRISES-3S PLACE-DES-ENTREPRISES-3X

Workaround a rare crash in companies#search

---

app/views/feedbacks/_feedback.haml

following #375; fixes PLACE-DES-ENTREPRISES-4H.

Fix a crash when displaying other users feedback

---

app/admin/solicitation.rb
app/controllers/companies_controller.rb
app/models/facility.rb
app/views/mailers/admin_mailer/solicitation.haml
config/locales/models.fr.yml

Add SIRET links from admin/solicitations and emails to the company pages

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/concerns/flash_to_review_subjects.rb
app/models/user.rb
config/locales/models.fr.yml
db/migrate/20200107154211_add_flags_to_users.rb
db/schema.rb

Add per-user flags and “can_view_review_subjects_flash”

---

app/assets/javascripts/application/semantic-ui.js
app/assets/stylesheets/application/experts.sass
app/assets/stylesheets/application/semantic-ui_extensions.sass
app/controllers/experts_controller.rb
app/views/experts/edit.haml
app/views/feedbacks/_feedback.haml
app/views/matches/_match.haml
app/views/needs/_need_content.haml
config/locales/fr.yml
config/locales/views.fr.yml

* Only mark as reviewed when the form is sent
* Tweak Specialist/fallback help text.
* Change the form button from “update” to “confirm”.
refs #766

Tweak experts skill edit page

---

app/views/experts/edit.haml
config/locales/views.fr.yml

Correction du texte de l’aide dans la revue des compétences

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
db/migrate/20200114104543_make_user_antenne_nonnull.rb
db/schema.rb

C’est déjà le cas de fait dans les données et dans tous les scénarios, en principe.

Changement de User#antenne en non-optionnel

---

app/admin/antenne.rb
app/admin/company.rb
app/admin/expert.rb
app/admin/facility.rb
app/admin/helpers/admin_link_to.rb
app/admin/institution.rb
app/admin/territory.rb
app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
spec/models/user_spec.rb

* Corrections et améliorations pour les flags dans user
* Retrait de l‘affichage de l’activité s’il n’y a rien à montrer
* Retrait de l’option inutilisée “autolink_to_antenne”

Ajustements sur /admin/user

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml

Add a “without_team” scope to /admin/users

---

app/assets/stylesheets/pages.sass
app/views/landing_topics/_exemple_topics.haml
app/views/landings/_institutions.haml
app/views/landings/_landing_details.haml
app/views/landings/index.haml
app/views/landings/show.haml
config/locales/views.fr.yml
spec/features/landing_page_feature_spec.rb

Ajustements sur la promesse sur la page d’accueil

---

app/services/stats/advisors_stats.rb
app/services/stats/base_stats.rb
app/services/stats/companies_stats.rb
app/services/stats/experts_stats.rb
app/services/stats/matches_stats.rb
app/services/stats/needs_stats.rb
app/services/stats/source_stats.rb

Avoid crashing if the passed IDs don’t exist. This is a bit overengineered :(
fixes PLACE-DES-ENTREPRISES-4N

Improve filter params in stats

---

app/admin/audited_audit.rb
app/admin/helpers/audited_description.rb
app/models/expert.rb

And fix the audit journal for deletion events (😅)
fixes PLACE-DES-ENTREPRISES-4P

Allow deleting expert teams again

---

app/views/diagnoses/_diagnosis.haml

Fix the diagnosis step not being correctly displayed

---

app/views/diagnoses/new.haml

improve ux for new diagnosis city search

---

app/controllers/diagnoses_controller.rb
app/services/api_adresse/query.rb

Prevent crashes when requesting invalid data to geo-adress

---

app/controllers/concerns/flash_to_review_subjects.rb

A line was lost during a rebase :(
PLACE-DES-ENTREPRISES-4T

Fix the “flash to review” alert

---

config/locales/views.fr.yml

Clarifier l’interface de début d’analyse manuelle

---

app/assets/stylesheets/application/experts.sass
app/assets/stylesheets/application/layout.sass
app/assets/stylesheets/application/semantic-ui_extensions.sass
app/controllers/experts_controller.rb
app/models/institution.rb
app/views/application/_flashes.html.haml
app/views/experts/edit.haml
app/views/layouts/application.html.haml

Preliminary work for #766
Visible changes:
* remove the top margin before the main section
* align the radio button with the checkbox label
* align the the textarea right margin within the container
* remove css rules \o/

Simplify experts css

---

lib/tasks/diagnoses_flag.rake

Fix method rename in #809 after #817

Fix diagnoses_flag task

---

app/views/needs/archives.haml
app/views/needs/archives_antenne.haml
app/views/needs/index.html.haml
app/views/needs/index_antenne.haml
config/locales/views.fr.yml

Fix the needs page wrongly displaying its empty state 

---

config/routes.rb

Sert les landing-pages uniquement sur /aide-entreprises/:slug

---

app/views/users/_team.html.haml

following #817
fixes PLACE-DES-ENTREPRISES-4V

Fix a stray “solo?” usage

---

app/assets/stylesheets/pages.sass
app/views/pages/_navbar.haml

Corrige aussi la taille du titre dans le footer pour iphone 5
close #820

corrige l'affichage du header sur mobile

---

app/admin/expert.rb
app/admin/user.rb
app/models/expert.rb
app/models/user.rb
app/views/users/show.html.haml
config/locales/models.fr.yml
lib/tasks/create_missing_personal_skillsets.rake
spec/factories/experts.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb

Create experts for all users

---

app/admin/subject.rb

fixes PLACE-DES-ENTREPRISES-51

Fix subjects csv download in admin

---

config/routes.rb

redirige les landings vers aide-entreprises avec les params

---

app/models/user.rb
spec/models/user_spec.rb

Automatically synchronize user attributes in personal skillsets

---

app/assets/stylesheets/application/diagnoses.sass
app/assets/stylesheets/application/experts.sass
app/assets/stylesheets/application/layout.sass
app/assets/stylesheets/application/semantic-ui_extensions.sass
app/models/expert.rb
app/models/expert_subject.rb
app/views/diagnoses/steps/_expert_subject_checkboxes.html.haml
app/views/diagnoses/steps/_header.haml
app/views/diagnoses/steps/selection.haml
config/locales/views.fr.yml

Redesign the selection step

---

app/models/feedback.rb
spec/models/feedback_spec.rb

Envoyer les mails de commentaires des besoins à tous les intervenants

---

app/helpers/mailto_helper.rb
app/mailers/application_mailer.rb
app/views/about/_contact_us.haml
app/views/mailers/_footer.haml
app/views/mailers/company_mailer/taking_care_by_expert.html.haml
app/views/mailers/company_mailer/taking_care_by_support.html.haml
app/views/needs/index.html.haml
config/initializers/devise.rb
config/locales/views.fr.yml

Use mail_to helper

---

app/models/feedback.rb
spec/models/feedback_spec.rb

N'envoie pas les emails à leur auteur

---

app/admin/expert.rb

Ajouter la description du sujet de l'institution à la modification d'un expert

---

app/admin/solicitation.rb

Ajoute la thématique et la provenance sur la page d'une sollicitation

---

app/assets/stylesheets/application/diagnoses.sass
app/views/needs/_feedback_form.haml
config/locales/views.fr.yml

Amélioration du texte sur la page d'une analyse

---

app/admin/expert.rb
app/admin/match.rb
app/models/match.rb
config/locales/models.fr.yml

Le code est pas hyper joli mais ça fonctionne 😅
closes #866

Ajoute le champs d'intervention au csv des mises en relation

---

app/controllers/solicitations_controller.rb
config/locales/views.fr.yml

On pourra peut-être améliorer le formulaire et ne pas mettre de JS du tout mais au moins c'est un premier pas
closes #862

Permet au formulaire de solicitation de fonctionner sans JS

---

app/admin/institution.rb
app/admin/solicitation.rb
app/assets/stylesheets/pages.sass
app/controllers/external_solicitations_controller.rb
app/models/institution.rb
app/models/solicitation.rb
app/views/external_solicitations/_thank_you.haml
app/views/external_solicitations/new.haml
app/views/layouts/external_solicitations.html.haml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20200309150119_add_partner_token_to_institution.rb
db/schema.rb

Ajoute un formulaire intégrable par les partenaires

---

Gemfile
Gemfile.lock
app/assets/stylesheets/mailers.sass

Add a dummy workaround rule at the top of mailers.sass

---

db/seeds.rb

Do not rely on first running import_dump :)
* db:seed can now be used on an empty DB (db:setup and db:reset work)
* db:seed is idempotent
* The app is usable after a db:setup
fixes #874

Make seeds.rb usable for initial setup

---

lib/tasks/import_dump.rake

* keep personal_skillsets with their users
* give cool names to teams
fixes #879
(also refactor the anonymize task)

Tweak imported data anonymization

---

app/admin/landing.rb
app/models/landing.rb
app/views/landing_topics/_example_topics.haml
config/locales/models.fr.yml
config/locales/views.fr.yml

and change placeholder for siret

Add possibility to change landing examples title

---

app/admin/landing.rb
app/controllers/landings_controller.rb
app/models/landing.rb
app/views/landing_topics/_example_topics.haml
app/views/landings/_form.haml
app/views/landings/_thank_you.haml
app/views/landings/show.haml
app/views/landings/solicitation.js.haml
config/locales/models.fr.yml
config/locales/views.fr.yml

Personnalisation du formulaire sur les landing pages

---

app/controllers/landings_controller.rb

refs #888
Metrics on Scalingo say we have ample room.

Decrease the landing pages cache duration

---

app/views/landings/_form.haml
app/views/landings/_thank_you.haml

Make sure custom html in landing pages is displayed in the form

---

app/admin/solicitation.rb
app/models/solicitation.rb
app/views/mailers/admin_mailer/solicitation.haml
config/locales/models.fr.yml
spec/mailers/previews/admin_mailer_preview.rb

refs #888 : make all details available in the index

Customize /admin/solicitations#show

---

app/admin/landing.rb
app/views/landing_topics/_landing_topics.html.haml
app/views/landings/_landings.haml
app/views/landings/show.haml
config/locales/views.fr.yml

Display landing topics in rows of 3

---

app/admin/landing.rb
app/assets/stylesheets/pages.sass
app/models/landing.rb
app/views/landings/_landing.haml
config/locales/models.fr.yml

Allow displaying a specific landing with emphasis on the home page

---

app/models/diagnosis.rb
app/models/user.rb
config/locales/models.fr.yml

Allow disabling UserMailer.confirm_notifications_sent per user

---

app/assets/stylesheets/application/solicitation.sass
app/controllers/solicitations_controller.rb
app/models/diagnosis.rb
app/models/solicitation.rb
app/policies/solicitation_policy.rb
app/views/application/_navbar.html.haml
app/views/landings/_form.haml
app/views/solicitations/_solicitations.haml
app/views/solicitations/canceled.html.haml
app/views/solicitations/index.html.haml
app/views/solicitations/processed.html.haml
app/views/solicitations/remove.js.haml
app/views/solicitations/show.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20200310154025_add_solicitation_to_diagnoses.rb
db/migrate/20200310165132_add_status_to_solicitation.rb
db/migrate/20200312145536_add_full_name_to_solicitation.rb
db/schema.rb
spec/features/new_solicitation_feature_spec.rb
spec/policies/solicitation_policy_spec.rb

Ajoute une page sollicitations et permet de changer leurs statut

---

app/admin/landing.rb
config/locales/views.fr.yml

Tweak page ordering in /admin/landings#edit

---

app/controllers/solicitations_controller.rb
app/models/solicitation.rb
config/routes.rb

Tweak solicitations

---

app/admin/solicitation.rb
app/controllers/landings_controller.rb

Fix solicitation full name

---

app/assets/stylesheets/pages.sass
app/views/landings/_landing.haml
app/views/landings/_landing_details.haml
app/views/landings/show.haml

Change the Call to Action buttons to point to the exemples

---

app/admin/solicitation.rb
app/models/solicitation.rb
config/locales/models.fr.yml
vendor/assets/stylesheets/active_admin.scss

Ajout des infos de status et de filtres par option, et de clôture en masse dans /admin/solicitations.
refs #888

Clôture en masse des solicitations

---

app/assets/stylesheets/pages.sass
app/views/landing_topics/_landing_topic.html.haml
app/views/landing_topics/_landing_topics.html.haml
app/views/landings/show.haml
config/locales/views.fr.yml

Ajustements sur les landing pages

---

app/controllers/companies_controller.rb
app/controllers/diagnoses/steps_controller.rb
app/controllers/diagnoses_controller.rb
app/models/diagnosis.rb
app/views/companies/_search_form.haml
app/views/companies/search.haml
app/views/companies/show.html.haml
app/views/diagnoses/new.haml
app/views/needs/_visit_summary.haml
app/views/solicitations/_solicitation.haml
app/views/solicitations/_solicitations_tabs.html.haml
app/views/solicitations/canceled.html.haml
app/views/solicitations/index.html.haml
app/views/solicitations/processed.html.haml
config/locales/views.fr.yml
config/routes.rb

Créer une analyse à partir d'une sollicitation

---

app/assets/stylesheets/pages.sass
app/controllers/landings_controller.rb
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_institutions.haml
app/views/landings/_landings.haml
app/views/landings/index.haml
app/views/landings/show.haml
app/views/stats/_ministats.haml

More landing pages tweaks

---

app/views/landings/_landing.haml
app/views/landings/show.haml

add form for newsletter COVID-19

---

app/assets/javascripts/shared/checkboxes_require_one.js

/o\ we’re a high-traffic site now
fixes PLACE-DES-ENTREPRISES-65

Make the solicitation form work with Chrome 49

---

app/admin/diagnosis.rb
app/admin/solicitation.rb
app/models/diagnosis.rb
app/models/solicitation.rb
lib/core_extensions/relation/human_count.rb

Display solicitations and diagnoses in admin

---

app/admin/solicitation.rb

Add selected_options to solicitations csv

---

app/admin/solicitation.rb
app/controllers/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/views/solicitations/_solicitation.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb

Principalement du nettoyage et un peu d’améliorations de performances sur /admin/solicitations
refs #601

Ajustements sur les statuts des sollicitations

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application/semantic-ui_extensions.sass
app/controllers/solicitations_controller.rb
app/views/kaminari/_first_page.html.haml
app/views/kaminari/_gap.html.haml
app/views/kaminari/_last_page.html.haml
app/views/kaminari/_next_page.html.haml
app/views/kaminari/_page.html.haml
app/views/kaminari/_paginator.html.haml
app/views/kaminari/_prev_page.html.haml
app/views/solicitations/_solicitations_tabs.html.haml
app/views/solicitations/canceled.html.haml
app/views/solicitations/index.html.haml
app/views/solicitations/processed.html.haml
config/initializers/kaminari_config.rb
config/locales/views.fr.yml
config/routes.rb

Pagination sur /sollicitations

---

app/assets/stylesheets/pages.sass
app/controllers/landings_controller.rb
app/models/solicitation.rb
app/services/match_mailer_service.rb
app/views/landing_topics/_landing_topics.html.haml
app/views/landings/_form.haml
app/views/landings/_thank_you.haml
app/views/landings/create_solicitation.js.haml
app/views/landings/show.haml
config/brakeman.ignore
config/locales/views.fr.yml
config/routes.rb
spec/factories/landing_options.rb
spec/factories/landings.rb
spec/factories/solicitations.rb
spec/models/solicitation_spec.rb

* Validations côté modèle
* Affichage des erreurs dans le formulaire à côté des valeurs erronées
* Gestion des vieux navigateurs / sans javascript à l’identique
* Nettoyage et refactor. A priori, on devrait pouvoir utiliser le même contrôleur pour le formulaire embarqué en iframe dorénavant.

Amélioration de la validation des solicitations

---

app/controllers/matches_controller.rb

We have users with IE11 on Windows 7 without javascript 🎉
PLACE-DES-ENTREPRISES-57

Make /matches#update work without js

---

app/views/landings/show.haml

Not for the form result, be it success or failure

Only cache landings#show if the action is actually 'show'

---

app/admin/solicitation.rb
config/locales/views.fr.yml

Permet d'ajouter des tags aux sollicitations en masse

---

app/assets/stylesheets/pages.sass
app/views/landings/index.haml

Partially revert "WIP: Remove redundant/useless parts of pages.sass (maybe?) c45ad6350c267ac5205832290212a29d5f27bfdf"

Readd missing css rules (Partially revert c45ad635)

---

app/admin/match.rb

Disable match.expert_subject in csv export

---

app/admin/landing.rb
app/assets/stylesheets/pages.sass
app/controllers/landings_controller.rb
app/models/landing.rb
app/models/solicitation.rb
app/views/landings/_show_landing.html.haml
app/views/landings/_show_solicitation_form.html.haml
app/views/landings/new_solicitation.html.haml
app/views/landings/show.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
spec/features/new_solicitation_feature_spec.rb
spec/models/solicitation_spec.rb

Déplace le formulaire des sollicitations sur une autre page

---

app/assets/javascripts/application/semantic-ui.js
app/models/diagnosis.rb
app/views/solicitations/_solicitation.haml
app/views/solicitations/_solicitation_actions.html.haml
app/views/solicitations/_solicitation_badges.html.haml
config/locales/views.fr.yml

Display diagnoses in solicitations

---

app/admin/landing.rb
app/models/institution.rb
app/models/landing_option.rb
app/models/subject.rb
app/models/theme.rb
config/locales/models.fr.yml
db/migrate/20200406072135_add_slugs_to_subjects_and_institutions.rb
db/migrate/20200406075437_add_preselection_to_landing_option.rb
db/schema.rb
spec/factories/landing_options.rb
spec/factories/landings.rb
spec/models/institution_spec.rb
spec/models/subject_spec.rb
spec/models/theme_spec.rb

Add landing options preselection (model and admin)

---

app/views/landing_topics/_landing_topic.html.haml

add event on landing option click for matomo

---

app/admin/landing.rb
app/models/landing_option.rb
app/views/landings/_show_solicitation_form.html.haml
config/locales/models.fr.yml
db/migrate/20200408095342_add_content_to_landing_options.rb
db/schema.rb

ajoute un titre et une description aux formulaire de sollicitation

---

app/admin/match.rb

add siret to matches csv export

---

app/admin/feedback.rb

add siret, institution and antenne to feedback csv

---

app/admin/landing.rb
app/models/landing.rb
app/views/landings/_show_landing_topics.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml

Ajoute un message en dessous des exemples d'une page thématique

---

app/models/badge.rb
app/models/solicitation.rb
spec/factories/badges.rb
spec/models/badge_spec.rb

Touch solicitations after a badge is added/removed/updated

---

app/views/landing_topics/_landing_topic.html.haml

Fix matomo events for landing topics

---

app/views/needs/_visit_summary.haml

cacher lien vers la sollicitation dans la fiche de la visite pour ceux qui n'y on pas accès

---

app/assets/stylesheets/pages.sass

fix up css glitch on mobile

---

lib/tasks/import_dump.rake

Don’t touch records when importing data from production

---

app/mailers/user_mailer.rb
app/models/feedback.rb
app/services/match_mailer_service.rb
spec/mailers/user_mailer_spec.rb

Ne pas tenter d’envoyer de mails aux utilisateurs supprimés

---

Gemfile
Gemfile.lock
app/views/feedbacks/_feedback.haml
app/views/mailers/admin_mailer/solicitation.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/user_mailer/match_feedback.html.haml
app/views/needs/_need_content.haml
app/views/needs/_visit_summary.haml
app/views/solicitations/_solicitation.haml

I’m a little worried about using an old gem with no update in six years (https://rubygems.org/gems/rails_autolink) but that beats coding it ourselves, and the maintainer is a core rails contributor.

Automatically create links for urls in user-created content

---

app/admin/feedback.rb

We’re lacking integration tests for the admin pages. I’ll file an issue.

Fix a crash in admin/feedbacks after #926

---

app/admin/expert.rb
app/admin/feedback.rb
app/mailers/user_mailer.rb
app/models/feedback.rb
app/policies/feedback_policy.rb
app/views/feedbacks/_feedback.haml
db/migrate/20200430082448_remove_expert_to_feedbacks.rb
db/schema.rb
spec/factories/feedbacks.rb
spec/mailers/user_mailer_spec.rb
spec/models/feedback_spec.rb
spec/policies/feedback_policy_spec.rb

closes #1023 
⚠️ merge #1038 first

retire la relation entre un commentaire et un expert

---

.circleci/config.yml
Gemfile
spec/rails_helper.rb

* debase should only be loaded in development and tests
* dotenv-rails should be loaded in development and in tests: this is a proper fix for #562

Fix Gemfile grouping

---

.rspec_parallel
Gemfile
Gemfile.lock
README.md
bin/parallel_rspec
bin/spring

wip:
setup:
* bundle
* rake parallel:create (to setup test databases)
usage: RAILS_ENV=test rake parallel:spec (without spring) bin/parallel_rspec spec (with spring)
timing on my slow macbook:
```
> rake spec
[…]
Finished in 55.08 seconds (files took 6.85 seconds to load)
> 
> RAILS_ENV=test rake parallel:spec
[…]
Took 47 seconds
```

Add parallel_spec

---

app/models/expert.rb

Remove Expert#has_many :feedbacks

---

app/views/needs/index.html.haml

affiche les liens vers les besoins archivés et de l'antenne dans tous les cas

---

app/assets/javascripts/application.js
app/assets/stylesheets/application/solicitation.sass
app/controllers/solicitations_controller.rb
app/models/solicitation.rb
app/views/solicitations/index.html.haml
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

permet de chercher des sollicitations par tags et landing_options

---

app/assets/stylesheets/application/solicitation.sass

fixup css glitch on solicitation search

---

app/helpers/solicitation_helper.rb
app/models/landing_option.rb
config/locales/models.fr.yml
db/migrate/20200514125019_remove_landing_option_title.rb
db/schema.rb
spec/factories/landing_options.rb

Fix missing landing_option titles in /sollicitation

---

spec/factories/institutions.rb

🤷 I don’t even remember when institutions had emails.

Remove long-unused factory trait Institution#with_email

---

app/models/expert.rb
app/models/user.rb
config/locales/models.fr.yml
db/migrate/20200513151028_add_deleted_at_to_experts.rb
db/schema.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb

permet le soft delete des experts

---

app/policies/diagnosis_policy.rb
spec/policies/diagnosis_policy_spec.rb

Allow users to access diagnoses received by the experts of their antenne

---

app/assets/stylesheets/application/solicitation.sass
app/views/solicitations/_solicitation.haml

Affiche aussi les informations d'une sollicitation en gras plutôt que les libellés
close #1076

affiche le logo du partenaire dans les sollicitations

---

app/admin/expert.rb
app/admin/user.rb
app/controllers/concerns/expert_subjects_modal.rb
app/controllers/experts_controller.rb
app/models/expert.rb
app/policies/expert_policy.rb
app/views/experts/_subjects_fields.html.haml
app/views/experts/subjects.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
db/migrate/20200525134347_add_flags_to_experts.rb
db/schema.rb
spec/policies/expert_policy_spec.rb

fixes #1077
Pour les flags, j’ai copié collé le fonctionnement de User. Il y a matière à simplification, surtout pour les pages admin. En fait, il faudrait utiliser une batch_action avec un menu, comme tu as fait pour les badges. Je le garde pour plus tard.

Add Expert#can_edit_own_subjects

---

app/models/solicitation.rb

permet de chercher des sollicitations par mots clés et campagnes

---

app/assets/stylesheets/pages/cgu.sass
app/controllers/about_controller.rb
app/views/about/cgu.haml
app/views/about/mentions_legales.html.haml
app/views/about/politique_de_confidentialite.html.haml
app/views/pages/_footer.haml
config/locales/about/cgu.fr.yml
config/locales/about/mentions_legales.fr.yml
config/locales/about/politique_de_condidentialite.fr.yml
config/locales/fr.yml
config/locales/views.fr.yml
config/routes.rb

Met à jour les conditions générales etc

---

app/admin/institution.rb
app/admin/landing.rb
app/admin/solicitation.rb
app/assets/stylesheets/pages.sass
app/controllers/external_solicitations_controller.rb
app/models/solicitation.rb
app/views/external_solicitations/new.haml
app/views/landings/_new_solicitation_form.html.haml
app/views/landings/new_solicitation.html.haml
config/locales/views.fr.yml

Utilise le même formulaire pour l'iframe et les landings

---

app/assets/stylesheets/application/diagnoses.sass
app/controllers/diagnoses_controller.rb
app/controllers/solicitations_controller.rb
app/models/solicitation.rb
app/views/companies/show.html.haml
app/views/diagnoses/_related_diagnoses.html.haml
app/views/diagnoses/new.haml
app/views/needs/_visit_summary.haml
config/locales/views.fr.yml
db/migrate/20200528090057_add_index_for_solicitation_email.rb
db/schema.rb

si c'est une analyse avec SIRET on affiche toutes les analyses qui sont deja en cours pour cette entreprise même si elles ne sont pas terminées et pour les analyses à partir de sollicitation sans siret on affiche les analyses liées au même email.
closes #1087

affiche les analyses deja en cours à la création d'une analyse

---

app/controllers/diagnoses/steps_controller.rb
spec/controllers/diagnoses/steps_controller_spec.rb

Assigner les analyses automatiques à l’utilisateur qui fait la mise en relation

---

app/views/solicitations/_solicitation_actions.html.haml
config/locales/views.fr.yml

Ajoute un bouton “analyse manuelle” en cas d’échec de l’analyse automatique

---

app/admin/landing.rb
app/controllers/sitemap_controller.rb
app/models/landing.rb
app/models/landing_option.rb
app/views/landings/_index_landing_card.html.haml
app/views/landings/new_solicitation.html.haml
app/views/sitemap/sitemap.xml.builder
config/routes.rb
public/robots.txt

* Includes landing pages and static pages with contents.
* Automatically refreshed once a day (and on deploy.)

Add a sitemap

---

app/views/admin/import.html.haml

Don’t include deleted users in sample csv for import

---

Gemfile
Gemfile.lock

pretty-prints “some_query.to_sql”

Pretty print SQL queries in development

---

app/admin/concerns/csv_exportable.rb
app/admin/match.rb
app/controllers/admin_controller.rb
app/jobs/csv_job.rb
app/mailers/admin_mailer.rb
app/services/csv_export/models/match.rb
app/services/csv_export_service.rb
app/views/mailers/admin_mailer/send_csv.html.haml
config/environments/development.rb
config/environments/production.rb
config/locales/views.fr.yml

Permet de télécharger le CSV des mises en relations sans timeout

---

app/controllers/concerns/geocoder_ip.rb
config/locales/views.fr.yml

fixup after #1125
* Display the alert for people _not_ in the region
* Only HDF, not IDF yet.

Fixup Geoip alert

---

app/admin/landing.rb
config/locales/models.fr.yml
config/locales/views.fr.yml

Petits ajustements en lien avec #1128, #1127.

Améliorations sur admin/landings

---

Gemfile.lock

Fixup timecop gem removal

---

app/views/landings/_new_solicitation_form.html.haml

Remove old hidden fields for partner_token and institution_slug

---

app/helpers/breadcrumbs_helper.rb
app/views/landings/new_solicitation.html.haml
app/views/landings/show.haml

fixup display of landings title

---

app/models/landing.rb

flags in json being "0" instead of false in not ideal.

Fix landing emphasis being cancelled all the time

---

app/admin/landing.rb
app/assets/stylesheets/application/solicitation.sass
app/mailers/expert_mailer.rb
app/models/landing.rb
app/views/landings/_new_solicitation_thank_you.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/expert_mailer_preview.rb

Ajuster le message de mise en relation après sollicitation ou widget

---

config/locales/views.fr.yml

Remove “guichet public” from the page title

---

config/environments/development.rb

Env.fetch raises an exception if the variable isn't found.

Fixup deployment after #1167

---

README.md
config/initializers/session_store.rb

Add a note in the README regarding HSTS, Rails and Scalingo

---

app/views/landings/new_solicitation.html.haml
app/views/pages/_newsletter.html.haml

Display the newsletter form in the solicitation confirmation view

---

app/controllers/solicitations_controller.rb

Display an error when updating a solicitation fails for some reason

---

config/locales/views.fr.yml

Tweak text in newsletter_subscription

---

app/assets/stylesheets/pages/stats.sass
app/services/stats/source_stats.rb
app/views/stats/_stats_chart.haml
app/views/stats/show.haml
config/locales/views.fr.yml

The google console complains about smallish issues in the /stats page; it's due for a redesign eventually, but let's fix the easy ones.

Fix stats page quirks for mobile

---

app/views/landings/_show_landing_topics.html.haml

Fix html escaping for message_under_landing_topics

---

app/admin/expert.rb
app/admin/institution.rb
app/models/expert.rb
app/models/expert_subject.rb
app/models/institution.rb
app/models/institution_subject.rb
app/models/theme.rb

* In /admin/institutions and /admin/experts
* tables rather than lists of text
* ordered selects
* indicate subjects that are archived
* In mon_comptes/domaines
* Do not show archived subjects

Amélioration de l'affichage des sujets côté admin

---

app/admin/match.rb
app/helpers/person_helper.rb
app/models/contact.rb
app/models/expert.rb
app/models/match.rb
app/models/user.rb
app/views/diagnoses/_related_diagnoses.html.haml
app/views/mailers/admin_mailer/weekly_statistics.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/matches/_match.haml
app/views/needs/_additional_experts.haml
config/locales/views.fr.yml
spec/models/user_spec.rb

Au passage de #1119, mais sans rapport direct.

Nettoyage: retrait de méthodes inutilisées ou redondantes

---

app/controllers/reminders_controller.rb
app/views/reminders/_expert_contents.haml

Change la couleur des bouton et trie uniquement par besoins sans réponse
closes #1193

couleur des boutons et trie dans les relances

---

app/views/diagnoses/_archive_action.haml

POST!!!!! 🤷‍♂️
This does not seem to trouble browsers, I guess rails-ujs tolerates it somehow.

Fix http verb for the unarchive button

---

app/admin/solicitation.rb
app/models/badge.rb

Add badges and diagnoses columns to solicitation csv export

---

app/assets/stylesheets/application/semantic-ui_extensions.sass
app/views/application/_navbar.html.haml
app/views/layouts/application.html.haml
app/views/layouts/side_menu.html.haml
app/views/layouts/user_tabs.html.haml
app/views/users/_header.html.haml
app/views/users/_menu.html.haml
config/locales/views.fr.yml

Make the user_tabs layout generic (and wider).
Set `@wide_layout` to true or use `layout "side_menu"`, or subclass it (like `layout "user_tabs"`).
preliminary work for #1119

Add new “wide_layout”

---

README.md

Add README note re: DNS configuration

---

app/models/concerns/archivable.rb
app/views/matches/_match.haml
app/views/needs/_need_header.haml
config/locales/views.fr.yml

affiche si un besoin est mis en échec et masque les boutons d'action

---

app/admin/institution.rb
app/assets/stylesheets/application/layout.sass
app/controllers/institutions_controller.rb
app/models/institution.rb
app/policies/institution_policy.rb
app/views/application/_navbar.html.haml
app/views/institutions/_advisors_table.html.haml
app/views/institutions/_antennes_table.html.haml
app/views/institutions/_header.html.haml
app/views/institutions/_institutions_table.html.haml
app/views/institutions/_menu.html.haml
app/views/institutions/_subjects_table.html.haml
app/views/institutions/advisors.html.haml
app/views/institutions/antennes.html.haml
app/views/institutions/index.html.haml
app/views/institutions/subjects.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb

Pages d’institutions et tables de suivi de déploiement

---

app/controllers/institutions_controller.rb
app/jobs/csv_job.rb
app/models/antenne.rb
app/models/expert_subject.rb
app/models/institution_subject.rb
app/models/match.rb
app/models/user.rb
app/services/csv_export/models/antenne.rb
app/services/csv_export/models/match.rb
app/services/csv_export/models/user.rb
app/services/csv_export_service.rb
app/views/diagnoses/steps/_expert_subject_checkboxes.html.haml
app/views/institutions/_advisors_table.html.haml
app/views/institutions/_antennes_table.html.haml
config/locales/fr.yml
spec/services/csv_export_service_spec.rb

au format attendu pour l’import. refs #1119
WIP:
* Use a better table footer for the buttons
* Dry it up
* Write tests!

Export CSV des antennes et conseillers

---

app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb

this is actually following #991

Avoid sending emails to deleted experts

---

app/views/needs/index.html.haml
config/locales/views.fr.yml

display message where there is no needs

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/index.sass
app/views/about/comment_ca_marche.html.haml
app/views/landings/index.haml
app/views/landings/new_solicitation.html.haml
app/views/landings/show.haml
app/views/pages/_newsletter.html.haml
config/locales/views.fr.yml

Améliorations sur le portail utilisateur

---

app/views/landings/new_solicitation.html.haml
app/views/pages/_newsletter.html.haml
config/locales/views.fr.yml

Ajoute le bouton VoxUsagers

---

app/controllers/institutions_controller.rb
app/helpers/nested_errors_helper.rb
app/models/expert.rb
app/models/expert_subject.rb
app/models/institution.rb
app/models/user.rb
app/services/csv_import/antenne_importer.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
app/views/institutions/_import_errors.html.haml
config/locales/views.fr.yml
spec/services/csv_import_service_spec.rb

Fixes and improvement on import and error reporting.
followup #1254, refs #1253

Improvements for User and Antenne import

---

app/assets/stylesheets/pages.sass

Affiche les logos sur une seule ligne sur la plupart des écrans

---

app/controllers/institutions_controller.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
app/views/institutions/_antennes_table.html.haml
spec/services/csv_import_service_spec.rb

More import improvements

---

app/views/matches/_match.haml

fixup mark match as done for admin

---

app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/helpers/badges_helper.rb
app/helpers/page_infos_helper.rb
app/models/concerns/involvement_concern.rb
app/models/need.rb
app/views/application/_navbar.html.haml
app/views/reminders/_menu.html.haml
app/views/reminders/experts/_expert_contents.haml
app/views/reminders/experts/_header.html.haml
app/views/reminders/experts/_menu.html.haml
app/views/reminders/experts/index.haml
app/views/reminders/experts/needs.haml
app/views/reminders/experts/show.haml
app/views/reminders/needs/_needs.html.haml
app/views/reminders/needs/index.html.haml
config/initializers/inflections.rb
config/locales/views.fr.yml
config/routes.rb
spec/models/need_spec.rb

Reminders review

---

.gitignore

I’m giving [Nova](https://panic.com/nova/) a try :)

Ignore Panic’s Nova editor files

---

app/assets/stylesheets/application/institutions.sass
app/controllers/institutions_controller.rb
app/models/antenne.rb
app/models/expert.rb
app/models/expert_subject.rb
app/models/institution.rb
app/models/user.rb
app/services/csv_export/models/user.rb
app/views/institutions/_advisors_table.html.haml
app/views/institutions/_institutions_table.html.haml
config/locales/views.fr.yml

* additional row to check the number of experts for each subject
* do not count or display deleted users and experts
(refs #1253)

Améliorations sur l’annuaire

---

app/views/company_satisfactions/new.html.haml
app/views/mailers/company_mailer/satisfaction.html.haml
config/locales/views.fr.yml

ajustements des questions dans l'email de satisfaction

---

app/admin/diagnosis.rb

(I just had to do it manually)

Allow setting the solicitation id in admin/diagnoses/edit

---

app/controllers/needs_controller.rb
app/views/needs/_need_header.haml
config/locales/views.fr.yml

Renomme le bouton "Mettre en échec" en "Archiver"

---

app/admin/expert.rb

Following #1292
fixes PLACE-DES-ENTREPRISES-A4

Fixup /admin/experts edition

---

app/helpers/nested_errors_helper.rb
spec/helpers/nested_errors_helper_spec.rb

fixes PLACE-DES-ENTREPRISES-A6
Also comment and test nested_errors_messages 🤷

Fix a crash in nested_errors_messages (when importing users)

---

app/admin/match.rb
config/locales/models.fr.yml
vendor/assets/stylesheets/active_admin.scss

Traduction et couleurs corrects pour les labels des états des besoins

---

app/assets/javascripts/pages/matomo_events.js
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_index_landing_card.html.haml

un au clique sur la home vers une landing et un au clic d'une landing vers le formulaire
closes #1316

Ajoute des events Matomo

---

Gemfile
Gemfile.lock
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/solicitations_controller.rb
config/environments/development.rb

En lien avec https://github.com/betagouv/place-des-entreprises/pull/1313

Ajout de bullet et amelioration de qq requetes

---

app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb

ne prend pas en compte les analyses non complètes dans les relances

---

app/assets/javascripts/pages/navbar.js

Répare le bug de la navigation sur mobile, gérée en js et inexistante au format iframe. 
closes #1235

Fix toggle navbar on mobile #1235

---

app/models/feedback.rb
spec/models/feedback_spec.rb

Ne notifie pas les experts pour les commentaires s'ils ont refusé le besoin

---

app/admin/user.rb

Allow batch-deleting users in admin

---

config/brakeman.ignore

Remove an obsolete ignored entry for brakeman

---

app/models/expert_subject.rb

Do not offer to match with deleted experts

---

app/controllers/landings_controller.rb

Redirect not_found landing pages using a 301 instead of a 302

---

app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/models/need.rb
app/views/reminders/_menu.html.haml
config/locales/views.fr.yml
config/routes.rb

Ajoute un onglet relance pour prévenir l'institution + wording

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/index.sass
app/assets/stylesheets/pages/section_examples.sass
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_index_landing_card.html.haml
app/views/landings/_index_landing_cards.html.haml
spec/features/new_solicitation_feature_spec.rb

Rend les cartes accessibles et ajoute des bordures au survol

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/index.sass
app/assets/stylesheets/pages/section_examples.sass
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_index_landing_card.html.haml
app/views/landings/_index_landing_cards.html.haml
spec/features/new_solicitation_feature_spec.rb

20ce89f7d9c830e03e701bb0cfa85c3e61ec4a5b
oups
refs #1369

Revert "Merge pull request #1363 from betagouv/accessibility"

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/index.sass
app/assets/stylesheets/pages/section_examples.sass
app/views/landing_topics/_landing_topic.html.haml
app/views/landings/_index_landing_card.html.haml
app/views/landings/_index_landing_cards.html.haml
spec/features/new_solicitation_feature_spec.rb

fixe pour pouvoir cliquer sur les boutons des cartes + fixes IE

---

app/assets/stylesheets/pages/section_examples.sass

corrige un problème de texte qui saute sur une certaine résolution d'écran

fixup padding for small screen

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/landing.sass
app/views/landings/_new_solicitation_form.html.haml
app/views/landings/new_solicitation.html.haml
config/locales/views.fr.yml

affiche les mentions d'information partout et déplace les options à coté

---

app/assets/javascripts/pages/matomo_events.js
app/assets/stylesheets/pages/landing.sass
config/locales/views.fr.yml

Je ne sais pas si c'est méga utile avec le travail qu'est en train de faire @clairezed mais ça ne m'a pas pris longtemps.
closes #1320

ajoute une evenement Matomo pour la recherche du siret

---

app/controllers/concerns/expert_subjects_modal.rb
app/models/expert.rb
app/models/user.rb
lib/tasks/fix_flags_values.rake
spec/models/expert_spec.rb

Prevent displaying the subjects review modal

---

app/assets/javascripts/pages/siret_autocomplete.js
app/views/landings/_new_solicitation_form.html.haml
config/locales/views.fr.yml

Une micro PR pour corriger une absence de traduction d'une branche finalement mergée trop vite. 
Cf https://github.com/betagouv/place-des-entreprises/pull/1376#issuecomment-727914496

Add assistive hint translation

---

app/models/need.rb
config/locales/views.fr.yml

Met à jour les delais des relances

---

app/admin/need.rb
app/models/need.rb
config/locales/models.fr.yml

supprime le scope by status

---

app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/views/reminders/_menu.html.haml
config/locales/views.fr.yml
config/routes.rb

Ajouter un onglet « Besoins refusés » 

---

app/views/pages/_alert_region.haml
config/locales/views.fr.yml

⚠️ penser à ajouter `Île-de-France` à la variable d'environnement `DEPLOYED_REGIONS` 
closes #1419

ajoute l'Île-de-France aux régions déployées

---

app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/models/need.rb
app/views/reminders/_territory_choice.haml
app/views/reminders/experts/index.haml
app/views/reminders/needs/index.html.haml
config/locales/views.fr.yml
spec/models/need_spec.rb

permet de trier l'ensemble des relances par région

---

app/assets/stylesheets/application/diagnoses.sass
app/controllers/needs_controller.rb
app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/controllers/reminders_actions_controller.rb
app/models/concerns/involvement_concern.rb
app/models/expert.rb
app/models/need.rb
app/models/reminders_action.rb
app/views/reminders/_diagnosis.haml
app/views/reminders/_menu.html.haml
app/views/reminders/_needs.html.haml
app/views/reminders/experts/_expert_contents.haml
app/views/reminders/experts/_menu.html.haml
app/views/reminders/experts/needs.haml
app/views/reminders/needs/_diagnosis.haml
app/views/reminders/needs/_needs.html.haml
app/views/reminders/needs/index.html.haml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20201116141908_create_reminders_actions.rb
db/schema.rb
spec/factories/needs.rb
spec/factories/reminders_action.rb
spec/models/need_spec.rb

ajoute des boutons pour sortir les besoins des relances

---

app/models/match.rb

Apparemment il ne restait que ça
closes #1435

remove old status from match

---

app/assets/stylesheets/application/layout.sass
app/views/diagnoses/steps/matches.html.haml
config/environments/development.rb

- Je suis pas convaincue à 100% du style, mais je me dis que ça changera à terme avec la refonte des fiches entreprises ?
- C'est `diagnosis.content` que j'affiche. Je sais pas si ça aurait pu être du `need.content` (c'est pas encore clair pour moi qu'est-ce qui est quoi).
closes #1442

Add solicitation text to mer

---

app/models/need.rb
lib/tasks/update_needs_status.rake
spec/models/need_spec.rb

refs #1417
⚠️ 🧹The rake task needs to be run in production after deployment.

🧹 Change update_status to fix “quo” needs

---

app/controllers/needs_controller.rb
app/models/concerns/involvement_concern.rb
app/views/needs/index.html.haml
spec/models/concerns/involvement_concern_spec.rb
spec/models/need_spec.rb

Fix involvement scopes

---

app/views/needs/_received_needs.haml

Sort received needs by happened_on date, instead of updated_at

---

app/admin/need.rb
config/locales/models.fr.yml

For consistency with the app UI. refs #1323, followup #1291 
Before | After

Do not say “en échec” when archiving a need in admin

---

app/helpers/institutions_helper.rb

l'erreur était `undefined method display_image for Class`

fix un bug à l'envoie des invitations

---

app/admin/feedback.rb
config/locales/models.fr.yml

Followup #1465, j’ai remarqué que ça manquait, refs #1466

Add category columns filters to /admin/feedbacks

---

app/views/needs/_need.haml

L'affichage pêtait suite à la dernière mise en prod
TODO : tester l'affichage des pages pour les utilisateurs

Quick fix affichage needs#show

---

app/views/needs/_need_content.haml
spec/features/users/needs_feature_spec.rb

Un test bête et méchant pour vérifier que la page d'un besoin est bien toujours accessible.
Test de non-régression pour https://github.com/betagouv/place-des-entreprises/pull/1473

Add need show feature test

---

app/controllers/application_controller.rb

redirect to "/besoins/boite_de_reception" after login

---

app/views/matches/_match.haml

sur la page entreprise ajoute un lien vers la page relance d'un référent

---

app/views/stats/_stats_params.haml

bug, affiche le filtre institution pour les admin uniquement

---

lib/tasks/update_users_emails.rake

@clairezed je te laisse jeter un œil avant que je merge, j'ai deja fait une PR avec une erreur ce matin du coup je veux bien une relecture 😅

fixup update_users_emails task

---

app/services/admin_mailers_service.rb
app/views/mailers/admin_mailer/weekly_statistics.html.haml

La mise à jour de l'email de stats était passé entre les mailles du réaménagement des stats :)
@LucienMLD je te laisse jeter un oeil, que tout est bon ?

Correction email admin des stats

---

app/admin/solicitation.rb
app/models/application_record.rb
app/models/record_extensions/human_count.rb
config/initializers/core_extensions.rb

Fix n+1 admin solicitations

---

app/assets/stylesheets/shared/autocomplete.sass
app/front/javascripts/application/insee_code_field.js
app/views/application/_insee_code_field.html.haml
config/locales/views.fr.yml

Ajoute l'auto complétion pour la localisation des sollicitations manuelles

---

app/services/company_mailer_service.rb

Besoin de logguer + d'info pour identifier un possible bug avec sendinblue

Get more info with Sentry

---

app/models/user.rb
config/locales/views.fr.yml
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/devise_mailer_preview.rb
spec/models/user_spec.rb

Enlarge never_used_account to never accepted invitation

---

Gemfile
Gemfile.lock

See https://github.com/voormedia/rails-erd/pull/365

Use a fork of rails-erd for Rails 6.1 compatibility

---

app/controllers/application_controller.rb
app/controllers/concerns/auto_fullscreen_layout.rb
app/controllers/concerns/iframe_prefix.rb
app/controllers/shared_controller.rb
app/front/javascripts/pages/iframe_external_links.js
app/helpers/nested_errors_helper.rb
app/models/concerns/diagnosis_creation.rb
app/models/user.rb
app/services/csv_export.rb
app/services/csv_export/base_exporter.rb
app/services/csv_import.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
app/views/layouts/application_fullscreen.html.haml
app/views/layouts/user_tabs.html.haml
config/routes.rb

Sparkle comments everywhere

---

app/controllers/reminders/experts_controller.rb
app/models/concerns/involvement_concern.rb
app/models/expert.rb
app/models/match.rb
app/models/need.rb
app/services/expert_reminder_service.rb
app/views/reminders/experts/_expert_contents.haml
app/views/reminders/experts/_menu.html.haml

Comments for Needs scopes (#1367)

---

app/front/javascripts/pages/siret_autocomplete.js

Évite de retourner une erreur à chaque page si on n’est pas sur le formulaire

fix for siret autocomplet

---

app/controllers/pages_controller.rb
app/controllers/stats/base_controller.rb
app/views/pages/_footer.haml
spec/policies/stats/all_policy_spec.rb

Add stats policy and authorize team link

---

.browserslistrc
app/front/packs/application.js
app/front/packs/pages.js
app/views/layouts/pages.html.haml
package.json
yarn.lock

closes #1490 
(enfin, j'espère)

Add IE11 compatibility

---

app/views/companies/_mandataire.html.haml
config/locales/views.fr.yml
doc/04-architecture.md

Remove mandataire birthdate

---

app/mailers/user_mailer.rb
spec/mailers/user_mailer_spec.rb

Prevent notify_match_status to be sent to admin

---

app/services/stats/public/all.rb
app/views/stats/public/index.haml

Hide region stats

---

app/front/javascripts/application/feedbacks.js

En lien avec https://sentry.data.gouv.fr/betagouvfr/place-des-entreprises/issues/1894542
Apparemment, l'erreur de popait que pour les feedbacks. J'y ai donc appliqué les modifs que j'avais précédemment appliquées ailleurs.
Cf https://github.com/betagouv/place-des-entreprises/pull/1416

Change feedbacks js loop

---

app/services/csv_import/user_importer.rb
spec/services/csv_import/user_importer_spec.rb

Add user import attributes sanitization

---

app/helpers/solicitation_helper.rb
app/models/institution.rb
app/models/solicitation.rb
app/services/stats/matches/transmitted_less_than_72h_stats.rb
app/services/stats/public/solicitations_diagnoses_stats.rb
app/services/stats/public/taking_care_time_stats.rb
config/locales/views.fr.yml
spec/models/solicitation_spec.rb
spec/views/stats/public/index.html.haml_spec.rb
spec/views/stats/team/index.html.haml_spec.rb

Fix stats with diagnosis and test

---

app/controllers/companies_controller.rb
app/services/api_entreprise/entreprise_response.rb

close #1580 
Peut-être un changement d'API côté API Entreprise ?

Fix missing entreprise key for API Ets

---

.circleci/config.yml
app/controllers/concerns/geocoder_ip.rb
app/models/clockwork.rb
app/models/solicitation.rb
app/models/territory.rb
app/services/stats/base_stats.rb
app/services/stats/public/all.rb
app/services/stats/public/exchange_with_expert_stats.rb
app/services/stats/public/experts_stats.rb
app/services/stats/public/solicitations_diagnoses_stats.rb
app/services/stats/public/solicitations_in_regions_stats.rb
app/services/stats/public/taking_care_time_stats.rb
app/views/landings/_new_solicitation_form.html.haml
app/views/pages/_alert_region.haml
app/views/stats/public/index.haml
config/locales/views.fr.yml

- closes #1572 
- closes #1574 
/!\ mettre à jour les codes region des Solicitation en amont

Amélioration des stats, notamment régionales

---

app/services/stats/public/solicitations_diagnoses_stats.rb
app/services/stats/public/solicitations_stats.rb

Ajoute le filtre région pour les stats "% de demandes dans les régions déployées transmises aux conseillers"

---

app/admin/institution.rb
app/admin/match.rb
app/admin/need.rb
app/admin/solicitation.rb
app/controllers/concerns/territory_filtrable.rb
app/controllers/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/services/stats/matches/transmitted_less_than_72h_stats.rb
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

closes #1578 
/!\ Merger d'abord https://github.com/betagouv/place-des-entreprises/pull/1576, branch sur laquelle se base cette PR

Mise à jour du code suite à l'ajout de code_region aux sollicitations

---

app/controllers/companies_controller.rb

Fix company_path arguments

---

app/views/sitemap/sitemap.xml.builder

Réparation de l'url des stats dans la sitemap

---

app/helpers/solicitation_helper.rb
app/models/solicitation.rb
config/locales/views.fr.yml
spec/models/solicitation_spec.rb

Solicitations invisibles : création de la catégorie 'inclassable'

---

app/controllers/utilities_controller.rb
app/front/javascripts/pages/siret_autocomplete.js
app/models/use_cases/search_company.rb
app/models/use_cases/search_facility.rb
app/services/api_entreprise/entreprise_request.rb
app/services/api_entreprise/entreprises.rb
app/services/api_entreprise/etablissement_request.rb
app/services/api_entreprise/etablissements.rb
app/services/search_etablissement.rb
config/routes.rb
spec/models/use_cases/search_company_spec.rb
spec/models/use_cases/search_facility_spec.rb
spec/services/api_entreprise/entreprises_spec.rb
spec/services/api_entreprise/etablissements_spec.rb

Mise à jour token API Entreprise et gestion SIRET non-diffusables

---

Gemfile
Gemfile.lock
bin/rails
spec/rails_helper.rb
spec/spec_helper.rb

Parce que ça ne mange pas de pain. Et une fois qu'on active la config Rails les résultats sont tout de suite moins cools

Code coverage

---

app/controllers/concerns/territory_filtrable.rb
app/controllers/reminders/base_controller.rb
app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/solicitations_controller.rb
app/views/solicitations/index.html.haml

Improve solicitation

---

app/models/clockwork.rb

MAJ code_region sollicitation chaque jour

---

app/controllers/concerns/geocoder_ip.rb

Fix geocoder i18n error

---

app/models/clockwork.rb

J'avais oublié de changer la tâche pour qu'elle lance la tâche complète (= avec interrogation de API Ets)

Clockwork update solicitations code_region with api entreprise

---

app/models/solicitation.rb
app/views/solicitations/_solicitation.haml
config/locales/views.fr.yml

Ajout du lien "historique" dans les vignettes sollicitations

---

app/admin/need.rb
config/locales/models.fr.yml

@LucienMLD demande express de @MathieuGens pour pouvoir voir les antennes notifiées d'un besoin
close #1648

Export needs antennes

---

app/controllers/needs_controller.rb

Fix nombre affiché dans boite de réception

---

app/controllers/shared_controller.rb

Fix user header sans user après une erreur

---

app/front/stylesheets/pages.sass
app/views/layouts/pages.html.haml

... en créant un css_pack_tag vide. Et oui.
close #1659

Fait réapparaitre les icones côté public

---

app/views/shared/_matomo.html.haml

https://sentry.io/share/issue/8403d934a1c148e7a30e079786a28cb7/

add condition for time event

---

app/helpers/application_helper.rb
app/views/about/comment_ca_marche.html.haml
app/views/devise/sessions/new.html.haml
app/views/layouts/pages.html.haml
app/views/stats/public/index.haml
config/locales/devise.fr.yml
config/locales/views.fr.yml
public/robots.txt

close #1657 
(ticket scindé en deux, suite : #1677 )

Seo - clean de base

---

config/environments/production.rb

⚠️ il faudra tester les iframes sur staging avant de MEP

add default headers

---

app/views/landings/_show_landing_topics.html.haml

masque le texte en dessous des sujets pour les iframes 

---

app/front/javascripts/application/jquery-accessible-simple-tooltip-aria.js

closes #1689 
https://sentry.io/organizations/place-des-entreprises/issues/2320805274/events/2cb56f671e9b4f89a26c0d57ac9fae8e/?project=5671428
L'erreur à l'air de survenir sur la dernière version de chrome uniquement et c'est Steph qui a eu la plupart sans s'en rendre compte

check if aria_describedby is present

---

app/models/need.rb
app/policies/facility_policy.rb
app/views/companies/_facility_infos.html.haml
app/views/needs/show.haml
spec/policies/facility_policy_spec.rb

Affiche l'historique des besoins dès qu'il y a eu UN besoin, dans la vignette sollicitation

---

app/front/stylesheets/application.sass
app/front/stylesheets/base.sass
app/front/stylesheets/components/alertes.sass
app/front/stylesheets/components/buttons.sass
app/front/stylesheets/components/cards.sass
app/front/stylesheets/components/components.sass
app/front/stylesheets/components/navigation.sass

petits fixes de style

---

app/controllers/needs_controller.rb
config/routes.rb

fix https://sentry.io/organizations/place-des-entreprises/issues/2355752869/?environment=production&project=5671428&referrer=alert_email

change antenne_archived to antenne_expired

---

app/assets/stylesheets/pages.sass
app/helpers/images_helper.rb
app/helpers/regions_helper.rb
app/views/about/cgu.fr.html.erb
app/views/landings/_show_landing_institutions.html.haml
app/views/pages/_navbar.haml
config/locales/views.fr.yml

J'ai un gros doute sur l'accessibilité du champ SIRET, il y a des erreurs W3C sur le html

petites améliorations RGAA

---

app/views/layouts/pages.html.haml
config/locales/views.fr.yml

change le titre meta de la page d'accueil

---

app/helpers/status_helper.rb
app/views/matches/_match.haml

ajoute une icône différente pour les experts ajoutés après

---

app/views/about/mentions_d_information.fr.html.erb

Merger en même temps que le bandeau cookies
#1656

Modifie les mentions d'informations. Adeline code inside 💪

---

app/front/packs/pages.js
app/front/stylesheets/pages.sass
app/front/stylesheets/tarteaucitron-dsfr.scss
app/helpers/scripts_snippets_helper.rb
app/views/layouts/pages.html.haml
app/views/pages/_footer.haml
app/views/shared/_tarteaucitron.html.haml
config/locales/views.fr.yml

Ajout d'un gestionnaire de cookies

---

app/controllers/needs_controller.rb
app/front/stylesheets/base.sass
app/front/stylesheets/components/buttons.sass
app/front/stylesheets/components/labels.sass
app/front/stylesheets/typo.sass
app/helpers/status_helper.rb
app/views/experts/edit.html.haml
app/views/feedbacks/_feedback.haml
app/views/matches/_match.haml
app/views/matches/update.js.haml
app/views/needs/_match_actions.html.haml
app/views/needs/show.haml
app/views/users/registrations/antenne.html.haml
config/locales/views.fr.yml
spec/views/needs/show.html.haml_spec.rb

Petites amélioration page d'un besoin

---

lib/tasks/update_solicitations_code_region.rake

Restreint les appels à API entreprise en tâche de fond, pour éviter de dépasser les limites

---

app/controllers/about_controller.rb
app/views/about/accessibilite.html.erb
app/views/application/_footer.html.haml
app/views/pages/_footer.haml
config/locales/views.fr.yml
config/routes.rb

- ajout mention de non-conformité dans les footers
- page Accessibilité minimaliste
close #1273

Ajout page accessibilité

---

app/admin/match.rb
app/services/csv_export/match_exporter.rb

Corrige les pages analyses en page besoin en admin

---

public/robots.txt

Bloquer l'indexation iframe via robots.txt

---

app/front/javascripts/shared/index.js
app/front/javascripts/shared/polyfills.js

Add polyfill for element.matches
