Gemfile
Gemfile.lock
package.json

Shouldn’t change much; there are webpack-dev-server troubles that _should_ be fixed, according to the changelog, but 🤷‍♂️ .

Bump webpack-related gems

---

app/models/user.rb
app/views/mailers/admin_mailer/new_user_created_notification.html.haml
config/locales/views/mailers/admin_mailer.fr.yml
spec/factories/users.rb
spec/models/user_spec.rb

Bypass the manual admin validation for users from known domains. Users still have to confirm their email address, it’s just the additional approval.
The list of domain is currently hardcoded; we’ll see later if we need something more flexible.

Auto-approve users from know safe domains

---

app/admin/dashboard.rb
app/models/user.rb
config/locales/active_admin.fr.yml
spec/models/user_spec.rb

A quick hack to display the number of “active” users on the admin dashboard.
(Active users here are users who made a visit that was actually taken into account in the last 30 days.)

Show Active users on the Dashboard

---

app/admin/territory.rb
app/models/territory.rb
spec/models/territory_spec.rb

Allow admins to copy-paste the city codes in the admin panel directly in the admin panel.

Allow mass-import territory cities from admin panel

---

app/admin/expert.rb
app/admin/selected_assistance_expert.rb
app/admin/territory.rb
app/admin/user.rb
app/models/expert.rb
app/models/selected_assistance_expert.rb
app/models/territory.rb
config/locales/active_admin.fr.yml

Added selected_assistance_expert -> territories associations and allow filtering by territories in the admin.
https://trello.com/c/9RRj0rs1/193-dans-ladmin-permettre-de-filtrer-les-référents-contactés-par-territoire

Allow filtering selected experts by territory

---

app/controllers/stats_controller.rb
spec/controllers/stats_controller_spec.rb

Fix StatsController::history_date_ranges to respect the Rails timezone
Also add tests for history_date_ranges, although they don’t really allow to exhibit the buggy behaviour.

Remove the additional “next month” line in the stats page

---

app/admin/company.rb
app/admin/facility.rb
app/models/company.rb
app/models/facility.rb
config/locales/active_record.fr.yml
spec/models/facility_spec.rb

* Display the list of (known) facilities in the company page
* Filter facilities by company name
That second change is important. In most ActiveAdmin pages, the default filter for a `has_many` association is a `:select` drop down menu, which doesn’t make sense when there’s a lot of items. Using `filter :<association>_<attribute>, as: :string` displays a text field instead, and we should use it everywhere in our AA pages.

Improve Admin view for companies / facilities

---

app/admin/company.rb
app/admin/territory.rb
app/models/diagnosis.rb
app/models/facility.rb
app/models/selected_assistance_expert.rb
app/models/territory.rb
config/locales/active_admin.fr.yml

(waiting for #126)
In the ActiveAdmin page, display the Matches (aka SelectedAssistanceExperts) for the visits of the facilities of a company, and for the facilities in the cities of a territory.

Display matches for territory

---

package.json

```
ERROR in ./app/javascript/packs/common/babel-polyfill.js
Module build failed: Error: Couldn't find preset "stage-0"
```
Not sure why this would start to fail after bumping Rails, but OK.

Fix Webpacker compilation in production

---

.circleci/config.yml

rspec runs in 30 seconds on my machine, there’s no need to spin several containers, and it (hopefully) works around the random failures. However, I have no idea (yet) why there’s a 150-second stall once per rspec run on Circle CI
I suspect some tests load the UI, and thus a full webpacker compilation.

CircleCI: no parallelism

---

Gemfile
Gemfile.lock

Actually, rcook/user_impersonate2 now redirects to https://github.com/userimpersonate/user_impersonate2, and (no longer?) instructs to specify the repository.

Use the regular user_impersonate gem

---

app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/views/diagnoses/step4.html.haml

Questions may be deleted by admins, which basically makes old diagnoses “bad data”. We still might a avoid a crash :D

Fix a crash when displaying diagnosed_needs of deleted questions

---

app/controllers/relays_controller.rb
app/models/clockwork.rb
app/models/relay.rb
app/services/relay_service/mailer_service.rb
app/views/layouts/_navbar.html.haml
app/views/relays/diagnoses.html.haml
app/views/relays/index.html.haml
app/views/relays/show.csv.erb
config/locales/views/layouts.fr.yml
config/locales/views/relays.fr.yml
config/routes.rb
spec/controllers/relays_controller_spec.rb
spec/services/relay_service/mailer_service_spec.rb

* Style and names
* Change routes of the `relays/` section for more standard `index` and `show` pages.
* Display one section per relay (territory) in the index page (even though most relay (users) only manage one territory)
* Allow downloading a CSV summary for each relay (territory)

Start refactoring relay/diagnoses

---

app/views/stats/_stats_table.html.haml

If anyone asks, that was rubocop’s fault.

Fix Stats View

---

app/admin/user.rb
app/models/expert.rb
app/models/user.rb
config/locales/active_record.fr.yml
db/migrate/20180709075825_create_experts_users.rb
db/schema.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb

This is actually a workaround: most users (conseillers) are expected to belong to one expert (équipe référent). However, some (référents) have different set of (compétences) for different (territoires), and as of today, exist in duplicate entries in the expert (référents) table. As we want to link a single user (conseiller) to all these experts, we need a many-to-many association.

Migration: Change Expert<->>Users to Experts<<->>Users

---

app/models/expert.rb
spec/models/expert_spec.rb

There was a modeling issue between Expert, Assistance, and Match; when an AssistanceExpert is destroyed, the Matches using it are correctly nullified. However, when replacing the Assistance of an Expert, the `:through` association using AssistanceExpert was destroyed, but its callback were not.
As per the [docs](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many): 
> If using with the :through option, the association on the join model must be a belongs_to, and the records which get deleted are the join records, rather than the associated records.
Which, as I understand, means we should specify `dependent: :destroy` on the `has_many: :through` association as well.

Fix removing the assistances of an expert

---

app/admin/expert.rb
app/admin/match.rb
app/admin/relay.rb
app/controllers/application_controller.rb
app/controllers/experts_controller.rb
app/controllers/matches_controller.rb
app/controllers/needs_controller.rb
app/helpers/needs_helper.rb
app/models/contact.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/match.rb
app/models/use_cases/update_expert_viewed_page_at.rb
app/models/visit.rb
app/views/admin/_matches.html.arb
app/views/matches/update.js.erb
app/views/needs/_assigned_diagnoses.html.haml
app/views/needs/_expert_buttons.html.haml
app/views/needs/_match.html.haml
app/views/needs/_match_for_need_owner.html.haml
app/views/needs/index.html.haml
app/views/needs/show.html.haml
config/locales/views/needs.fr.yml
config/routes.rb
spec/controllers/experts_controller_spec.rb
spec/models/match_spec.rb
spec/models/use_cases/update_expert_viewed_page_at_spec.rb

Display all the needs in a single place. Refactor from the experts_controller and relays_controller.
Some redesign would be needed, but it’s currently the same UI as what was done in relays_controller and experts_controller.
This does not actually activate the view, but puts everything in place.

Dashboard for Experts and Relays

---

app/helpers/companies_helper.rb
app/models/search.rb
app/models/user.rb
spec/models/relay_spec.rb
spec/models/search_spec.rb
spec/models/user_spec.rb

On the other hand, it’s not possible (yet?) to delete a user who made a visit.
Additionally, cleanup a similar test in Relay and remove a useless scope in Search.

Allow deleting a user with a search history

---

app/models/category.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
spec/models/diagnosed_need_spec.rb

inverse relationship, better `nested_attributes`, uniqueness of `diagnosed_needs`, cascade dependent: destroy.
🤗

Improve Diagnosis model

---

app/models/category.rb
app/models/question.rb
db/migrate/20180830154712_add_interview_sort_order.rb
db/schema.rb

Add a “order” attribute to categories/questions and use it as the default sort order.
This is not used yet in the UI, as the “GetStep2Data” methods order questions manually, by `category_id` and `id`. However, this should just work when the step2 is rewritten in pure Rails. (#184)

Add interview questions ordering

---

app/controllers/diagnoses_controller.rb

Whenever updating the needs fails and we render the step 2 again, we need to reset all the variables.

Assign the @categories variable before rendering step2

---

app/admin/diagnosis.rb
app/admin/match.rb
app/admin/visit.rb
app/models/visit.rb

Allow editing and deleting visits and diagnoses from ActiveAdmin, properly cascade deletions, and display diagnosed needs from the Diagnosis details view.

Improve ActiveAdmin operations for Visit/Diagnosis

---

app/controllers/diagnoses_controller.rb

Mainly, we want to fail if `happened_on` isn’t set, but in fact, all params are required.

Add additional verification when submitting the visit details

---

app/models/diagnosis.rb
app/views/diagnoses/step5.html.haml
spec/models/diagnosis_spec.rb

We’ll rely on `happened_on` instead, and localize only in the UI.

Do not use `creation_date_localized`

---

app/admin/expert.rb
app/admin/relay.rb
app/models/assistance_expert.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/match.rb
app/models/relay.rb
app/views/admin/_matches.html.arb
db/migrate/20180920101754_add_matches_status_index.rb
db/schema.rb

This is using the (implementation detail) value of the status enum; but it’s a start.

Change the default scope ordering of matches

---

app/models/diagnosed_need.rb
app/models/match.rb
app/services/expert_reminder_service.rb
spec/models/diagnosed_need_spec.rb
spec/models/match_spec.rb
spec/services/expert_reminder_service_spec.rb

It’s a scope on DiagnosedNeed, not on Match. Additionally, the old implementation on match broke severely when using `ordered_by_status`.

 Refactor the with_no_one_in_charge scope

---

config/application.rb

It was introduced in Rails 5.2, but we don’t plan to use it.
(This is what our application.rb would look like if generated anew with `--skip-active-storage`.)

Remove active_storage

---

spec/mailers/previews/devise_mailer_preview.rb
spec/mailers/previews/user_mailer_preview.rb

* Fix a live-reload issue MailerPreviews.
* Don’t use factories in previews, to avoid polluting the dev DB.

Better MailerPreviews

---

app/views/diagnoses/step5.html.haml
app/views/mailers/user_mailer/match_feedback.html.haml
app/views/needs/_expert_feedback.html.haml
app/views/needs/show.html.haml

This respects newlines in user-submitted comments.

Use simple_format() to display user-provided text

---

app/controllers/feedbacks_controller.rb
app/views/needs/_expert_feedback_owner.html.haml

Allow experts to leave and update their feedback comments by authenticating only with the token.
https://trello.com/c/jsxXVfxR/279-bug-dauthentification-pour-les-commentaires-sur-les-page-référents-avec-token

Fix feedback access with token

---

app/controllers/home_controller.rb
app/models/user.rb
spec/models/user_spec.rb

Sort them by territory name, then by “contact_page_order”.

Tweak the order of relays in the contact page

---

app/admin/diagnosed_need.rb
app/models/diagnosed_need.rb
app/services/admin_mailers_service.rb
app/views/mailers/admin_mailer/weekly_statistics.html.haml
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
config/locales/views/mailers/admin_mailer.fr.yml
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/services/admin_mailers_service_spec.rb

* Improved diagnosed needs scopes in /admin
* Add a section “X abandoned needs" in the weekly email

Notify admins of abandoned needs

---

app/admin/feedback.rb
app/admin/match.rb
db/migrate/20181019094404_add_index_to_experts.rb
db/schema.rb

`includes:` all the things.
I was actually expecting to see more of these. There’s another one on the User page when we tentatively match the experts with the same email; as this is not a proper ActiveRecord association, there’s no simple way to eager-load it. This isn’t a performance issue yet; we’ll discuss again when it becomes a problem.

Avoid N+1 queries in admin

---

app/models/commune.rb
app/models/facility.rb
app/models/territory.rb
app/models/territory_city.rb
db/migrate/20181022135726_create_communes.rb
db/schema.rb
spec/factories/communes.rb
spec/models/commune_spec.rb

Add a proper Commune model between territories, facilities and (soon) Antennes, instead of querying on the city_code.
This only creates new tables and columns; the old behaviour is maintained until we actually migrate data.
(preliminary work for https://trello.com/c/uzBpixmv/264-nettoyage-territoire)

Add Commune

---

app/views/mailers/expert_mailer/_reminders_match.html.haml

`besoins_url` leads to `/besoins` and the diagnosis param is interpreted as the expected format, which means the path looked like `besoins.1234`…

Fix urls to diagnoses in reminder emails

---

app/models/facility.rb
app/models/territory_city.rb
db/migrate/20181023155512_populate_communes.rb
db/schema.rb
spec/models/facility_spec.rb

I’m not sure why, but the PopulateColumns migration (#250) fails when adding the nonnull constraints, while all the data seems to be properly set.
I’ll just workaround it and do it in a distinct migration for now.

Split the migration in two to workaround issues on staging

---

app/models/company.rb
app/models/facility.rb
app/models/use_cases/search_facility.rb
app/models/visit.rb
app/services/user_daily_change_update_mailer_service.rb
app/views/diagnoses/index.html.haml
app/views/diagnoses/step2.html.haml
app/views/diagnoses/step3.html.haml
app/views/diagnoses/step5.html.haml
app/views/needs/show.html.haml
spec/models/company_spec.rb
spec/services/user_daily_change_update_mailer_service_spec.rb

* Never truncate company names: remove the `name_short` method and only use the full name; this is a UI issue, we’ll fix it in the UI if we encounter it again.
* Do not alter company names when importing: Don’t “titleize” when importing from the SIRENE api: we’ll titleize, if relevant, in the UI.

Don’t truncate or alter company names

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/territory.rb
app/models/antenne.rb
app/views/admin/_matches.html.arb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml

In the admin pages, allow creating Antennes from existing Institutions/Territories/Experts.
This will be the central step for https://trello.com/c/z9Ty2rNK/270-nettoyage-institutions and https://trello.com/c/uzBpixmv/264-nettoyage-territoire. Once the data is converted, we’ll be able to switch to the new logic, and get rid of the old associations.

Add “Antenne” creation tooling

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/territory.rb
app/models/antenne.rb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml

Missing from the previous iteration:
* batch convert actions in Institution, Territory and Expert
* form in Institution: mass-assign the Antennes
* form in Antenne: mass-assign Users and Experts

Add tooling and admin for Antennes

---

app/models/antenne.rb
app/models/commune.rb
db/migrate/20181108170718_cleanup_commune_join_tables.rb
db/schema.rb

* Rename intervention_zones to antennes_communes
* Remove the city_code fields in facility and communes_territorie (née territory_cities), as well as the timestamps in the join table.

Cleanup Commune related tables now that Antennes are properly created

---

app/admin/antenne.rb
app/admin/expert.rb
config/locales/active_admin.fr.yml

Allow modifying the team (Experts + Users) of an Antenne, and prevent modifying the (deprecated) Territories of an Expert.

Bugfixes for admin/territory and admin/antenne

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/territory.rb
app/helpers/admin_helper.rb
app/models/commune.rb
app/models/concerns/many_communes.rb
app/models/expert.rb
app/views/admin/_experts.html.arb
app/views/admin/_users.html.arb
config/locales/active_admin.fr.yml
config/locales/active_record.fr.yml
config/locales/common.fr.yml
spec/models/concerns/many_communes_spec.rb
spec/models/expert_spec.rb

Display intervention zones as portions of “Bassin d’emploi” instead of raw lists of insee_codes.

Improve intervention zones display in Admin

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/user.rb
app/helpers/admin_helper.rb
app/models/concerns/many_communes.rb
config/locales/active_record.fr.yml

* Display a short summary of the intervention zone of Antennes and Experts in admin index pages
* Improve performance of intervention_zone_description
* Allow filtering out users with unconfirmed emails

More admin improvements

---

app/controllers/diagnoses_controller.rb
app/models/assistance.rb
app/models/assistance_expert.rb
app/models/company.rb
app/models/concerns/many_communes.rb
app/models/contact.rb
app/models/diagnosed_need.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/facility.rb
app/models/institution.rb
app/models/match.rb
app/models/relay.rb
app/models/territory.rb
app/models/use_cases/get_diagnosed_needs_with_filtered_assistance_experts.rb
app/models/user.rb
app/models/visit.rb
app/services/admin_mailers_service.rb
app/services/relay_service/mailer_service.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/mailers/previews/relay_mailer_preview.rb
spec/models/assistance_spec.rb
spec/models/diagnosed_need_spec.rb
spec/models/diagnosis_spec.rb
spec/models/facility_spec.rb
spec/models/visit_spec.rb

Following #293, just use associations through models instead of using custom scopes.
This is only partially done, but it already accounts for `+21, -216` lines.

Remove unused scopes

---

app/assets/stylesheets/layout.sass
app/assets/stylesheets/semantic-ui_extensions.sass

Let’s just use the default (Helvetica / sans-serif).

Don’t include google fonts (in semantic-ui)

---

app/helpers/needs_helper.rb
app/views/diagnoses/_steps.html.haml
app/views/diagnoses/step2.html.haml
app/views/diagnoses/step3.html.haml

Following #309: replace some `form_for` with `form_with` and use turbolinks between diagnoses steps.
This _may_ also include a fix for https://trello.com/c/VovU4pzW/277-les-boutons-de-prise-en-charge-ne-fonctionnent-pas-chez-certains-référents

Use ujs / turbolinks more consistently

---

app/admin/territory.rb
app/admin/user.rb
app/controllers/home_controller.rb
app/models/user.rb
config/locales/active_admin.fr.yml
spec/models/user_spec.rb

Both in territories and in users details; also fix a performance issue with loading the “relays” scope in users.

Allow editing relays in admin

---

app/controllers/companies_controller.rb
app/models/facility.rb

For historical reasons, the SIRET numbers of La Poste are not luhn valid.
While we’re there, clean up a bit the siret validation code, from the controller to the Facility model. Still not great, but less terrible?

 Allow La Poste siret numbers to be recognized

---

app/admin/institution.rb

Allow editing. ActiveAdmin ajax_select inputs for to-many associations are buggy; without specifying the limit, only the first item is shown. When saving change, this tries to break the other associations, which our DB validations (hopefully) prevent.

Fix nonworking admin pages for institutions

---

app/controllers/home_controller.rb
app/models/user.rb

Also, avoid displaying duplicates

Avoid displaying unapproved profiles in the team page

---

app/controllers/companies_controller.rb
app/models/facility.rb
spec/models/facility_spec.rb

While we’re here, move this code to a more decent place (the Facility model), and add validation spec.

Tweak SIRET validation to allow hyphens and separator

---

app/models/diagnosis.rb
app/models/relay.rb
app/services/admin_mailers_service.rb
spec/models/diagnosis_spec.rb
spec/models/relay_spec.rb

We should use named associations instead of scopes when possible.

Remove unused `of_user` scopes

---

vendor/assets/stylesheets/template-data-gouv-main.css

Fix a missed copy-pasta in the css that led the form page to always use bold for Source Sans Pro
🤷‍♂️

Fix source-sans-pro font weight

---

app/admin/diagnosed_need.rb
app/models/diagnosed_need.rb
app/services/admin_mailers_service.rb
app/services/expert_reminder_service.rb
app/views/mailers/admin_mailer/weekly_statistics.html.haml
config/locales/active_admin.fr.yml
config/locales/views/mailers/admin_mailer.fr.yml
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/services/admin_mailers_service_spec.rb
spec/services/expert_reminder_service_spec.rb
spec/views/mailers/admin_mailer/weekly_statistics.html.haml_spec.rb

Now we only have
* “Rejected”: all contacted experts have explicitly rejected.
* “With no-one in charge”: not all contacted experts have responded, and no one has accepted.
Aditionally, all status-based scopes ignore the “archived” needs.

Clarify “rejected” and “no one in charge” needs

---

app/models/diagnosed_need.rb

ActiveAdmin apparently is not fond of scopes with subquery when using a custom order. 🤷🏻‍♂️

Workaround a crash in ActiveAdmin with order and scopes

---

app/controllers/stats_controller.rb
app/services/stats/advisors_stats.rb
app/services/stats/companies_stats.rb
app/services/stats/diagnosed_needs_stats.rb
app/services/stats/matches_stats.rb
app/services/stats/transmitted_needs_stats.rb
app/views/stats/show.haml
config/locales/views/stats.fr.yml

Dorénavant, une grande partie de la détection sera faite par l’équipe admin.
Dans le panneau des stats, on affichait les besoins détectés; j’ai changé pour afficher les besoins effectivement transmis, ce qui supprime la quantité de fausses détections faite par l’équipe pour tests. Ce n’est pas idéal non plus. Il faudrait sans doute passer du temps à les supprimer réellement.

Inclure l’activité des admins dans les stats

---

app/views/matomo/_matomo.html.haml

The way we report turbolinks page loads to matomo is wrong: the `/` prefix adds the whole url as a relative path, which is just wrong and creates a `https` group of pageviews on matomo. Let‘s just report the absolute url.

Fix urls reported to matomo during turbolinks events

---

app/views/feedbacks/create.js.haml
app/views/needs/show.haml

The feedback was always appended to the first need. This makes sure the element id specifies the need.

Fix the feedback not being posted on the right need

---

app/views/layouts/_head.html.haml
config/initializers/assets.rb
vendor/assets/stylesheets/ie9_fixes.sass

Not only is this of dubious use, ui.top.menu is not (anymore?) used in the app.

Remove (actually unused) ie9_fixes.sass

---

Gemfile
Gemfile.lock
app/admin/diagnosed_need.rb
app/admin/feedback.rb
app/admin/match.rb
app/models/diagnosed_need.rb
config/locales/active_record.fr.yml
spec/models/diagnosed_need_spec.rb

This takes into account comments and matches updated: allows scoping diagnosed_needs not recently updated.

Add DiagnosedNeed.last_activity_at

---

app/admin/diagnosed_need.rb
app/admin/match.rb
app/helpers/admin_helper.rb
app/helpers/status_helper.rb
app/models/diagnosed_need.rb
app/models/match.rb
app/services/relay_service/csv_generator.rb
app/services/stats/matches_stats.rb
app/views/needs/_diagnoses_list.haml
app/views/needs/_match.haml
app/views/needs/_need_header.haml
config/locales/active_record.fr.yml
spec/models/diagnosed_need_spec.rb

* Rename it :status, not :status_synthesis
* Add two new status :diagnosis_not_complete and :sent_to_no_one
* Add scope :by_status() and admin filter
* Dry status description methods with Match.status
(Also fixup admin params for #409)

Refactor DiagnosedNeed.status and description

---

app/controllers/stats_controller.rb
app/services/stats/needs_stats.rb
app/services/stats/transmitted_needs_stats.rb
app/views/stats/show.haml
config/locales/views/stats.fr.yml

(Actually, remove the “TransmittedNeedsStats” and count the transmitted needs in “NeedsStats”)
Need.diagnosis_completed
is the same thing as
Need.where(diagnoses: { step: Diagnosis::LAST_STEP })

Remove non-transmitted needs from stats

---

app/helpers/application_helper.rb

This is a workaround, we should ideally write “0 mise en relation”, which is possible but a little more complex.

Display a single dash when there is no match

---

app/models/concerns/archivable.rb
app/models/need.rb

I’m not 100% certain how this works:
1. The resulting query of the scope yields an array of ids.
2. Ransacker (?) uses this array to build another query that looks like this:
SELECT <things> WHERE id IN (<array>)
If array is empty, this is a syntax error. Ransacker (or ActiveAdmin) is not smart enough to avoid this query if there are no results.
🤷🏻‍♂️
I’m seeing this in production following #439, as I’ve assigned all non-assigned needs to the Support team and there are no `sent_to_no_one` needs anymore. 🤷🏻‍♂️

Tweak ransacker filters to avoid crashing when there are no results

---

Gemfile
Gemfile.lock
app/views/layouts/_navbar.html.haml
app/views/layouts/solicitations/_navbar.haml

Et c’était déjà prévu dans les css 🙆‍♂️

Use active_link_to in navbars

---

app/assets/stylesheets/solicitations/index.sass
app/views/landing/landing.haml

It makes stuff way too large on mobile, and was only maybe relevant when we had a multicolumn design.

Remove the landing-specific css rules

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb

Instead of redirecting to "/", which is the enterprise home page.

Redirect to "/conseillers" after a sign-up attempt

---

Gemfile

Don’t require rspec_junit_formatter gem
It’s only needed when running tests (for circleci).
It messes with the console, when running `rails c` it causes this warning:
```
irb: warn: can't alias context from irb_context
```
This is related to rspec monkey_patching a `context` method on `Object` (https://github.com/rspec/rspec-rails/issues/1645)

Fix irb_context in rails console

---

app/controllers/needs_controller.rb
app/helpers/feedback_helper.rb
app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb
app/models/diagnosis.rb
app/models/match.rb
app/models/need.rb
app/models/use_cases/update_expert_viewed_page_at.rb
app/services/admin_mailers_service.rb
app/services/expert_reminder_service.rb
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
app/views/needs/_diagnoses_list.haml
app/views/needs/_match.haml
app/views/needs/index.html.haml
spec/mailers/previews/expert_mailer_preview.rb
spec/models/match_spec.rb
spec/views/mailers/expert_mailer/notify_company_needs.html.haml_spec.rb

Since we removed Relays, all the code in Match that switched between relays and experts can be removed. This also includes the `of_expert()` scope (previously known as `of_relay_or_expert()`.

Remove no-longer-needed methods

---

app/admin/expert.rb
app/models/expert.rb
app/models/user.rb
config/locales/models.fr.yml

Only as admin tooling for now; confirmation email is disabled.
Experts without a team are actually _experts without an account_, and they need to click the notification email everytime; we’ll want to actually provide a user account for them, this is the first step.

Add admin tooling to create missing users for lonely experts

---

app/admin/diagnosis.rb
app/admin/need.rb
app/admin/subject.rb
app/helpers/admin_archivable.rb
app/models/concerns/archivable.rb
config/locales/models.fr.yml
spec/models/concerns/archivable_spec.rb

This is solely to make rubymine stop complaining about the “invalid” `archived?` key in the locale yaml file.

Rename :archived? to :is_archived

---

app/controllers/landing_controller.rb

Include the tracking params in the link to the root page so that they are included as hidden params in the contact form.

Forward the pk_* tracking params from the landing pages

---

app/admin/landing.rb
app/models/landing.rb
app/models/landing_topic.rb
config/i18n-tasks.yml
config/locales/models.fr.yml
db/migrate/20190520121816_create_landing_topics.rb
db/migrate/20190520144211_add_featured_to_landing.rb
db/schema.rb
spec/factories/landing_topics.rb

Cette PR prépare la migration vers les nouvelles pages de Landing, en enrichissant les modèles.
Pour l'instant elle n'apporte des changements qu'à l'interface d'administration. L'affichage des nouvelles données viendra par la suite.
- Les landings peuvent maintenant avoir des « Cas d’usage » (qui seront affichés en tant que pavés explicatifs sous le texte des pages de landing)
- Les landings peuvent maintenant être marqués comme « Affichées sur la Home » – c'est à dire qu'elles seront affichées en petit pavés sur la page racine du site.
Tout cela est éditable dans l'interface d'administration.

Amélioration des modèles de Landing

---

app/admin/skill.rb
app/models/need.rb
app/models/subject.rb

in admin/skills/new, do not display the archived subject in the picker.
Also: some cleanup in the `ordered_for_interview` scopes.

Do not offer archived subjects when creating new skills

---

app/assets/stylesheets/solicitations/index.sass
app/views/landings/_landing.haml
app/views/landings/index.haml

* hardcode css variables (until we properly use postcss)
* use several rows, no grids :(
* use cards, not tiles from the template.

Workarounds for Internet Explorer

---

app/admin/landing.rb
app/models/landing.rb
app/views/landings/show.haml
app/views/solicitations/_form.haml
config/locales/models.fr.yml
config/locales/views.fr.yml

They can (must) be specified in /admin/landings.

Add landing-page specific description examples

---

.rubocop.yml
app/models/diagnosis.rb
app/models/expert.rb
app/models/expert_skill.rb
app/models/match.rb
app/models/need.rb
app/models/use_cases/update_expert_viewed_page_at.rb
app/views/needs/show.haml
db/migrate/20190625123951_add_experts_and_skills_to_matches.rb
db/schema.rb
lib/tasks/migration/migrate_matches_expert_skills.rake
spec/controllers/matches_controller_spec.rb
spec/controllers/needs_controller_spec.rb
spec/factories/matches.rb
spec/lib/tasks/migration/migrate_matches_expert_skills.rake_spec.rb
spec/models/antenne_spec.rb
spec/models/diagnosis_spec.rb
spec/models/expert_skill_spec.rb
spec/models/expert_spec.rb
spec/models/match_spec.rb
spec/models/use_cases/update_expert_viewed_page_at_spec.rb
spec/services/expert_reminder_service_spec.rb
spec/support/tasks.rb
spec/views/mailers/expert_mailer/notify_company_needs.html.haml_spec.rb

Cette PR sépare la relation `Match -> Expert Skill` en `Match -> Expert` et `Match -> Skill`. Pour l'instant ça n'apporte aucun changement visible. À terme, cela permettra d'assigner manuellement des experts à un besoin plus facilement.
Cette PR :
- Crée les nouvelles relations sur le modèle
- Supprime les anciennes relations
- Ajoute une tâche Rake pour migrer les données de l'ancien schéma vers le nouveau
- Met à jour le code pour utiliser direction Match#expert là où c'est pertinent
(Le modèle `ExpertSkill` sera entièrement supprimé dans une PR future.)
Cette PR ne comporte pas d'état intermédiaire pour gérer à la fois l'ancien et le nouvel état de la base. Elle doit donc être mise en production à froid.
1. Couper l'accès au site en production
2. Mettre en production le nouveau code
3. …

Refactor Matches <-> Experts Skills relation

---

app/admin/delayed_job.rb

The status_tag method signature had changed a long time ago in ActiveAdmin; it was soft-deprecated in 1.x, and removed in 2.*. We upgraded to AA 2.1 in #481 3 weeks ago.

Fix admin/jobs display

---

app/controllers/application_controller.rb
app/controllers/diagnoses_controller.rb
app/controllers/feedbacks_controller.rb
app/controllers/matches_controller.rb
app/controllers/needs_controller.rb
app/models/contact.rb
app/models/diagnosis.rb
app/models/feedback.rb
app/models/match.rb
app/models/need.rb
spec/models/contact_spec.rb
spec/models/diagnosis_spec.rb
spec/models/feedback_spec.rb

1. Refactor permissions model
* remove spaghetti
* use two different “can_be_viewed” and “can_be_updated” methods
* decide which method to use depending on the http method
This is still done manually and a very simple model, but it’s slightly better than it used to be.
2. Allow support experts to access diagnoses

Allow support teams to view needs

---

app/controllers/stats_controller.rb
app/models/match.rb
app/models/user.rb
spec/models/match_spec.rb

Just use `where(status: <status>)` which has the same number of characters 🤷‍♂

Cleanup: remove scope `Match.with_status`

---

app/views/reminders/reminders_notes.js.haml

The bug isn’t noticeable, since the saved textfield has the same contents as the edited textfield, but it’s still bug.
https://sentry.data.gouv.fr/betagouvfr/place-des-entreprises/issues/1850469/

Update the correct element after saving an expert reminders notes

---

app/models/skill.rb

This led to a crash in ActiveAdmin queries like `/admin/experts?q[skills_id_eq]=74`
https://sentry.data.gouv.fr/betagouvfr/place-des-entreprises/issues/1855985/

Fix skill.matches relationship description

---

app/controllers/diagnoses_controller.rb
app/models/diagnosis.rb
app/views/application/flashes.js.haml
app/views/layouts/_flashes.html.haml
spec/factories/diagnoses.rb
spec/models/diagnosis_spec.rb

Some diagnoses have no happened_on (which is why I’m sorting by created_at in _diagnoses.haml).
This happens when the user passes invalid data in step 3 and the browser doesn’t block them. This conditionally validates the presence of :happened_on, as well as :visitee for good measure.
Additionally, this revealed another issue in the diagnosis form where we don’t properly display flash messages because requests are made through ujs.

Properly validate visitee / visit date attributes in diagnosis step 4

---

app/admin/expert.rb
app/admin/user.rb
app/helpers/users/registrations_helper.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/institution.rb
app/models/match.rb
app/models/need.rb
app/models/user.rb
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/needs/_team.html.haml
app/views/users/show.html.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
db/migrate/20190809151052_remove_user_institution.rb
db/schema.rb
spec/factories/users.rb
spec/features/users/registrations_controller_spec.rb
spec/models/user_spec.rb

`user.antenne.institution.name` should be used instead (or the shortcut `user.institution.name`)
We only have few users remaining that are not linked to an institution, and as we plan to add a lot of users in the next months, let’s make this future-proof.

Drop user.institution

---

app/views/needs/_more_matches.haml

e.g. experts with an access_token.

Prevent a crash when viewing a needs page when not connected

---

app/views/diagnoses/step3.html.haml

IE11 adds `left-to-right` marks around the `/`, which then breaks the date parsing on ruby’s side. Let’s just format it manually.
This is a quick and dirty fix, until we
- use a proper date library
- refactor this form to not use the same formatter for display and for data. 😓
This is ugly, but not as bad as it seems. As a matter of fact, we require french formatting when used as text input, and the placeholder reads 'jj/mm/aaaa'.

Fix date formatting for IE11 for diagnosis date

---

app/models/concerns/involvement_concern.rb

Only include active needs in the “taking care” scope

---

config/environments/production.rb
config/environments/staging.rb

Properly add Cache-Control headers for static assets.
Add some point between Rails 4 and 5, Scalingo and rails_12factor, the proper configuration settings were lost.

Add Cache-Control headers for static assets

---

app/controllers/needs_controller.rb
app/models/match.rb
app/models/need.rb
app/views/needs/_additional_experts.haml
app/views/needs/_match.haml
config/locales/fr.yml
config/locales/views.fr.yml

Following #539
- limit queries
- 3 characters minimum
- 15 results max
- disable button during request
- display “no results” when relevant
- indicate that a match has been made after the initial matches

Improve the “additional experts” flow

---

app/assets/javascripts/needs.js

`window.onload` doesn’t fire when navigating via turbolinks. (We had the same issue with matomo.)

Make sure semantic-ui popups in /besoins are activated

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
db/migrate/20191010145528_remove_user_contact_page_order.rb
db/schema.rb
spec/models/user_spec.rb

The “Team” info has been removed from the public pages for a while.

Remove User::contact_page attributes

---

spec/features/application_controller_feature_spec.rb
spec/mailers/admin_mailer_spec.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/user_mailer_spec.rb
spec/rails_helper.rb

rake spec loads .env, bin/rspec doesn’t.

Make sure tests pass in any env configuration

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/solicitations/_form.haml

We don’t have a spam problem — yet. This is a basically free solution; if/when it’s not enough, we’ll start looking for more.
Note: this gem adds inline CSS, that _might_ be an issue for CSP. We’ll see. In the worse case, it’s not really hard to add a honeypot field ourselves.

Add a honeypot field to the solicitation form

---

app/admin/user.rb
app/models/antenne.rb
app/models/institution.rb
app/models/user.rb
config/locales/models.fr.yml

We’re only relying on invitations from now on : users can’t change their email on their own.
This is almost the last step regarding invitations management; we’ll actually drop the confirmable-related column in a moment.

Stop using Devise:confirmable for Users

---

app/models/user.rb
config/initializers/devise.rb
config/locales/devise.fr.yml

* Email unknown: send nothing (obv)
* User imported, but not yet invited : send nothing
* User invited, but invitation not accepted yet: re-invite
* User with accepted invitation: send the regular reset email
In all cases: do not indicate whether the email is known.

Send relevant emails (or not) when the user resets their password

---

app/controllers/companies_controller.rb

This is probably temporary: we may drop api-entreprises completely at some point. (when the rncs api is no longer alpha)

Truncate possibly (very) long error messages from api-entreprises

---

app/views/landings/_landings.haml

We have 9 landings now 🤷🏻‍♂️.
I’d use a grid but it would fail on IE11.

Display 3 landing per row on the home page

---

db/migrate/20190325142929_add_archived_at_to_question.rb

🤷🏻‍♂️ hopefully this will let migrations pass from scratch (and will allow scalingo review apps to run)

Revert erroneous search-and-replace in a9b562

---

app/admin/user.rb
app/models/user.rb
config/locales/models.fr.yml
db/migrate/20191108085610_add_deleted_at_to_user.rb
db/schema.rb
spec/factories/feedbacks.rb
spec/models/feedback_spec.rb
spec/models/user_spec.rb

refs #641
Instead of actually destroying users from DB, we now:
* timestamp the deletion date, which makes them invalid for login
* blank the personal information (name, email and phone number)
That way, in the diagnoses and feedbacks of that user, we no longer indicate the user’s name but still know their Institution and Antenne.

Soft-delete users and clear personal information

---

app/admin/expert.rb
app/models/expert.rb
app/models/user.rb
app/views/devise/mailer/reset_password_instructions.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/devise/shared/_links.html.haml
config/locales/devise.fr.yml
config/locales/models.fr.yml
db/migrate/20191115134923_make_expert_phone_number_nonnull.rb
db/schema.rb
lib/tasks/create_experts_matching_users.rake
spec/factories/experts.rb
spec/mailers/previews/devise_mailer_preview.rb
spec/models/expert_spec.rb

* ⚠️  merge #649 and #650 first
* Add a rake task to create all Users for Experts without users
* These users are created without a password; they can’t be used to sign in.
* Reword and tweak the “reset password” email and forms to properly handle these new User accounts.
refs #638

Create Experts placeholder Users

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/user.rb

Before:
After:
---
Tweak “ajax_select” inputs in ActiveAdmin:
* For :users (and :advisors) inputs: specifying an empty collection prevents AA to preload the deleted accounts in the menu. The `scoped_collection` in admin/user.rb is respected by the actual ajax queries; however the initial content of the menu includes any Users, which made the deleted accounts available. (This is arguably a bug in the activeadmin-ajax_filter gem)
* For other :ajax_select inputs: remove the `limit: 999` I used to specify trying to make it look better. When the selected item is not present in the collection, AA will just display an empty field until the ajax query is actually made, which is weird and may take a few seconds in the worst scenarios. However, this is 1. fighting the framework, 2. plain ugly and …

Don’t show deleted accounts when selecting users in admin

---

config/locales/views.fr.yml

Shorten the meta-title so that “TPE et PME” fits in the google results

---

app/views/stats/_ministats.haml
app/views/stats/_stats_charts.haml
config/locales/views.fr.yml

Display the same “advisors“ count in stats and ministats

---

app/admin/antenne.rb
app/admin/expert.rb
app/admin/institution.rb
app/admin/user.rb

fixes #668
@LucienMLD est-ce que ça vaudrait la peine d‘écrire un mini-helper activeadmin pour ne pas réécrire ces 5 lignes à chaque fois qu’on utilise ajax_select? (dans une PR suivante, je préfèrerais merger ça rapidement pour éviter les accidents en prod)

Fix Admin to-many inputs forgetting relations

---

app/views/devise/mailer/invitation_instructions.html.haml
config/locales/devise.fr.yml
spec/mailers/previews/devise_mailer_preview.rb

This happens when requesting a password reset before actually having received the invitation: an invitation is sent, but there is no inviter.
fixes #684

Do not crash when sending an invitation with no inviter

---

.rubocop.yml
app/models/need.rb

After #676, all matches were updated to link to the new subjects. This inadvertently changed the `udpated_at` values. Fortunately, using the other datetime values should yield pretty much the same result.
fixes #683
Also use ruby 2.6-style endless ranges for ActiveRecord queries :)

Fix Need::abandoned scope to only take human activity into account

---

spec/factories/antennes.rb
spec/factories/communes.rb
spec/factories/companies.rb
spec/factories/contacts.rb
spec/factories/experts.rb
spec/factories/institutions.rb
spec/factories/users.rb

Ça évite à certains tests de rater à cause de deux valeurs qui ne sont pas uniques dans la base

add unique to faker factories attributes

---

app/admin/theme.rb
app/models/institution.rb
app/models/institution_subject.rb
app/models/subject.rb
app/models/theme.rb

Actually similar to #693; additionally, associations between theme and institutions were missing in the models.

Fix crashes in /admin/themes

---

lib/tasks/import_dump.rake

The -o option doesn’t exist anymore; I suspect we never actually needed it, it’s probably been copypasted since the beginning.

Fix the import_dump task for postgres 12

---

app/admin/patches/data_access.rb
app/admin/user.rb

fixes #691
(This is actually a rerun of a (dirty) patch that was removed when migrating to Rails 6.)
Properly override the scoped_collection in a module.
ℹ️ The overriding module needs to be in a path that is watched by zeitwerk if we want autoreload to work.

Fix duplicate rows in ActiveAdmin

---

app/admin/concerns/admin_archivable.rb
app/admin/helpers/admin_link_to.rb
app/admin/helpers/csv_builder.rb
app/admin/helpers/intervention_zone_description.rb
app/admin/helpers/status_status_tag.rb
app/admin/match.rb
app/admin/need.rb
app/admin/patches/scopes.rb
app/helpers/admin_helper.rb

Following #697, move around activeadmin helper methods.
In rails <6, there was a class (re)loading issue deep in ActiveAdmin, that lead to a massive leak when tweaking and reloading /admin pages, that became slower and slower to respond. Additionally, custom helper methods (i.e. `admin_link_to`) were actually _not_ reloaded at all. I’m not sure exactly what the bug was, and if the fix is just in zeitwerk working differently than the old loading mechanism. Anyway, things look better now.
Also, I spent too much time making #697 work properly; I felt this deserved more than a 3-line patch.

More fixes for activeadmin and zeitwerk

---

vendor/assets/stylesheets/mailers.sass

This is actually a preliminary commit for #600 and #638.
Big changes:
* No more grey background
* max-width from 600px to 700px
* Custom bullets for ul (larger dots)
* Finer “blockquotes”: just a thin line in the left margin instead of a grey zone

Redesign email css

---

app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb
app/models/diagnosis.rb
app/views/mailers/user_mailer/confirm_notifications_sent.html.haml
config/locales/views.fr.yml
spec/mailers/previews/user_mailer_preview.rb

⚠️ merge #713 first
This refs #600 but is actually done as cleanup for #638: 
In the main notification email to experts, we will add some optional warning if the expert needs to activate their user account. Sending this email (as cc:) to the advisor would be but confusing for the them. Let’s send a distinct email.

Send a distinct email to the advisor when sending notifications

---

app/views/layouts/_navbar.html.haml

No number, just a colored circle:

Add a “unread“ badge for unresponded matches in the navbar

---

README.md
lib/tasks/push_to_production.rake

It looks like this:
```
$ rake push_to_production
Updating master and production…
Depuis github.com:betagouv/place-des-entreprises
Last production commit is ebe7d79c4149c3ae64af917e0ccd09bb7c473cc8
About to merge 5 PRs and push to production:
🚀 
* [#718](https://github.com/betagouv/place-des-entreprises/pull/718) display created_at date instead of visit date
* [#720](https://github.com/betagouv/place-des-entreprises/pull/720) Bump rack from 2.0.7 to 2.0.8
* [#714](https://github.com/betagouv/place-des-entreprises/pull/714) Do not cc everyone in UserMailer#match_feedback
* [#710](https://github.com/betagouv/place-des-entreprises/pull/710) Send a distinct email to the advisor when sending notifications
* [#713](https://github.com/betagouv/place-des-entreprises/pull/713) Redesign email css …
```

New rake task `push_to_production`

---

app/controllers/feedbacks_controller.rb
app/mailers/user_mailer.rb
app/models/feedback.rb
app/views/mailers/user_mailer/match_feedback.html.haml
spec/mailers/previews/user_mailer_preview.rb

Après discussion il en est ressortie qu'on enverrait l'email de notification quand il y a un nouveau commentaire uniquement au conseillé qui a créé le besoin

Mail G - Information du conseiller sur le commentaire d’un référent

---

app/controllers/feedbacks_controller.rb
app/mailers/user_mailer.rb
app/models/feedback.rb
app/views/mailers/user_mailer/match_feedback.html.haml
spec/mailers/previews/user_mailer_preview.rb
spec/models/feedback_spec.rb

Send match_feedback email **from experts** to the diagnosis advisor only.
On the other way, send feedback emails from the advisor to all the experts.
fixup after #719 and #714

Send advisor feedback emails to all experts

---

app/controllers/concerns/flash_to_review_subjects.rb
app/mailers/expert_mailer.rb
app/models/diagnosis.rb
app/models/user.rb
app/views/devise/mailer/reset_password_instructions.html.haml
app/views/mailers/expert_mailer/_never_used_solo_account_warning.html.haml
app/views/mailers/expert_mailer/_remind_received_needs.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
config/locales/devise.fr.yml
config/locales/views.fr.yml
spec/mailers/previews/devise_mailer_preview.rb
spec/views/mailers/expert_mailer/notify_company_needs.html.haml_spec.rb

refs #638 
* Send notifications emails without an access_token
* Do not cc the advisor
* Send a password reset link to notified experts with unused accounts

No access token in notifications emails

---

config/routes.rb

/besoins/:need used to live at /diagnoses/experts/:need, but that was _a long time ago_, before there was even a relation between Users and Experts.
This is tangentially related to #735; we could patch it, but frankly let’s just get rid of it.

Remove old /diagnosis/expert route redirection

---

app/admin/need.rb
config/locales/models.fr.yml

L’équipe support peut accéder aux analyses, et peut mettre en relation directement depuis là.
@stephreso tu me confirmes que ce bouton :  <img width="287" alt="Capture d’écran 2019-12-27 à 16 40 40" src="https://user-images.githubusercontent.com/139391/71523130-e68fad00-28c7-11ea-9d9f-ab17551eba59.png"> n’est plus utilisé ?

Remove the “Match with support” button in /admin/needs

---

config/locales/views.fr.yml

The `taking_care` key was incorrect in the yml file, which led to this:

Fix i18n in the update_match_notify email

---

app/mailers/user_mailer.rb
app/views/mailers/user_mailer/update_match_notify.html.haml

This is still possible, until we merge #735
fixes PLACE-DES-ENTREPRISES-4D PLACE-DES-ENTREPRISES-4G

Workaround update_match_notify crashing when there is no current_user

---

app/views/layouts/application.html.haml
app/views/layouts/pages.html.haml
app/views/shared/_user_impersonate.html.haml

Display the “development” and “impersonate” partials in `pages` as well as in the main `application`.

Display ribbons in `pages`

---

app/admin/expert.rb
app/admin/match.rb
app/controllers/application_controller.rb
app/controllers/feedbacks_controller.rb
app/controllers/matches_controller.rb
app/controllers/needs_controller.rb
app/helpers/status_helper.rb
app/models/expert.rb
app/models/match.rb
app/models/user_context.rb
app/policies/application_policy.rb
app/policies/diagnosis_policy.rb
app/policies/feedback_policy.rb
app/views/diagnoses/_diagnosis.haml
app/views/feedbacks/_feedback.haml
app/views/feedbacks/create.js.haml
app/views/matches/_match.haml
app/views/matches/update.js.haml
app/views/needs/_feedback_form.haml
app/views/needs/_need.haml
app/views/needs/_need_content.haml
app/views/needs/add_match.js.haml
app/views/needs/show.haml
config/locales/models.fr.yml
lib/tasks/import_dump.rake
spec/controllers/matches_controller_spec.rb
spec/models/expert_spec.rb
spec/policies/diagnosis_policy_spec.rb
spec/policies/feedback_policy_spec.rb

🔥🔥🔥🔥
Stop using `access_token`, `current_expert` and `current_roles` everywhere.
This finally closes #638.

Stop using access_token

---

Gemfile
Gemfile.lock

1. change our declared dependencies from sass to sassc - it’s actually the same, the sass-rails gem is now just a frontend to sassc-rails.
2. however, semantic-ui-sass still uses the ruby-based sass; 
2.1 switch to the community fork, fomantic-ui-sass
2.2 [make a PR](https://github.com/fomantic/Fomantic-UI-SASS/pull/3) to switch fomantic-ui-sass itself to sassc
2.3 update fomantic-ui-sass once this PR is merged
This means we’re now using fomantic-ui 2.8.4 (from semantic-ui 2.4.2), with a [handful of features](https://fomantic-ui.com/introduction/new.html); the switch to sassc itself may increase performance a little bit, but at this point, even switching to libsass sounds dated. Anyway.

Switch to fomantic-ui (and to sassc)

---

config/initializers/assets.rb

We’re having semi-random crashes in the test suite linking to this issue in sassc:
https://github.com/sass/sassc-rails/issues/122
It is suggested that this line is involved. In any case, it looks like this triggers duplicate precompilation, which (this is a theory) may lead to a race condition.

Remove the assets.precompile line in assets.rb

---

app/assets/stylesheets/pages.sass
app/views/landing_topics/_example_topics.haml
app/views/landings/index.haml
app/views/landings/show.haml
config/locales/views.fr.yml
spec/features/landing_page_feature_spec.rb

followup #781
* Typos:
"answere" -> "answer"
"exemple_topics" -> "example_topics"
* Use the text-center class rather than creating a new css rule
* Fix the else condition ("landing.featured_on_home") in example_topics.haml.
Technically, all landings are currently “featured on home”, so we might as well remove this feature.

Ajustements des pages d’accueil

---

config/routes.rb

* Remove now-unused /conseillers route.
* Reorder in distinct sections (for Pages and Application)
* Tidy up codestyle a bit
The generated routes are the exact same as before (except for the removed /conseillers route). The order changes, but as far as I can tell, there are no ambiguous routes that would be resolved differently.

Cleanup routes.rb

---

app/views/diagnoses/index.haml

We’re still working on the wording.
The new UI can be enabled by adding FEATURE_DIAGNOSIS_WITHOUT_SIRET=true to .env.
In any case, `/analyses/new` is still available.
followup #773

Hide the “diagnosis without siret” form behind an env flag

---

lib/tasks/import_dump.rake

* whitelist ExpertSubject.role, to avoid trying to put a fake string in an enum (an integer in DB)
* (this makes `rake import_dump` crash right now)
* remove deleted attributes,
* fake readable_locality with a postal code, to reflect the behaviour in production

Fixes and improvements in import_dump.rake

---

app/assets/stylesheets/application/diagnoses.sass
app/controllers/diagnoses/steps_controller.rb
app/controllers/diagnoses_controller.rb
app/models/diagnosis.rb
app/views/application/_flashes.html.haml
app/views/diagnoses/steps/_expert_subject_checkboxes.html.haml
app/views/diagnoses/steps/_header.haml
app/views/diagnoses/steps/_steps.haml
app/views/diagnoses/steps/besoins.html.haml
app/views/diagnoses/steps/selection.haml
app/views/diagnoses/steps/visite.html.haml
app/views/shared/flashes.js.haml
config/i18n-tasks.yml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/companies_controller_spec.rb
spec/controllers/diagnoses/steps_controller_spec.rb
spec/controllers/diagnoses_controller_spec.rb
spec/views/diagnoses/steps/step4.html.haml_spec.rb

* move to diagnoses/steps
* rename the GET “stepX” routes to the same routes as the POST routes
* move the partial and rename the i18n keys
This should make things easier for #791 and subsequent redesign of the diagnosis steps.
Additional related changes:
* Define named constants for the 2, 3, 4 diagnosis steps. This is not yet a proper enum, but we’re getting there.
* Fix flash messages not being displayed after remote forms; we still need to use flashes.js.haml, but at least it’s working.

Move the steps routes to a distinct controller and fix flashes

---

app/controllers/experts_controller.rb
config/routes.rb

It only redirects to the first expert, if any. This is temporary for an experiment while we redesign the profile page. (refs #766)

Add a new /mes_competences url

---

app/controllers/matches_controller.rb
app/mailers/user_mailer.rb
config/initializers/core_extensions.rb
lib/core_extensions/delayed/job/remove_jobs.rb
spec/lib/core_extensions/delayed/job/remove_jobs_spec.rb
spec/mailers/user_mailer_spec.rb

Wait one minute before sending `update_match_notify`, and cancel previous email jobs if a new action is taken within the minute.
refs #799

De-duplicate status notification emails

---

app/admin/user.rb

Prevent each User flag to be wrongly interpreted as true in /admin/users. The checkbox form sets the flags values to `0` and `1` but `!!0` is actually true. Let’s use .to_b (from wannabebool instead: 0.to_b is false, 1.to_b is true, and nil.to_b is false.

Fix flags display in /admin/users

---

config/routes.rb

We broke external links in !812

Serve landing pages both on /entreprise and on /aide

---

.rubocop.yml
app/admin/expert.rb
app/admin/user.rb
app/mailers/expert_mailer.rb
app/models/diagnosis.rb
app/models/expert.rb
app/models/user.rb
app/views/mailers/expert_mailer/_never_used_account_warning.html.haml
app/views/mailers/expert_mailer/_never_used_solo_account_warning.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/mailers/expert_mailer/remind_involvement.html.haml
config/locales/devise.fr.yml
config/locales/models.fr.yml
config/locales/views.fr.yml
spec/mailers/expert_mailer_spec.rb
spec/models/diagnosis_spec.rb
spec/models/expert_spec.rb
spec/models/user_spec.rb

This adds `without_users` and `personal_skillsets` scopes and methods to Expert. This will be central to adapt the UI for the different cases in #766.
Additionally, this
* adds a related “without_users” scope
* add team-related scopes in User as well
* adds ActiveAdmin scopes for all these
* removes the old `solo?` method in User and Expert
* refactor Diagnosis/ExpertMailer that was using `solo?`; this changes the behaviour when sending password instructions to users after notifying an expert: we used to only send the password email if the expert only had one user, but in reality we have situations where several users could need it.

Ajout des scopes “équipes” pour /admin/users et /admin/experts

---

app/assets/javascripts/pages.js
app/assets/stylesheets/pages.sass
app/views/landings/_landing.haml
app/views/landings/_landing_details.haml
app/views/landings/index.haml
app/views/landings/show.haml

fixes #839
Also, this enables smooth scrolling to local anchors, and disable turbolinks on local pages.
See https://caniuse.com/#search=scroll-behavior
As of today, only Safari is missing it, but it’s already available in the latest Safari Technology Preview. (IE lacks it completely, but who cares about IE.)
Also disable Turbolinks for public pages, for two reasons:
* Turbolinks messes with smooth scrolling, when going from one page to another with an anchor. Since Turbolinks replaces the <body>, the browser still believes it should be scrolling to the new location from the current location on the old page, which makes no sense. (See https://github.com/turbolinks/turbolinks/issues/181#issuecomment-545084567)
* When clicking a link to the same page with an anchor, turbolinks issues an XHR …

Link directly to the form in the landing pages from the homepage

---

app/admin/patches/data_access.rb

When trying to destroy an object that is still referenced, for example an Institution that still has Antennes, PG will throw an exception and AA will fail and return an `error 500` blank page.
This catches and displays the underlying error; there seems to be no mechanism in AA to handle destroy failures at all. 🤷🏻‍♂️

Display foreign key violations errors in /admin when trying to destroy

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/services/api_entreprise/entreprise_response.rb
app/services/api_entreprise/etablissement_response.rb
app/views/shared/errors/404.html.haml
app/views/shared/errors/500.html.haml
config/locales/fr.yml
config/routes.rb

This is imperfect, but a first step.
- It’s using rubocop, not haml-lint, which means haml files are not verified.
- It uses a regexp to decide if a string looks like human-displayed sentence. The rules are:
> Sentences are determined by the STRING_REGEXP. (Upper case character, at least one space, and sentence punctuation at the end)

Add rubocop i18n

---

app/models/solicitation.rb

Prevent error `undefined local variable or method partner_token' for Solicitation`

add partner_token to FORM_INFO_KEYS

---

app/controllers/shared_controller.rb

Typically, /favicon.ico or requests to /.well-known/<stuff>.json.
PLACE-DES-ENTREPRISES-5E
(In theory, we’re declaring urls for the favicons in the head, but 🤷🏻‍♂️)

Fix handling of 404 for non-html resources

---

app/views/solicitations/canceled.html.haml
app/views/solicitations/index.html.haml
app/views/solicitations/processed.html.haml

Wow that was easy. On my machine, it cuts rendering for `/sollicitations` from 1600-1800ms to 200-300ms, with this nice line in the logs:
```
Rendered collection of solicitations/_solicitation.haml [765 / 765 cache hits] (Duration: 87.9ms | Allocations: 32139)
```
(Small disadvantage: the shorthand syntax for render doesn’t support options.)

Enable collection partial caching in /sollicitations

---

app/views/companies/_search_form.haml
app/views/diagnoses/new.haml

followup #911
fixes PLACE-DES-ENTREPRISES-60
The fix could have been just to add a `&`, but we might as well use `local_assigns` instead of `defined`.

Prevent crashing when starting a new diagnosis without a solicitation

---

app/assets/javascripts/application.js
app/assets/javascripts/pages.js
app/assets/javascripts/shared/checkboxes_require_one.js
app/assets/stylesheets/pages.sass
app/views/diagnoses/steps/selection.haml
app/views/landings/_form.haml
config/locales/views.fr.yml

Demander à sélectionner au moins une option à l’envoi d’une sollicitation

---

config/environments/production.rb

In #913, we use some ✨fancy ES6 javascript✨ syntax, and Uglifier needs to be made aware of this.
The exact command that fails is RAILS_ENV=production bundle exec rake assets:precompile.
The error message is
> Uglifier::Error: Unexpected token: name (boxes_parent). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
In development, Uglifier isn’t used 🤷🏻‍♂️.
See https://github.com/lautis/uglifier/issues/127 for context.

Fix Uglifier complaining about ES6 syntax

---

app/views/solicitations/_tracking.haml

rendering the solicitation 1969 made this crash; i’m not sure exactly why `if solicitation.pk_campaign` was true, while the value in DB was nil. I suspect something with a weird encoding and jsonb storage.
PLACE-DES-ENTREPRISES-5R

Workaround a weird crash in /admin/solicitations

---

app/assets/stylesheets/pages.sass

Not exactly sure why this is iOS only. 🤷🏻‍♂️

Override default button appearances on ios safari

---

app/assets/stylesheets/pages.sass

Remove the red outline around checkboxes in Firefox

---

app/controllers/matches_controller.rb
app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb
app/models/need.rb
app/services/match_mailer_service.rb
app/views/mailers/expert_mailer/notify_other_taking_care.html.haml
app/views/mailers/user_mailer/notify_match_status.html.haml
config/i18n-tasks.yml
config/locales/views.fr.yml
spec/mailers/expert_mailer_spec.rb
spec/mailers/previews/expert_mailer_preview.rb
spec/mailers/previews/user_mailer_preview.rb
spec/mailers/user_mailer_spec.rb
spec/services/match_mailer_service_spec.rb

Nettoyage:
* Suppression de UserMailer.daily_change_update (qui n’était plus utilisé depuis longtemps)
* Unification de CompanyMailer.taking_care_by_expert et CompanyMailer.taking_care_by_support
Correction:
* Dans le mail de notification à l’advisor, ne plus utiliser le nom de l’utilisateur qui change le statut, mais celui de l’expert.
Refactor:
* Déplacement de la méthode de déduplication des emails de notification dans un nouveau service (MatchMailerService)
Amélioration:
* Déduplication du mail de notification de prise en charge aux entreprises (CompanyMailer.notify_taking_care)
Nouveauté (enfin) :
* Envoi d’un mail de notification de prise en charge aux autres experts sur un besoin qui n’ont pas encore répondu. (ExpertMailer.notify_others_taking_care)
closes #799

Envoyer un nouveau mail de notification aux experts quand un autre prend en charge

---

app/admin/helpers/admin_link_to.rb
app/admin/solicitation.rb
app/controllers/landings_controller.rb
app/models/landing.rb
app/models/solicitation.rb
app/views/landings/_form.haml
db/migrate/20200323133834_add_slug_to_solicitation.rb
db/schema.rb

This is done in passing while adding validations to Solicitation. See next PRs :)
This uses the `slug` as the key for the association. The mais problem was to take the slug out of the `form_info` and make it a proper column; the rest is just using the proper options for `has_many` and `belongs_to`.
This also adds indexes for `slug`, which is always a good idea.
---
To be clear: the point is that we can write `solicitation.landing`, or `landing.solicitations` or `Solicitation.all.joins(:landing)`, etc.

Add a formal Landing <-> Solicitation association

---

app/assets/javascripts/shared/checkboxes_require_one.js
app/views/diagnoses/steps/selection.haml
app/views/landings/_form.haml

Who knew you couldn’t run code that was not loaded yet?
🙂 fixes PLACE-DES-ENTREPRISES-6G PLACE-DES-ENTREPRISES-68. (old Chrome and Firefoxes.
🙂This also fixes PLACE-DES-ENTREPRISES-6G, which is the same error but on old Safaris,
🙃 but it still on old Safaris doesn’t work because `setCustomValidity()` doesn’t seem to be supported on Safari 9 (neither is `required = true`). For this, I’m adding server-side validation and proper error reporting in a next PR.
Also, I’m relatively happy with the new selector-based activation: the script is automatically run for elements with the attribute `data-checkboxes-require-one-with`, and the message is also set in that attribute.

Fix error "Can't find variable: checkboxes_require_one"

---

app/views/devise/sessions/new.html.haml
config/initializers/devise.rb

On n’a pas de vraiment bonne raison de limiter les sessions à deux semaines; pour une bonne partie des référents qui ne vient pas souvent, ça annule complètement l’effet de “se souvenir de moi”. Au passage, autant précocher cette option à la connexion.

Garde les sessions utilisateur ouvertes plus longtemps

---

app/controllers/feedbacks_controller.rb

This is the same as #933, but for feedbacks creations 
We have users with IE11 on Windows 7 without javascript 🎉
PLACE-DES-ENTREPRISES-57
This does _not_ make the destroy link work, as this is a method: :delete link backed by rails-ujs.

Make /feedbacks#create work without js

---

app/controllers/diagnoses/steps_controller.rb
app/models/solicitation.rb
config/locales/models.fr.yml
spec/models/solicitation_spec.rb

refs #958. PLACE-DES-ENTREPRISES-71
* The issue was not with the flash, but with the error being an uncatched exception.
(I’m still not quite happy with this section of the app, but it’s one less bug.)
* Also, be slightly less strict when validating selected options in solicitations. If the landing options change after the solicitation is made, we don’t want the solicitation to suddenly become invalid.

Fix error display in diagnosis steps in solicitation is invalid

---

config/locales/devise.fr.yml

This is the error shown when a user tries to login before accepting the invitation.

Add missing i18n for devise.failure.invited

---

app/controllers/landings_controller.rb
app/views/landings/_index_landing_card.html.haml
app/views/landings/_index_landing_cards.html.haml
app/views/landings/_show_solicitation_form.html.haml
app/views/landings/index.haml
spec/features/new_solicitation_feature_spec.rb

* Store form info and campaign params in the session cookie, instead of polluting the url with it. It also turns out to be simpler to manage.
* Improve New Solicitation Feature spec to actually check that the solicitation params (including the tracking params) are saved.
(This helps for #939)

Use the session cookie for form_info

---

Gemfile
Gemfile.lock

Don’t really bump it: rspec-rails 4 has been released, we don’t need to reference the branch explicitely anymore. (We need rspec-rails 4 for rails 6)

bump rspec-rails gem

---

app/admin/solicitation.rb
app/models/landing.rb
app/models/landing_option.rb
app/models/solicitation.rb
app/views/landings/_show_solicitation_form.html.haml
app/views/solicitations/_solicitation.haml
config/locales/models.fr.yml
config/locales/views.fr.yml
db/migrate/20200331125244_change_landing_option_slug_to_title.rb
db/migrate/20200331132751_change_solicitation_selected_options.rb
db/schema.rb
spec/features/new_solicitation_feature_spec.rb
spec/models/solicitation_spec.rb

Preparation for #940, but il will also help for #949. First item of #952, as well.
* Make proper slugs and titles for LandingOptions 
* move the current slug to title, and a parameterized version of it to slug
* make the slug nonnull
* Use an array of selected options slugs instead of a hash
* Deprecate solicitations.options (to options_deprecated)
* Move the chosen keys to the new array
* Also rename solicitations.slug to landing_slug and make it nonnull
* Revert 536d6fdba9c6e59d6a749bf537fb02e74babec68 Tweak selected options validation in solicitation. 
* Validate Solicitation.landing actually exists on create
* Add a column per landing slug in the solicitations csv (#952)
--- 
Can I say I enjoy using a postgresql array of slugs to define a has_many relation?

Améliorations des relations Solicitations-LandingOptions

---

Gemfile.lock

followup #985
This fixes this warning in the console:
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.5-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(This has no consequences, apart from being annoying)

Bump the parser gem after ruby upgrade to 2.6.6

---

app/admin/expert.rb

refs #991; apparently we don’t have bad data in production, but it happens in local. (yet?)

Avoid crashing when encountering baddata in Experts

---

app/admin/solicitation.rb

It’s possible for landing_options_slugs to be nil (not just empty), and it happens if the landing has no options.

Avoid crashing in solicitation csv export when no options are selected

---

app/assets/javascripts/application/semantic-ui.js
app/assets/stylesheets/application/semantic-ui_extensions.sass
app/assets/stylesheets/application/solicitation.sass
app/views/application/_navbar.html.haml

Deux corrections:
1. amélioration du css pour le menu Sollicitations, qui est à la fois un entête de menu et un lien cliquable. Il faut que le `dropdown` soit `item`, pas le `a`; cependant, ce n’est pas complètement géré par fomantic-ui et le lien reste bleu par défaut.
2. Changement du sélecteur pour activer le dropdown js de fomantic-ui, pour ne pas le faire sur les dropdown `.simple` (justement comme celles de la navbar)

Correction des menus déroulants dans la barre de navigation

---

app/assets/stylesheets/application/diagnoses.sass
app/controllers/companies_controller.rb
app/controllers/diagnoses/steps_controller.rb
app/controllers/diagnoses_controller.rb
app/controllers/stats_controller.rb
app/models/diagnosis.rb
app/views/diagnoses/steps/matches.html.haml
app/views/diagnoses/steps/needs.html.haml
app/views/diagnoses/steps/visit.html.haml
config/i18n-tasks.yml
config/locales/views.fr.yml
config/routes.rb
spec/controllers/companies_controller_spec.rb
spec/controllers/diagnoses/steps_controller_spec.rb
spec/controllers/diagnoses_controller_spec.rb
spec/models/diagnosis_spec.rb
spec/models/need_spec.rb
spec/models/user_spec.rb
spec/views/diagnoses/steps/matches.html.haml_spec.rb

* remove the “same path” routes for post and get, that was dumb
* stop using flashes.js, just redirect (and let turbolinks do its thing)
* remove a forgotten version of `checkboxes_require_one` in the needs step
* use diagnoses step enum names instead of magic numbers
* add a new diagnoses validation to ensure needs are selected in the needs step (it‘s already done in the frontend anyway)
This is in preparation for #940

Refactor StepsController before preselection

---

app/helpers/solicitation_helper.rb
app/views/solicitations/_solicitation.haml

refs #940
Ça ne sera pas essentiel, une fois la fonctionnalité complète, mais ça aide à comprendre ce qui se passe. baby steps, tout ça.

Afficher l’institution et le sujet préselectionné dans /sollicitations

---

app/controllers/diagnoses/steps_controller.rb

Only prefill the form with the solicitation info if the visitee hasn’t been filled yet.

Fix Diagnosis#visite overwriting the visitee info with the solicitation

---

app/mailers/user_mailer.rb

See also #991: when we’re able to soft-delete experts, this can be removed.

Fix match_feedback following #1022

---

lib/tasks/expert_to_user_for_feedbacks.rake

references #1023
Premier parti avant de pouvoir supprimer les champs en base. Après cette tache il reste une centaine de commentaires sans utilisateur, Mathieu m'a donné les noms pour chaque expert

Ajoute une tache rake pour ajouter un user aux commentaires qui n'en on pas

---

app/controllers/companies_controller.rb
app/controllers/diagnoses/steps_controller.rb
app/controllers/diagnoses_controller.rb
app/models/concerns/diagnosis_creation.rb
app/models/diagnosis.rb
app/models/facility.rb
app/views/application/_insee_code_field.html.haml
app/views/companies/show.html.haml
app/views/diagnoses/new.haml
app/views/diagnoses/steps/visit.html.haml
config/routes.rb
spec/controllers/companies_controller_spec.rb
spec/controllers/diagnoses/steps_controller_spec.rb
spec/controllers/diagnoses_controller_spec.rb
spec/models/facility_spec.rb
spec/views/companies/show.html.haml_spec.rb

Prepare for #940: move the diagnosis creation to a diagnosis_creation concern
1. Add insee_code getter and setter to facility
* implicitly fetch the geo api for details
2. Unify the diagnosis create methods and better params
* Use diagnosis#create instead of company#create_diagnosis_from_siret and diagnosis#create_diagnosis_without_siret
* Nest attributes for diagnosis.facility and facility.company
* Use local forms for now, so that _at least_ errors get displayed. We’ll do some js magic another time.
* That’s a step from from returning 400 with no content
* In company#show, use a proper form, instead of an implicit link_to form. Additionally, it’s more elegant for the hidden parameters.
* The other advantage is that diagnosis creation errors, now, are always validation errors and can be …

Refactor diagnosis create methods

---

app/admin/need.rb
app/models/need.rb
app/views/diagnoses/_diagnosis.haml
config/locales/models.fr.yml
lib/tasks/fixup_updated_at.rake
spec/factories/feedbacks.rb
spec/lib/tasks/fixup_updated_at_rake_spec.rb
spec/models/need_spec.rb

Related to #1023, #1024 and #940: this is moving a lot these days.
1. A rake task to fix and cleanup the updated_at values, following accidents and refactors (we have some baddata)
2. Removal of Need.last_activity_at, now that we can just use Need.updated_at. It was always clumsy.
WIP:

Cleanup updated_at, touches, and last_activity_at

---

app/controllers/diagnoses/steps_controller.rb
app/models/diagnosis.rb
app/models/need.rb
app/views/diagnoses/steps/_expert_subject_checkboxes.html.haml
app/views/diagnoses/steps/matches.html.haml
spec/controllers/diagnoses/steps_controller_spec.rb
spec/models/diagnosis_spec.rb

refs #940
* Refactor Steps#updates_matches parameters: 
* Use nested attributes, instead of a custom serialization
* Preselect diagnoses matches by actually creating matches
* Instead of just pre-checking the boxes in the UI. This means creating matches before sending the notifications!
After this change, all the automatic selection to diagnoses is done in the get actions of steps_controller; we now just have to move it all to methods in DiagnosisCreation.

Create matches before sending notifications

---

app/controllers/diagnoses/steps_controller.rb
app/models/concerns/diagnosis_creation.rb
config/locales/models.fr.yml
spec/controllers/diagnoses_controller_spec.rb
spec/models/concerns/diagnosis_creation_spec.rb

more refactor for #940:
* split creation tests for diagnoses between controller related tests (i.e. http responses) and actual creation code
* in the visit step, _actually_ create the visitee in db using the details from the solicitation. This is in line with the behviour for the needs and matches steps.
* do not mark the solicitation as “processed” before the diagnosis is completed and the notifications are sent.

More refactor for diagnosis creation

---

app/models/clockwork.rb
app/services/admin_mailers_service.rb

broken in #738 (4 months ago.)
There are two bugs, and we never found out because we don’t have sentry running on clockwork.
* In clockwork.rb, we can’t use `deliver_later` for AdminMailersService.send_statistics_email and ExpertReminderService.send_reminders: deliver_later is a method of ActionMailer, the service methods don’t return mailers. They are simply meant to be run as regular jobs. Changing it in #738 was a mistake.
* For ExpertReminderService.send_reminders, this is not really a problem: the service method enqueues the mailer jobs, and returns an array; after that, the calling method in clockwork.rb crashes, but the actual mailer jobs are enqueued.
* In AdminMailersService.send_statistics_email, there is another unrelated issue: we’re using ActiveJob’s deliver_later to enqueue, …

Fix weekly_statistics email delivery

---

app/controllers/diagnoses/steps_controller.rb
app/models/concerns/diagnosis_creation.rb

Fixup after #1071 and #1066
I should have read the doc better:
> The create_association method returns a new object of the associated type. This object will be instantiated from the passed attributes, the link through this object's foreign key will be set, and, once it passes all of the validations specified on the associated model, the associated object will be saved.
“The _associated_ object will be saved”, not the origin object of the relationship. In our case, that means the Contact was saved, but not the Diagnosis. I actually had changed the code the other way round because it seemed better to juste call create, instead of build and save.
🤷🏻‍♂️

Fixup for automatic visitee creation (prepare_visitee_from_solicitation)

---

app/controllers/diagnoses_controller.rb
app/controllers/needs_controller.rb
app/models/diagnosis.rb
db/migrate/20200527114540_tweak_diagnosis_belongs_tos.rb
db/schema.rb
spec/models/diagnosis_spec.rb

refs #940: when we create diagnoses automatically for received solicitations, there is no _current_user_ making the diagnosis.
This is WIP: Apparently, there is no place in the app when we try to display the diagnosis’ advisor before the diagnosis is complete, but I want to make some more tests.

Make diagnosis advisor optional

---

app/controllers/landings_controller.rb
app/controllers/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/models/concerns/diagnosis_creation.rb
app/models/solicitation.rb
app/views/solicitations/_solicitation_actions.html.haml
config/application.rb
config/brakeman.ignore
config/locales/models.fr.yml
config/locales/views.fr.yml
config/routes.rb
db/migrate/20200528151220_add_diagnosis_errors_to_solicitation.rb
db/schema.rb
spec/models/concerns/diagnosis_creation_spec.rb

refs #940
Si un diagnosis peut être préparé automatiquement, le bouton “démarrer une analyse” est remplacé par celui-ci:
Si la préparation échoue, par exemple parce que le SIRET est invalide ou qu’aucun référent de l’institution préselectionné n’est sur la zone de l’entreprise, un message d’erreur s’affiche:
Une fois l’analyse préparée, le bouton devient “Analyse en cours”. La sollicitation reste dans l’onglet “à traiter”: 
Pour les autres sollicitations, où la préparation automatique est impossible, le bouton “Démarrer une analyse” continue d’exister.

Prepare diagnosis

---

app/models/need.rb
db/migrate/20200603115449_add_last_activity_at_to_needs.rb
db/schema.rb
spec/models/need_spec.rb

closes #1097 
@n-b je me souviens qu'on s'était dit qu'on avait peut-être cassé quelque chose en ajoutant `touch: true` sur la relation d'un commentaire et d'une analyse. Et c'est le cas, il ne faut pas que les analyses sortent de l'onglet "relance" quand un commentaire est ajouté. Et j'ai l'impression que ce n'est pas utile non plus sur les sollicitations, mais je rate peut-être quelque chose

Ne pas sortir les analyses des relances quand un commentaire est déposé

---

app/views/shared/_user_impersonate.html.haml
config/initializers/user_impersonate.rb

* corrige le bouton retour depuis les pages public du site (PLACE-DES-ENTREPRISES-74)
* retour sur la page de l’utilisateur en question, plutôt que sur /admin/users (qui est longue à charger, en plus)

Amélioration au retour de “voir le site comme…”

---

app/models/need.rb

When two or more matches are created, the after_touch callback is triggered once for every match; as the other matches are not persisted yet, their :updated_at value is nil.
followup #1098 PLACE-DES-ENTREPRISES-8B

Fix a crash when creating several matches for the same need

---

app/models/expert.rb
app/models/user.rb
spec/factories/diagnoses.rb
spec/factories/matches.rb
spec/factories/needs.rb
spec/models/need_spec.rb

That way, all the through relations that rely on Expert#received_matches are filtered too:
* Expert.received_needs
* Expert.received_diagnoses
* User.received_matches
* User.received_needs
* User.received_diagnoses
followup #1115, PLACE-DES-ENTREPRISES-88

Filter sent matches in Expert#received_matches

---

app/controllers/shared_controller.rb

followup #1101
TLDR: Basically, our custom error rendering (in SharedController#render_error) gets in the way of the normal Rails handling. We should get rid of it.
We're getting requests for sitemap.txt. The only supported type is xml, and a ActionController::UnknownFormat exception is raised. According to [the docs](https://apidock.com/rails/ActionController/ImplicitRender) (See also this [relevant PR](https://github.com/rails/rails/issues/20666),  this should result in a 406. However, we rescue in render_error: our handler can only return 404 ou 500, and only returns 404 for a very specific set of errors, so our 406 is changed to a 500.
In fact, this facility shouldn’t even exist. Our custom 404 and 500 pages were maybe meant to be customised at some point, but they are not. We should …

Don't log sentry errors for sitemap queries of the wrong type

---

app/services/csv_export/models/match.rb
app/services/csv_export_service.rb

running `RAILS_ENV=production rails s` failed with
```
.../gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `const_get': uninitialized constant CsvExport::Models::Match (NameError)
Did you mean?  CsvExport::Match
Math
```

Fix zeitwerk complaining about wrong required modules

---

app/views/landings/_show_landing.html.haml
app/views/landings/show.haml

Ils n'étaient par réellement pris en compte: le code ruby `meta` n'est pas appelé si le cache du template est utilisé (c'est-à-dire la plupart du temps, en principe!)
fait en passant pour #1127

Corrige les meta description et title sur les landing pages

---

app/admin/landing.rb
app/assets/javascripts/pages/iframe_external_links.js
app/controllers/concerns/iframe_prefix.rb
app/controllers/landings_controller.rb
app/controllers/shared_controller.rb
app/models/landing.rb
app/views/external_solicitations/new.haml
app/views/landings/_new_solicitation_form.html.haml
app/views/landings/_show_landing.html.haml
app/views/landings/index.haml
app/views/landings/new_solicitation.html.haml
app/views/landings/show.haml
app/views/layouts/pages.html.haml
config/routes.rb
spec/views/iframe_test_page.html

Plus gros morceau de refs #1094.
Le concern IframePrefix permet de servir toutes les actions de `landings` avec un préfixe optionnel `/w`. S’il est présent, alors `in_iframe?` devient true, ce qui permet de faire un layout différent, d'ajuster les options et les urls des liens. La difficulté principale est de s'assurer que les liens générés gardent le préfixe `/w` quand on va d'une page à l'autre, mais pas pour les liens sortants.
En bonus:
* Une page html pour tester l'iframe. On peut l'ouvrir telle quelle, mais Rubymine propose en menu contextuel “Open in browser”, qui crée en fait un mini serveur web local: c‘est sans doute plus réaliste.
* un mini fix de layout pour external_solicitations, même si c’est temporaire

Permettre de servir toutes les pages de landing dans un iframe

---

config/environments/production.rb

PORT isn't set in production environment, which leads to urls ending with a weird `:0`.

Do not include the port number in urls in production

---

Gemfile
Gemfile.lock
app/views/landings/_newsletter.html.haml
app/views/layouts/pages.html.haml
app/views/shared/_environment_ribbon.html.haml
spec/a11y/a11y_spec.rb
spec/spec_helper.rb
spec/support/axe/matchers/be_accessible.rb

Add `axe-matcher` and basic automated accessibility tests for `/` and landing pages.
refs #1102

First automated a11y tests

---

app/mailers/admin_mailer.rb

The correct way to add attachments is `attachments[file_name] = …` 🤷🏻‍♂️

Don’t pass the CSV attachment in the mail header

---

Gemfile
spec/models/badge_spec.rb
spec/models/feedback_spec.rb
spec/models/need_spec.rb
spec/spec_helper.rb

We don’t need Timecop’s advanced features, and travel_to complains when nesting travels, which is actually helpful.

Use ActiveSupport’s travel_to instead of Timecop

---

app/assets/stylesheets/pages.sass
app/assets/stylesheets/pages/landing.sass
app/assets/stylesheets/pages/section_examples.sass
app/views/landings/_new_solicitation_form.html.haml
app/views/landings/new_solicitation.html.haml
spec/views/iframe_test_page.html

* Tweak the iframe test page to look like what our partners are doing
* Fix layout for links in landing topics contents. This broke in the coronavirus page, where we had lots in a links in the topics contents.
* Fix form width when in-iframe. We had conflicting rules overriding each other for the form margin

Landing css tweaks

---

app/views/landings/new_solicitation.html.haml
spec/a11y/a11y_spec.rb

Je pense qu’on peut clôturer #1102 avec ça.
(Il y avait une broutille sur la page `/demande`, sans landing_option, ce qui donnait un `h1` vide. C’est corrigé.)

Ajout d’un test d’accessibilité sur la page formulaire

---

app/models/solicitation.rb

Fixup #1165
The fields are required when the user submits the solicitation; afterwards, anything can happen. Also, we have tons of legacy data.

Only require solicitation fields on creation

---

app/controllers/needs_controller.rb

À l'ajout d'experts additionnels pour un besoin existant, ne pas proposer les experts sans sujets (typiquement, les personal_skillsets de membres d’équipes).

Ne par proposer d’ajouter les experts sans sujets

---

app/helpers/person_helper.rb
app/views/diagnoses/_related_diagnoses.html.haml
config/locales/views.fr.yml

Ajoute un bouton vers l'analyse associée plutôt qu'une zone cliquable pas intuitive. 
Corrige un bug de turbolink qui ne scrollait pas vers la sollicitation au clic sur "Sollicitation liée"
closes #1191

amélioration des liens vers les sollicitations et analyses précédentes pour une même personne

---

app/controllers/needs_controller.rb
app/views/diagnoses/_diagnosis.haml
app/views/needs/_needs_antenne_tabs.html.haml
app/views/needs/_needs_tabs.html.haml
app/views/needs/index.html.haml
config/locales/views.fr.yml

Affiche le nombre de demandes dans l'onglet et supprime les tags "pris en charge" quand c'est par un autre conseillé
closes #1194

Diagnosis status

---

app/controllers/needs_controller.rb
app/helpers/status_helper.rb
app/policies/match_policy.rb
app/policies/need_policy.rb
app/views/matches/_match.haml
app/views/needs/_archive.haml
app/views/needs/_need.haml
config/locales/views.fr.yml
config/routes.rb

Permet de clôturer un besoin ou le mettre en échec quand on est admin
closes #1192

Cloturer / Mettre en échec depuis l'onglet relance

---

app/views/matches/_match.haml

Affiche le nom de l'antenne au lieu de l'institution sur la fiche entreprise

---

lib/tasks/import_dump.rake

It was also necessary to reconfigure the CLI:
> scalingo config --region osc-fr1
see also #1213

Change the DB name after the scalingo region migration

---

app/assets/stylesheets/application/semantic-ui_extensions.sass
app/views/institutions/_advisors_table.html.haml
app/views/institutions/advisors.html.haml

I haven’t found a simple way to make the table visually overflow, but have the whole layout scroll (which was already the behaviour in Safari). Well, that’ll do.
fixup #1223

Make sure very wide tables can scroll

---

app/admin/expert.rb

Introduced in #1186: we need to choose between all the institutions subjects, not just the current expert's subjects.

Fix Subjects selections in /admin/experts

---

app/admin/match.rb

Following #1215
ActiveAdmin (Formtastic, really) doesn’t like real enum types. I considered implementing EnumInput as per https://github.com/formtastic/formtastic/issues/718, but  really I don’t want to go there. Also, it’s an issue from 2011.

Fix admin/match status edition

---

app/assets/javascripts/application/semantic-ui.js
app/controllers/institutions_controller.rb
app/models/concerns/many_communes.rb
app/models/expert_subject.rb
app/models/institution_subject.rb
app/policies/institution_policy.rb
app/services/csv_export/models/user.rb
app/services/csv_import/antenne_importer.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
app/views/institutions/_advisors_table.html.haml
app/views/institutions/_antennes_table.html.haml
app/views/institutions/_import_errors.html.haml
app/views/institutions/import_advisors.html.haml
app/views/institutions/import_antennes.html.haml
config/locales/fr.yml
config/locales/views.fr.yml
config/routes.rb
spec/models/concerns/many_communes_spec.rb
spec/models/expert_subject_spec.rb
spec/models/institution_subject_spec.rb
spec/services/csv_import_service_spec.rb

fixes #1119 and 1243
* Finish tests
* Additional Features (maybe in another PR)
* Subjects matching
Both involve reworking UserImpoerter#subjects_mapping. We also want to return an error if both the unique Subject column and subject-specific column are present
* UI (in another PR)
* Cleanup (in another PR)
* Make the importer and exporter similar, as much as reasonable
* Move them together in a CSVIO namespace
* Move the “serialized_identifier” and “serialized_description” methods to the CSVIO namespace

Import CSV des antennes et conseillers 

---

app/admin/expert.rb
app/models/institution.rb
app/models/user.rb
app/services/csv_import/base_importer.rb
app/services/csv_import/user_importer.rb
spec/models/institution_spec.rb
spec/services/csv_import_service_spec.rb

Suite de #1225, refs #1253
* Subjects matching

Import improvements

---

app/models/solicitation.rb

Solicitation search is currently crashing, PLACE-DES-ENTREPRISES-A0.
Introduced in fc9dac1e6552b29be1c0ceec43e79bbb9e723fb5 (part of #1267), the feedbacks table is joined, and this introduces an ambiguity with the “description” column name.

Fix solicitation search

---

app/views/landings/_new_solicitation_form.html.haml
config/i18n-tasks.yml
config/locales/models.fr.yml
config/locales/views.fr.yml

fixes #1280
Also move the landing attributes i18n to views.fr.yml, separate from the attributes placeholders used for the user/login forms.

Add a help comment to find one’s SIRET

---

app/controllers/users/registrations_controller.rb
app/models/user.rb

But not users themselves: :email isn’t a permitted parameter in registrations_controller.
This behaviour was introduced in f6120b404f2eea22146643a3ce73d9e0e5c42f31 in #837.
refs #1285, later.

Allow admins to change user emails

---

app/admin/institution.rb
app/admin/landing.rb

`find_by_slug!` raises an ActiveRecord::RecordNotFound, while `find_by_slug` returns nil if not found, which, in ActiveAdmin triggers another exception later. (namely, "NoMethodError: undefined method `slug' for nil:NilClass").
RecordNotFound is properly returned as a 404 error, while NoMethodError is returned as a 500 :(
fixes PLACE-DES-ENTREPRISES-A8 and PLACE-DES-ENTREPRISES-A7

Properly raise a 404 with custom ActiveAdmin finders

---

app/services/csv_import/user_importer.rb
spec/services/csv_import/user_importer_spec.rb

When importing users of a same team, the subjects are set on the team. Typically, partners will provide csv with each member of the team having only their subject selected. The team must have all the subjects of its members.
This also means that when importing users, we only add subjects, never remove them.
fixes #1310
~~WIP:~~

Merge the subjects of individual users in a team

---

app/controllers/institutions_controller.rb
app/helpers/nested_errors_helper.rb
app/services/csv_import.rb
app/services/csv_import/user_importer.rb
app/views/institutions/_import_errors.html.haml
spec/services/csv_import/user_importer_spec.rb

* réajout des colonnes de l’équipe à l’export (fixes #1327)
* correction de l’union des sujets des différents membres d’une équipe (#1327 aussi, et dû à #1311)
* corrections sur l'affichage d'erreurs à l’import
* parfois, l’import échouait et on n’avait pas d’erreur affichées. c’était du au fait qu’on _re_ validait les objets pour afficher les erreurs, mais parfois, la re-validation ne donne pas les mêmes erreurs que la validation pendant l’import.
* ajout d’un filet de sécurité à l’affichage des erreurs récursives

Correction sur l’import/export CSV

---

app/mailers/expert_mailer.rb
app/services/expert_reminder_service.rb
spec/mailers/expert_mailer_spec.rb

Cf 2e point de #1334 : met à jour les scopes pour les envois d'email pour ne rien envoyer aux utilisateurs soft-deleté

Ne pas envoyer d'email aux comptes supprimes #1334

---

app/views/landings/_index_landing_cards.html.haml
config/locales/views.fr.yml

- N'affiche pas la landing mise en avant sur la home si c'est une iframe. Par contre il faudra peut-être réfléchir à une solution pour l'afficher sur certaines iframes
- Affiche un texte différent en dessous des landings topics si c'est une iframe qui redirige vers le formulaires "/e/aide-entreprises/contactez-nous/demande/autre_demande"
- Met à jour le texte d'aide au remplissage de la description d'une sollicitation

petits ajustements pour les iframes

---

app/admin/expert.rb
app/admin/user.rb
config/locales/models.fr.yml

Change the way the flags are set and cleared in admin for Users and Experts.
Instead of dynamically building batch and item actions, just build one batch action with form_options. It’s not used very often, and it’s less fragile.
(Done in passing for #1348; this isn’t really related but I was there.)
Avant:
Après:

Remove some dynamic magic for User and Expert options in activeadmin

---

app/models/need.rb
config/locales/models.fr.yml
spec/models/need_spec.rb

Corrige un bug sur le scope `abandoned` des besoins ça prenait les besoins sans activité depuis 15 jours, mais si on laisse un commentaire ça modifie cette date depuis que l'ona  ajouté le `touch: true`. Ce qu'on veut c'est les besoins sans prise en charge dans les 15 jours.
closes #1360

corrige le scope des besoins abandonnés 

---

app/views/mailers/company_mailer/newsletter_subscription.html.haml
config/routes.rb

fixes #1388
* send the correct url in the new emails
* redirect the failing url to the correct url

Fix Newsletter url

---

app/admin/match.rb
app/assets/javascripts/application/semantic-ui.js
app/assets/stylesheets/application/diagnoses.sass
app/assets/stylesheets/application/needs.sass
app/controllers/diagnoses/steps_controller.rb
app/models/concerns/diagnosis_creation.rb
app/models/diagnosis.rb
app/models/need.rb
app/models/solicitation.rb
app/models/theme.rb
app/services/csv_export/match_exporter.rb
app/views/diagnoses/steps/_next_step.haml
app/views/diagnoses/steps/needs.html.haml
app/views/diagnoses/steps/visit.html.haml
app/views/mailers/expert_mailer/notify_company_needs.html.haml
app/views/needs/_need_header.haml
app/views/needs/_visit_summary.haml
config/locales/views.fr.yml
spec/mailers/previews/expert_mailer_preview.rb

- Réduit tous les thèmes sur /analyses/:id/besoins pour ne laisser ouvert que celui qui a le sujet pré-sélectionné et ajoute un bouton "passer à la suite" sur chaque thème pour éviter d'avoir a scroller en bas du formulaire
- passe l'étape "visite" si une sollicitation est liée et si une `diagnosis.visitee` est présente
- dans l'export CSV des matches affiche la description de la sollicitation s'il y en a une
- affiche la description de la sollicitation en dessous du titre du besoin, juste au-dessus des commentaires
- affiche les analyses précédentes sur l'écran de choix des sujets si une entreprise a déjà fait l'objet d'analyses
- dans l'email aux experts afficher la description de la sollicitation s'il y a lieu
closes #1366
closes #1028

Accélère la création d'analyses

---

app/front/javascripts/pages/siret_autocomplete.js

Webpack est + intransigeant sur l'écriture du js. C'était un `let` manquant qui bloquait la recherche par siren

Fix missing let

---

app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders/reminders_controller.rb
app/models/need.rb
app/views/reminders/_menu.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/models/need_spec.rb

- ajout du panier "A rappeler (J+14)
- ajustement des delais de relances des paniers contigus
- suppression du "panier" "Relancés"
- ajout d'une base de test pour les paniers relance, basée sur https://docs.google.com/document/d/1vNTpNEdgmacCoAp1yw_MMaTI5PgOEFGMvGI3t-xZrQQ/edit, à compléter une fois la jonction faite avec https://github.com/betagouv/place-des-entreprises/pull/1403
- suppression de tests caducs
closes #1380

Panier a rappeler

---

app/models/need.rb
spec/controllers/diagnoses/steps_controller_spec.rb

Fixes #1421
The `update(status:...)` actually failed, because of a validation error in matches. It was due to this validation in Match:
```
validates :expert, uniqueness: { scope: :need_id, allow_nil: true }
```
This code is called in a weird context: we’re actually updating diagnosis params from StepController#update_matches, and the matches `touch`es back the Need. It seems that Need.update tries to validate the in-memory matches objects, but fails because the same data is already in database, and it doesn’t know it’s actually the same record.
Anyway. Nothing that a .reload can’t fix. 🤷‍♀️

Make sure Need#update_status works correctly after the matches are made

---

app/models/need.rb
spec/models/need_spec.rb

Ce scope est censé définir si un besoin a reçu de l'aide ou pas pour les relances mais ils y a plusieurs cas de besoins qui passent à la trappe

met à jour et test le scope no_help_provided

---

doc/02-development.md
lib/tasks/import_prod_to_staging.rake

- tâche pour importer en staging la BDD de prod
- la première partie est très similaire à `import_dump.rake` mais pas tout à fait -> format restorable de l'import.
- il y a sûrement une refacto à faire entre les 2 tâches, mais comme cette histoire m'a déjà passablement épuisée j'ai pas eu le courage

Import prod to staging

---

app/models/need.rb
spec/models/need_spec.rb

Visiblement on avait oublié un cas de figure, par exemple dans le panier +21 jours si un besoin avec déjà été marqué dans un panier précédent il apparaissait quand même, même s'il était marqué +21. Du moment qu'un de ces `reminders_actions` avait une autre catégorie que celle du panier.

excludes needs when there is at least one reminders action with category

---

app/models/need.rb
spec/models/need_spec.rb

Fixup for #1427. If at least one match is done_no_help or done_not_reachable, the status should reflect it.
⚠️ 🧹The rake task needs to be run in production after deployment.
```
rake update_needs_status
```

🧹 Fix the priority for done_no_help and done_not_reachable

---

app/controllers/reminders/base_controller.rb
app/controllers/reminders/experts_controller.rb
app/controllers/reminders/needs_controller.rb
app/controllers/reminders_actions_controller.rb
app/helpers/application_helper.rb
app/helpers/badges_helper.rb
app/models/expert.rb
app/models/need.rb
app/views/application/_navbar.html.haml
app/views/reminders/_menu.html.haml
app/views/reminders/experts/_header.html.haml
app/views/reminders/experts/_menu.html.haml
app/views/solicitations/_menu.html.haml
config/locales/views.fr.yml
config/routes.rb
spec/models/need_spec.rb

C’est un peu gros, mais ça se lit bien commit par commit. Il y a plusieurs points pour #1323 et #1367:
* tweaks de UI (en principe, ce sont les seuls changements visibles)
* ajouts de redirections (de /relance vers /relances/besoins, principalement) et d’une route spécifique pour “to_poke” plutôt que d’utiliser :index.
* ajout d’un helper `menu_link_with_count`
* nettoyage des actions, des routes et des scopes pour coller aux noms des reminder_actions (poke, call, warn et archive)
* refactor des scopes et des délais par panier
Ça ne prend pas en compte toutes mes questions encore en cours sur need.status. À suivre :)

Simplification des scopes pour les paniers

---

app/assets/stylesheets/application/needs.sass
app/controllers/needs_controller.rb
app/views/diagnoses/_diagnoses.haml
app/views/diagnoses/_diagnosis.haml
app/views/diagnoses/index.haml
app/views/diagnoses/index_antenne.haml
app/views/feedbacks/_feedback.haml
app/views/feedbacks/create.js.haml
app/views/matches/_match.haml
app/views/matches/update.js.haml
app/views/needs/_need.haml
app/views/needs/_need_content.haml
app/views/needs/_received_needs.haml
app/views/needs/add_match.js.haml
app/views/needs/show.haml
app/views/reminders/_diagnosis.haml
app/views/reminders/_needs.html.haml

2ème partie de #1367. Sauf erreur, on a plus utilisé `highlighted_experts` et `needs_of_interest` depuis le redesign de la page /relances, voire déjà avant.

Remove old unused params

---

app/services/stats/companies_by_employees_stats.rb

@LucienMLD 
Il y avait un problème d'affichage dans les mini-stats (j'en parle dans la revue de ta derniere PR stats, mais j'ai découvert que le bug était déjà présent avant ça.
Pour le corriger, j'ai enlevé un bout de code, vérifié que les stats publiques continuent bien de s'afficher et que les tests pêtent pas. 
Je te laisse vérifier (j'ai aucune idée d'à quoi ce bout de code servait, donc j'espère pas avoir commis d'impair)

Remove count false for CompaniesByEmployeesStats

---

app/views/stats/_stats_params.haml

Manifestement il y avait des bugs d'utilisateurs qui voyaient le filtre institution. J'ai essayé de faire des tests de vues en essayant de passer le current_user pendant 1h sans succès. je me suis dit que `current_user.is_admin?` ça fonctionnera à tout les coups

cache le filtre sollicitation pour les non admin (encore)

---

app/services/company_mailer_service.rb

Il y avait un soucis avec la méthode utilisée pour repérer si un contact était présent dans une liste de contacts sendinblue. 
Avec la nouvelle méthode ça devrait aller mieux
closes #1504

Correction bug sib compant mailer

---

app/admin/delayed_job.rb

This is a bit unfortunate. Starting in Rails 6.1, this crashes at lauch in production:
```
/Users/nicolas/Documents/place-des-entreprises/app/admin/delayed_job.rb:3:in `<main>': uninitialized constant Delayed::Job (NameError)
```
It seems that the Delayed::Job symbol is actually created dynamically when the backend for the ActiveJob is set; if the ActiveAdmin page is executed first, the Delayed::Job symbol doesn’t exist.
The workaround is to specify explicitly the actual backend class; it should be _the same thing_.
I’m not exactly sure why this started to fail now.

Explicitly specify the Delayed::Job backend for the ActiveAdmin page

---

config/environments/development.rb
config/environments/test.rb
config/initializers/core_extensions.rb

* followup #1494: tweak the loading of HumanCount some more; this time following the docs and the warning message.
* use i18n.raise_on_missing_translation instead of action_view.raise_on_missing_translations; that’s Rails 6.1

Fix Rails loading deprecations

---

app/views/diagnoses/_diagnoses.haml

Remove the unused partial diagnoses/_diagnoses.haml

---

app/models/antenne.rb
app/models/institution.rb
app/models/institution_subject.rb
app/models/theme.rb
app/views/application/_navbar.html.haml
app/views/solicitations/index.html.haml
db/migrate/20210125130337_add_index_to_updated_at_for_cache_keys.rb
db/schema.rb

A bunch of commits from a forgotten branch, done mostly while working on /annuaire.
* Add Indexes for “updated_at” attributes used for fragment caching: if we’re using `max(updated_at)` in sql queries, it better be indexed.
* Cleanup another use of fragment caching: there is no point in computing `Badge.maximum(:updated_at)` ourselves: rails caching knows to do it itself when we pass the Relation as a cache key.
* Also cache the need badge indicator in the navbar.

Fragment caching improvements

---

app/models/concerns/diagnosis_creation.rb

* Move get_solicitation_description inside the module
* prepare matches without preselected institutions. The condition was added in #1375, I’m not exactly sure why; anyway, this is supposed to fail if no match is found. 🤷

Cleanup diagnosis creation

---

app/models/need.rb
app/views/reminders/_diagnosis.haml
app/views/reminders/experts/_expert_contents.haml
spec/views/reminders/needs/index.html.haml_spec.rb

Correction des erreurs d'affichage et de décompte des relances, avec test basique
Tests à compléter : les tests de views ne prennent pas le `layout` ni les `content_for`, donc ici les chiffres afffichés dans la colonne du menu ne sont pas testés. Pas pris le temps de creuser comment les tester en même temps.

Fix reminders counts

---

Gemfile
Gemfile.lock
app/models/antenne.rb
app/models/concerns/person_concern.rb
app/models/institution.rb
spec/features/users/invitations_controller_spec.rb
spec/services/csv_export/user_exporter_spec.rb

Une autre branche, que vous pourriez trouver intéressante (ou non). Les tests échouent, et c’est normal: le comportement de `normalize_name` a changé, et les données sont normalisées automatiquement à la création.
Je pense que c’est pertinent; ça devrait éviter une partie des erreurs à l’import.

Sanitize data on input

---

app/views/pages/_newsletter.html.haml

avoid closing a paragraph in the wrong place

---

config/initializers/devise.rb

Plusieurs utilisateurs ont été importés avec des virgules ou point virgules dans leur adresse email et n'ont donc jamais reçu l'email d'invitation.
Nouvelle regex : /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/`

Contraint d'avantage le format des emails

---

app/views/reminders/_diagnosis.haml
app/views/reminders/_needs.html.haml

Je n'ai pas réussi à reproduire le problème en local mais je pense que si un besoin est dans le panier "à rappeler" qu’aucune action n'ai faite et qu'il passe dans le panier suivant au bout d'un certain temps. Le Diagnosis reste inchangé car il n'a pas été mis à jour, en rajoutant l'action du panier courant dans la clé du cache ça peut résoudre le problème. Avec un peu de chance ça va résoudre le problème des Diagnosis dont les boutons n'apparaissaient pas tout le temps.
closes #1562

change la clé du cache pour les analyses dans les relances

---

app/controllers/needs_controller.rb

Je ne sais pas si ça change grand chose et ce que fait Rails quand on lui uniquement la collection. Mais il y a encore des erreurs entre le chiffre dans le menu sur /besoins et la liste affichée

change key cache for received needs

---

app/models/solicitation.rb

@clairezed l'export des sollicitations ne fonctionne pas a cause d'un `invers_of` je push ça en attendant

temporary fix invers_of

---

Gemfile
Gemfile.lock
app/controllers/newsletters_controller.rb
app/controllers/shared_controller.rb
app/services/company_mailer_service.rb
config/initializers/sentry.rb

- passage à sentry standard suite à l'incendie des serveurs de https://sentry.data.gouv.fr
- on en profite pour mettre à jour la gem sentry
close #1595

Mise à jour de sentry

---

app/front/javascripts/pages/siret_autocomplete.js
app/views/feedbacks/create.js.haml
app/views/feedbacks/destroy.js.haml

closes #1668 
et essaye aussi de traiter `Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /rech-etablissement?query=34063900400068&non_diffusables=false` (https://sentry.io/organizations/place-des-entreprises/issues/2307965094/?project=5671428&query=is%3Aunresolved)

Fix bug js remove() avec ie11

---

config/environments/production.rb

#1666
Après l'utilisation de project-zap (https://www.zaproxy.org/) il en est ressorti qu'il nous manquait des headers pour les requêtes en général et celle des assets

Ajoute des headers pour les requetes

---

app/services/stats/base_stats.rb

to prevent error `Database and Ruby have inconsistent time zone info`

specify timezone for group_by

---

app/policies/expert_policy.rb
app/views/matches/_match.haml
spec/policies/expert_policy_spec.rb

Sur la page d'un besoin affiche les experts supprimés uniquement aux admins

---

app/models/match.rb

close #1730 
@LucienMLD il y avait une raison précise au délai de 5 minutes pour les `additional_match` ? j'ai réduit le délais de 5 min à 30 secondes ; tu diras s'il faut être vigilant là-dessus

Ajouter l'icone "ambulance" lorsque  les experts ont été ajoutés + de 30 secondes après les 1eres MER (au lieu de 5min)

---

app/views/needs/_menu.html.haml

Suite à la mise à jour de rails #1735 ... 
Une erreur a popé à un moment dans sentry, sans que j'arrive à la reproduire ni que nos tests ne le signale ; mais bon cette modif ne mange pas de pain.

Fix polymorphic_path with sym in boite de reception

---

app/admin/solicitation.rb

https://sentry.io/organizations/betagouv-f7/issues/2386923063/?environment=production&project=5747178&query=is%3Aunresolved
J'ai essayé de faire fonctionner le filtre des `landing_options_slug` mais sans succès j'ai préféré l'enlever. On peut les trier avec le champ de recherche sur /sollicitations

Delete filters that do not work

---

app/views/about/mentions_d_information.fr.html.erb
app/views/shared/_matomo.html.erb
app/views/shared/_tarteaucitron.html.erb
app/views/solicitations/_solicitations_tags_js.html.erb
config/initializers/content_security_policy.rb

j'ai des doutes que ça règle toutes les erreurs mais j'ai trouvé cette parade sur pas mal de posts qui en parlent, c'est à ajouter sur les scripts qui ne sont pas chargé dans le head d'une page
https://sentry.io/organizations/betagouv-f7/issues/2384890408/?environment=production&project=5747178&query=is%3Aunresolved+ujs&statsPeriod=14d

prevent rails-ujs is already been loaded

---

app/views/landings/new_solicitation.html.haml

C'était dû à https://github.com/betagouv/place-des-entreprises/commit/4accd9ba53df85694b3f9d0a081a3c8e660ef115#diff-848ede2b938a196347b04a913aab18ff89b217b88991eb2b9299b01aa786d6ae, qui nous a échappé à tous les 2.
close #1792

Remet les accompagnements à côté du formulaire

---

app/helpers/needs_helper.rb
app/views/needs/show.haml

closes #1794 
le texte en haut de la sélection des besoins était bien pris en compte sur la fiche
mais pas celui en dessous d'un sujet

ajoute la description du besoin sur une fiche besoin

---

app/services/csv_import/user_importer.rb
spec/services/csv_import/user_importer_spec.rb

close #1856 
Les modifs viennent à l'encontre du fonctionnement actuel : 
Le fonctionnement actuel ne permet pas de mettre à jour les sujets (par exemple, d'en supprimer), mais uniquement d'en ajouter.
Pour pouvoir supprimer des sujets, à partir de maintenant il faudra vraiment que tous les membres d'une équipe aient scrupuleusement les croix au même endroit, il n'y aura plus de mélange automatique.

Mise a jour des sujets des conseillers via import

---

app/controllers/annuaire/advisors_controller.rb
app/models/expert.rb
app/views/annuaire/advisors/_table.html.haml
config/locales/views.fr.yml

- décalage de décompte `advisors` / `experts`
- comparaison d'email sans `downcase`
- affichage des sujets d'institution au survol du décompte

Petites corrections annuaire

---

app/admin/subject.rb
app/models/subject.rb
lib/tasks/delete_old_subjects.rake

Ajout d'une tache rake pour mettre a jour le sujet des besoins qui ont des sujets obsolètes avec le sujet actuel "Autre besoin non référencé" et permettre de supprimer les sujets sans besoins directement en admin.
closes #1883

suppression des anciens sujet

---

app/controllers/annuaire/advisors_controller.rb
app/front/stylesheets/components/table.sass
app/views/annuaire/advisors/_table.html.haml

Plutôt que de réduire la taille des lignes j'ai masqué les antennes ou on n’importait pas d'utilisateurs
Change aussi la couleur quand il y a plusieurs utilisateurs sur un sujet en orange
closes #1886 
closes #1889

Masque les autres antennes à l'import d'utilisateurs

---

app/mailers/user_mailer.rb
app/models/clockwork.rb
spec/system/users/invitations_controller_spec.rb

close #1935 
Pistes de vraies résolutions pour le mail `remind_invitation` :
- simplement réinviter 
- trouver un moyen d'avoir un template spécifique en passant des paramètres
- créer un nouveau token lors de l'envoi du rappel, enregistrer la verison chiffrée en BDD, utiliser `raw_token` dans l'invitation

Réparation envoi des relances d'invitation

---

app/admin/landing_theme.rb

déplace les checkboxs des champs optionnels des formulaires pour qu'on ai moins tendance à cliquer dessus sans faire exprès. En modifiant les logos par exemple
closes #1986

move optional form fields

---

app/services/csv_import/base_importer.rb

j'ai pas fait de tests pour un si petit changement, on a déjà pas mal de tests sur l'import et en rajouter une couche pour un espace ça fait beaucoup je trouve

supprime les espaces en trop dans les CSV à l'import

---

lib/tasks/push_to_production.rake

A chaque fois dans le message que l'on copie/colle on avait un commit qui était déjà en prod

retire le message du dernier commit connue sur Main dans la tache push_to_production

---

app/models/diagnosis.rb
app/models/need.rb
spec/models/need_spec.rb

close #2134 
Correction rapide en attendant de faire mieux les choses. Pistes :
- soit un service de mise à jour du diagnostic (qui gérerait pas mal du code de `steps_controller` et permettrait de tester de façon isolée la mise à jour des steps),
- soit une machine à état

Correction need status

---

Gemfile
Gemfile.lock
app/admin/antenne.rb
app/views/annuaire/antennes/_table.html.haml

En lien avec #2195 et #2201 : la modélisation des managers n'est, en fait, pas stable -> des managers d'une antenne peuvent appartenir à une autre antenne. En attendant de clarifier le fonctionnement, on affiche de nouveau les anciens champs.
PR définitive en cours : #2212

Quick fix managers

---

app/models/concerns/with_slug.rb
app/models/institution.rb
app/models/landing.rb
app/models/landing_subject.rb
app/models/landing_theme.rb
spec/models/institution_spec.rb

close #2221 
Seul changement notable : les slugs des Institutions, dont les "_" sont remplacés par des "-". J'ai l'impression que la seule justification à des slugs avec underscore était pour l'affichage des logos, mais comme on a changé le système, le remplacement pose pas de pb de ce côté-là.
Tu penses peut-être à un cas que ni moi ni les tests n'avons en tête, @LucienMLD  ?

Amélioration de la gestion des slugs

---

app/views/landings/landing_subjects/_new_solicitation_form.html.haml
config/locales/views.fr.yml

Bloque le champ siret à 14 caractères et désactive l'autocomplete en attendant de le faire fonctionner avec 14 chiffres
close #2270

disable autocomplete for siret

---

app/admin/solicitation.rb

Normalement on ne va pas sur la page d'édition d'une sollicitation, mais au cas où, c'est mieux que d'avoir une erreur 500

prevent undefined input for enum

---

app/controllers/about_controller.rb
app/helpers/breadcrumbs_helper.rb
app/views/about/mentions_d_information.fr.html.erb
app/views/landings/landing_subjects/_new_solicitation_form.html.haml
app/views/landings/landings/_pde_partnership_mention.html.haml
app/views/layouts/pages.html.haml
app/views/pages/_breadcrumbs.html.haml

Enlève le lien sur le logo en bas de page si on active l'affichage du partenariat.
Enlève `X-Frame-Options` sur la page des mentions d'information quand on vient d'une iframe + retrait de la navbar et amélioration du fil d'ariane
closes #2353

améliore l'affichage des mentions d'informations dans une iframe

---

app/models/user.rb
app/services/csv_import/user_importer.rb
spec/models/user_spec.rb

Des utilisateurs sont créés sans expert `personal_skillsets`, ce qui téhoriquement ne devrait pas être possible. 
Les callback `  after_create :create_personal_skillset_if_needed` et `after_update :synchronize_personal_skillsets` semble ne pas bien fonctionner, ou bien ne pas toujours être appelés. Situation difficile à débuguer ; dans l'immédiat je modifie `synchronize_personal_skillsets` pour créer cet expert s'il est manquant.

Créé personal_skillsets à la MAJ si besoin

---

app/views/shared/_matomo.html.erb

https://fr.matomo.org/faq/how-to/how-do-i-track-a-website-within-an-iframe/
https://developer.matomo.org/api-reference/tracking-javascript
closes #2404

récupère les événements Matomo dans les iframes (normalement)

---

app/views/landings/landing_subjects/_new_solicitation_form.html.haml

c'est quand on cliquait sur ce lien dans une landing normal
closes #2399

fix une erreur sur la page des mentions d'informations

---

app/controllers/concerns/iframe_prefix.rb
app/controllers/landings/landings_controller.rb
app/helpers/solicitation_helper.rb
app/views/landings/landing_subjects/_card.html.haml
app/views/sitemap/sitemap.xml.builder
config/routes.rb
spec/a11y/a11y_spec.rb
spec/controllers/landings/landings_controller_spec.rb

- modification de la route `new_solicitation`, pour arrêter de perdre les bots, et rester cohérent (pas de redirection requise) : https://sentry.io/organizations/place-des-entreprises-org/issues/3314753404/events/?cursor=0%3A100%3A0&project=5747178
- correction d'une url dans la `sitemap` : https://sentry.io/organizations/place-des-entreprises-org/issues/3314427368/?environment=production&project=5747178&query=is%3Aunresolved

Jeudi debug

---

Gemfile
Gemfile.lock

Matrix was removed in ruby 3.1
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

add gem matrix

---

config/locales/models.fr.yml

Le message d'erreur actuel est incompréhensible pour les utilisateurs et utilisatrices

Amélioration traduction reset_password_token

---

app/front/javascripts/pages/controllers/pages_siret_autocomplete_controller.js
app/front/javascripts/shared/controllers/siret_autocomplete_controller.js
app/services/api_insee/base.rb

Les Api présentent en ce moment des faiblesses qui bloquaient l'autocomplétion. 
Trois modifications pour fluidifier :
- affichage d'un message standard en bon francais dans le champs d'autocompletion si une erreur inattendue est renvoyée par l'API
- en parallèle, envoi d'un notif d'erreur dans notre gestionnaire d'erreurs
- apparition du lien pour saisir manuellement son siret en cas d'erreur (pour le moment, c'était qu'en cas de résultat vide, ce qui est clairement pas suffisant)

Amélioration erreurs autocompletion siret

---

app/models/user.rb
spec/models/user_spec.rb

Deux experts personnel pour le même utilisateur étaient créés
closes #2672

corrige la duplication d'un utilisateur

---

app/views/application/_navbar.html.haml

Permet à la recherche par territoire d'être correctement chargé

desactive turbo sur les liens des relances et sollicitations

---

app/controllers/annuaire/antennes_controller.rb
app/controllers/annuaire/users_controller.rb
app/front/stylesheets/components/cards.sass
app/views/annuaire/users/import.html.haml
app/views/stats/_stats_chart.haml
app/views/stats/public/_load_stats.html.haml

- page des sollicitations : logo décalé - https://trello.com/c/SwEo2rGz/154-page-des-sollicitations-logo-d%C3%A9cal%C3%A9
- import sur staging et en prod depuis l'annuaire semble bloqué : /155-import-sur-staging-et-en-prod-depuis-lannuaire-semble-bloqué
- Stats : Légende du tableau est à l'envers (janvier vers juillet, alors que les nombres sont juillet vers janvier) - https://trello.com/c/68oOXT2B/152-imagepng

Debug 230209

---

app/models/landing_subject.rb
spec/models/landing_subject_spec.rb

close #2883 
A faire tourner en console : 
```ruby
LandingSubject.all.map do |ls|
ls.send(:autoclean_textareas)
ls.save
end
```

Nettoyage automatique des landing subjects

---

app/front/stylesheets/components/cards.sass
app/front/stylesheets/components/components.sass
app/helpers/badges_helper.rb
app/views/application/_user_admin_view.haml
app/views/feedbacks/_feedback.haml
app/views/reminders/experts/_expert.haml
config/locales/views.fr.yml

close #2860 
Reste à gérer : " la couleur sur la partie grisée des cartes pour égayer l’interface, selon les 3 catégories"
A faire une fois que la relance expert est calée

Relance cards

---

app/services/reminders_service.rb

⚠️  Une fois mep il faudra supprimer les `reminders_registers` des experts sans utilisateurs
closes #2928

ne prend pas les experts sans utilisateurs dans les relances

---

app/views/feedbacks/create.js.haml

quand on clôturait un message avec une aide proposée et qu'on laissait un commentaire, un texte nous indiquant qu'on avait bien refusé était affiché

corrige le message affiché quand on cloture un besoin et laisse un commentaire

---

app/models/feedback.rb
spec/models/feedback_spec.rb

C'est un raté quand on a simplifié l'envoie des emails en décembre. On a oublié quand c'est envoyé par un admin
closes #3045

Notifie les experts qui n'ont pas pris en charge quand c'est un admin qui poste un commentaire

---

app/admin/solicitation.rb
config/locales/models.fr.yml

Si une sollicitation n'a pas d'analyse ou a une analyse en cours, on supprime l'analyse et la sollicitation. S'il y a une analyse transmise, on affiche un message d’erreur.
closed #3064

Améliore la suppression des sollicitations en admin

---

app/services/api_consumption/models/company/api_entreprise.rb
app/services/api_rne/companies/base.rb
spec/fixtures/files/api_rne_companies.json
spec/services/api_consumption/models/company/api_entreprise_spec.rb

J'anticipe la disparition prochaine de l'API RNM en récupérant les infos registres renvoyées par l'API RNE. 
Pas sûre de la stabilité de l'API RNE, je propose donc de brancher quand il sera temps et de surveiller les données renvoyées d'ici là
Aussi : suppression de l'initialisation de la couverture de référencement (tâche lancée en prod)

Add registre info rne

---

app/models/clockwork.rb
app/views/application/_navbar.html.haml

Il y a un décalage de timezone avec le serveur, vraisemblablement.
On voudrait que les paniers soient générés vers 13h, or ils sont générés vers 15h. 
Quick fix pour diminuer les incompréhensions des collègues.
A terme, on aura peut-être une harmonisation des time zones à rechercher

Earlier reminders generation

---

app/models/antenne.rb
app/services/antenne_coverage/deduplicated_job.rb
spec/services/antenne_coverage/deduplicated_job_spec.rb

close #3163 
Ca devrait déjà améliorer les perfs, un peu. A noter : `/models/concerns/many_communes.rb:22` continue à prendre pas mal de temps ; mais ce serait bien que ça tienne encore le choc d'ici la refonte des territoires

Prevent multiple update_antenne_coverage calls

---

app/models/antenne.rb

On passe à 2 requêtes SQL au lieu de 3 requêtes + X requêtes supplémentaires (X étant le nombre d'antennes dans la région de l'antenne sur laquelle on se trouve) + du code ruby pour itérer
Mes premières vérifications sont bonnes, il faut que je poursuive pour s'assurer d'avoir ceinture et bretelles.

Optimize Antenne#territorial_antennes

---

app/services/reminders_service.rb
spec/controllers/reminders/experts_controller_spec.rb
spec/services/reminders_service_spec.rb
spec/support/reminders_spec_helper.rb

Jusqu'ici, le code intégrait les experts avec des vieux besoins > 2, et non >= 2.

Poule : dans panier à partir de 2 et non de 3

---

app/views/annuaire/users/_table.html.haml

En lien avec https://trello.com/c/m8xb7I26/358-annuaire-on-ne-voit-pas-le-nom-de-lantenne-si-trop-long
Franchement, je comprends pas pourquoi les cases sont si longues, j'ai pas réussi à débugguer. Je me demande si ce bug là date pas d'assez longtemps en fait (en enlevant le + gros des dernières modifs, ça flanche toujours).
Alors comme pis aller, je propose d'afficher le nom de l'antenne au survol. 
On pourra faire encore mieux quand on aura le composant tooltip à dispo !

Ajout nom antenne au survol dans l'annuaire

---

app/services/reminders_service.rb

au début : 46 secondes pour jouer le `each` sur `@experts_with_active_matches` 
avec le `find_each` : 43 secondes
avec le `joins` : 37 secondes
Je ne sais pas si ça va régler le problème du worker par contre

améliore les performances de la génération des paniers qualité

---

app/admin/feedback.rb
app/models/feedback.rb
config/locales/models.fr.yml

J'ai fait une première version simple pour qu'Adeline puisse trier les commentaires par date de besoin. Mais quand on voudra se servir de cet onglet pour les autres types de commentaires, il faudra adapter les filtres en fonction du scope
closes #3341

Ajoute des filtres pour les commentaires en admin

---

config/initializers/content_security_policy.rb

`script-src-elem` prend par défaut `script-src` donc on en a pas besoin, en plus le site https://cspvalidator.org/ nous dit que c'est pas reconnu comme entête.
doc : https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem

retire une csp qui fait doublon

---

app/models/need.rb
app/services/stats/companies/by_employees.rb

- fix rapide pour le graph des entreprises par nombre d'employés qui ne s'affiche plus. L'entreprise 93192 à un code effectif égale à `""`  (https://conseillers-entreprises-org.sentry.io/issues/5643769541/?project=5747178&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&stream_index=0)
- ne pas prendre les besoins d'entreprises anonymisé dans l'historique. closes #3547

jeudi débug

---

app/controllers/solicitations_controller.rb
app/services/create_diagnosis/find_relevant_expert_subjects.rb

/!\ ne fonctionne que si on rajoute des sujet à l'Expert Ademe (car on filtre sur les `experts_subjects`
```ruby
ademe_expert = Expert.find(22483)
ademe_expert.institution.institutions_subjects.each do |is|
ademe_expert.experts_subjects.create(institution_subject: is)
end
```

Ajout automatique de l'Ademe pour les besoins TEE

---

app/models/concerns/diagnosis_creation.rb
spec/models/concerns/diagnosis_creation_spec.rb

Debug de : les sollicitations mauvaises qualités reviennent chez nous avec une analyse à l'étape ``contact`

Fix Solicitation qui reviennent à l'étape contact

---

app/controllers/concerns/load_filter_options.rb
app/views/stats/team/_stats_params.haml

closes #3663 
Pour reproduire le bug il faut aller dans les stats équipe, sélectionner une institution et filtrer. Une fois la page recharger dans le select des thèmes il y avait plusieurs lignes pour un même theme

Corrige les filtres des stats équipe

---

app/models/clockwork.rb
doc/05-gotchas.md
lib/tasks/rattrapage_api_rne.rake

close #3670
Soupçon que les erreurs RNE relatives au port 443 soient liées au dépassement involontaire de leurs limitations (par exemple : Une limitation sur le nombre d’authentification à 5 authentification toutes les 30 secondes et qui bannit 10 minutes)
-> Avoir un compte RNE technique juste pour le dev ?

Tâche de rattrapage de l'API RNE

---

app/views/solicitations/step_contact.html.haml

En fait le champs de type `tel` affiche juste un clavier dans certains cas, surtout quand on est sur mobile
closes #3674

Ne permet que des chiffres pour le champ téléphone

---

app/controllers/reminders/experts_controller.rb
spec/system/users/passwords_controller_spec.rb

- Essaie pour fixer un flaky test. Attendre que la page soit chargé avant de regarder si "Besoins reçus" apparait

Modifie l'ordre des besoin dans la boite de récéption d'une équipe depuis le panier qualité

---

app/helpers/reminders_helper.rb

Pour une raison obscure on ne peut plus cliquer sur les boutons en prod
Reverts betagouv/conseillers-entreprises#3707

Revert "Change le bouton des relances par un formulaire sans Turbo"

---

app/services/api/recherche_entreprises/search/base.rb
app/services/diagnosis_creation/create_automatic_diagnosis.rb
spec/services/diagnosis_creation/create_automatic_diagnosis_spec.rb

1/ Dans API Rech entreprise, j'ai enlevé des codes d'erreur critique le 400, qui est un code bien géré chez eux avec un retour légitime. Ca nous évitera d'être spammé sur sentry pour cette fausse erreur
2/ On avait dans certains cas des erreurs dans la creation d'analyse qui étaient mal gérés. Par exemple, en cas de siret foireux -> ce n'est pas une erreur d'API, ce n'est pas une erreur dans l'objet analyse, mais une BasicError... Donc ça n'entraînait pas un rollback. J'ai remédié à ça, car alors la machine essayait de sauver une solicitation avec une analyse non persistée. Foireux.

Debug 241128

---

app/assets/stylesheets/components/cards.sass
app/controllers/application_controller.rb
app/controllers/conseiller/solicitations_controller.rb
app/controllers/emails/solicitations_controller.rb
app/helpers/solicitation_helper.rb
app/models/solicitation.rb
app/views/conseiller/solicitations/_retry_diagnosis.html.haml
app/views/conseiller/solicitations/_solicitation.haml
app/views/conseiller/solicitations/_solicitation_actions.html.haml
app/views/conseiller/solicitations/_solicitation_badges.html.haml
app/views/conseiller/solicitations/remove.js.haml
app/views/feedbacks/_form.html.haml
app/views/layouts/application.html.haml
app/views/shared/_flashes.html.haml
config/locales/views.fr.yml
spec/controllers/emails/solicitations_controller_spec.rb
spec/features/solicitations/send_generic_emails_spec.rb
spec/helpers/solicitation_helper_spec.rb

Met à jour les cartes sollicitation

---

app/models/need.rb
spec/models/need_spec.rb

L'ajout d'une question pour le sujet "Investissement" a rendu les besoins "investissement" en cours invalides, et empêchait donc le fonctionnement du callback `update_status`.
Le plus simple m'a semblé être de skipper la validation, mais il y a peut-être un loup que je n'ai pas levé ?
close #3850

Fix pb dans les paniers risques d'échec

---

.pre-commit-config.yaml
doc/01-setup.md

Ajoute un GitGuardian en pre-push pour vérifier qu'aucun secret n'est push. GitGuardian est installé en action mais ne vérifie qu'une fois le code publié

Ajoute Gitguardian en pre-push

---

app/services/effectif/code_effectif.rb
spec/services/effectif/code_effectif_spec.rb

Suite à un problème dans la génération des fichiers des MERs mensualisés

Fix Intitulé effectif quand code_effectif vide

---

app/controllers/reminders/experts_controller.rb
app/views/application/_navbar.html.haml

| Avant | Après |
|-|-|
| <img width="791" height="372" alt="Capture d’écran 2025-08-11 à 17 00 02" src="https://github.com/user-attachments/assets/61656369-43b3-4f70-854a-a48640bc0eb2" /> | <img width="791" height="372" alt="Capture d’écran 2025-08-11 à 16 58 47" src="https://github.com/user-attachments/assets/dfb46602-bc96-4fb3-a93a-32a17b0740a3" /> |
Seul le panier “Entrées” affichait bien l’onglet “Paniers Qualité” comme activé. C’est parce que le `active_link_to` dans la navbar pointait sur `/relances/experts/arrivees`, et donc les autres paths (comme `/relances/experts/superieur-a-cinq-besoins`) ne correspondait pas au critère “actif”. 
Le fix consiste à utiliser `/relances/experts` comme lien dans la navbar, et à rediriger ce path vers `/relances/experts/arrivees`; auparavant, …

Fix active link not highlighted in reminders sections

---

.github/workflows/update-dependencies.yml

fixes https://github.com/betagouv/conseillers-entreprises/security/code-scanning/10, I guess?

Use explicit permissions of the update-dependencies workflow

---

.circleci/config.yml

Fix yaml indentation for circleci jobs filters (followup #4021)

---

app/mailers/expert_mailer.rb
app/mailers/user_mailer.rb
spec/mailers/expert_mailer_spec.rb
spec/mailers/user_mailer_spec.rb

Ça change pas grand chose, mais ça fait un poil de code en moins. Les hooks `before_deliver` et `after_deliver` ont été ajouté dans rails 7.1 pour ça.
- `throw :abort` est la façon “normale“ d’annuler [dans une callback](https://api.rubyonrails.org/classes/ActiveSupport/Callbacks.html).
-  Malheureusement, ce n’est pas le comportement dans [`AbstractController::Callbacks`](https://github.com/rails/rails/blob/b0c813bc7b61c71dd21ee3a6c6210f6d14030f71/actionpack/lib/abstract_controller/callbacks.rb#L34), le `terminator` ne `catch` pas `:abort`, mais regarde si l’action a été `performed?` (c’est ce qui permet dans un controller rails de ne pas exécuter l’action si on répond une 404 dans un before_action).
- Or, `ActionMailer::Base` est en fait un controller, il hérite de …

Filtrer les emails à ne pas envoyer avec before_deliver

---

app/views/companies/_company.html.haml
app/views/companies/_errors.html.haml
app/views/companies/_facility.html.haml
app/views/companies/_mandataire.html.haml
config/locales/views.fr.yml

closes #3998
J’en ai profité pour corriger l’affichage des tables qui n’était pas très content avec le DSFR.
| Avant | Après |
|-|-|
| <img width="1048" height="1137" alt="Capture d’écran 2025-09-22 à 13 15 39" src="https://github.com/user-attachments/assets/93a39219-753a-4f0f-bb87-00875a17347d" /> | <img width="1048" height="1137" alt="Capture d’écran 2025-09-22 à 13 14 48" src="https://github.com/user-attachments/assets/4e8af44d-28ea-4635-b217-de2ffbb20637" /> |
Cette PR ne fait qu’afficher les erreurs “standard_error” et “unreachable”. Je vais faire une autre issue pour un réusinage de la gestion des erreurs pour les apis. Notamment:
- Remettre à plat la distinction entre les erreurs majeurs (qui déclenchent `TechnicalError`, et qui pour l’instant sont affichées sous formes de flash) …

Afficher les erreurs d’api tierce sur la page entreprise

---

Gemfile
Gemfile.lock
config/initializers/caxslx.rb

fixes #4008 
Ça ne change pas grand chose dans les faits par rapport à #4003, mais ça nous évite de fixer une version de dépendance.
ℹ️ Surveiller les prochaines releases de caxslx, pour désactiver ce patch une fois que https://github.com/caxlsx/caxlsx/pull/482 est mergée.

Disable zip64 globally to make our Excel exports compatible with Google Sheets
